/* ============================================================
   GRAMMAR KNOWLEDGE BASE (spec §18, §19)
   Every item: id, level, category, prerequisites, explanation,
   pattern, rules, examples, negative examples, common mistakes,
   exceptions, review rules. The `prereq` field forms the grammar
   prerequisite graph the learning engine walks before it
   recommends a topic.

   The seven ids from Phase 2.5 (g_gender, g_praesens, g_akkusativ,
   g_dativ, g_wordorder, g_modal, g_perfekt) are preserved verbatim
   so existing learner progress keeps resolving.
   ============================================================ */
const GRAMMAR_DB = [

/* ---------------- A0 ---------------- */
{id:'g_alphabet', level:'A0', category:'pronunciation', title:'The German Alphabet & Sound Rules',
 explanation:'German spelling maps onto sound far more consistently than English. Once you know the rules below, you can read almost any German word aloud correctly, even one you have never seen.',
 pattern:'letter → sound (fixed mapping, few exceptions)',
 rules:['ä = the "e" in "bed"; ö = say "e" with rounded lips; ü = say "ee" with rounded lips.',
  'ß (scharfes S) is always a voiceless "ss" and never begins a word.',
  'ei is pronounced like English "eye"; ie is pronounced like English "ee".',
  'sch = "sh". At the start of a word sp = "shp" and st = "sht".',
  'ch after a, o, u is a rough back sound (Buch); after e, i, ä, ö, ü, and consonants it is soft (ich).',
  'v is usually "f" (Vater), w is "v" (Wasser), z is "ts" (Zeit), s before a vowel is "z" (Sonne).'],
 examples:[{de:'mein – Bier', en:'"mine" – "beer" (ei = eye, ie = ee)'},{de:'Schule – sprechen – Stadt', en:'school – to speak – city ("sh", "shp", "sht")'},{de:'Buch – ich', en:'book – I (hard ch vs soft ch)'}],
 negativeExamples:[{wrong:'"Bier" read as "byer"', right:'"Bier" is read "beer" — ie = ee'}],
 mistakes:['Reversing ei and ie, because English spelling suggests the opposite.','Reading w as English "w" instead of "v".'],
 exceptions:['In loanwords v is often pronounced "v": Vase, Villa, Vitamin.'],
 prereq:[]},
{id:'g_capitalisation', level:'A0', category:'spelling', title:'Nouns Are Always Capitalised',
 explanation:'Every German noun is written with a capital letter, anywhere in the sentence. This is not stylistic — it is a spelling rule, and it is also a reading aid: a capital letter mid-sentence tells you a noun is starting.',
 pattern:'… das Haus … der Mann … ein Buch …',
 rules:['All nouns are capitalised: der Tisch, die Arbeit, das Kind.','Nominalised words are capitalised too: das Essen (the food/eating), beim Lernen (while learning).','"Sie" (formal you) is capitalised; "sie" (she/they) is not.'],
 examples:[{de:'Der Mann kauft ein Buch.', en:'The man buys a book.'},{de:'Wie heißen Sie? – Sie heißt Anna.', en:'What is your name (formal)? – She is called Anna.'}],
 negativeExamples:[{wrong:'der tisch', right:'der Tisch'}],
 mistakes:['Writing nouns lower case out of English habit.'],
 exceptions:[], prereq:['g_alphabet']},
{id:'g_pronouns', level:'A0', category:'pronouns', title:'Personal Pronouns (Nominative)',
 explanation:'The six German subject pronouns. German distinguishes three "you" forms: du (one person, informal), ihr (several people, informal) and Sie (formal, singular or plural, always capitalised).',
 pattern:'ich / du / er, sie, es / wir / ihr / sie, Sie',
 rules:['ich = I, du = you (informal sg.), er/sie/es = he/she/it, wir = we, ihr = you (informal pl.), sie = they, Sie = you (formal).','er/sie/es follow grammatical gender, not biological: der Tisch → er, die Lampe → sie, das Kind → es.','Sie (formal) is always capitalised and takes the same verb form as sie (they).'],
 examples:[{de:'Ich bin Ahmed. Wer bist du?', en:'I am Ahmed. Who are you?'},{de:'Wo ist der Schlüssel? – Er ist hier.', en:'Where is the key? – It is here. (der Schlüssel → er)'}],
 negativeExamples:[{wrong:'Wo ist der Tisch? – Es ist hier.', right:'Wo ist der Tisch? – Er ist hier.'}],
 mistakes:['Using "es" for all objects, as English uses "it" — German pronouns follow the noun\'s gender.'],
 exceptions:[], prereq:['g_capitalisation']},
{id:'g_sein_haben', level:'A0', category:'verb-conjugation', title:'sein and haben',
 explanation:'The two most frequent German verbs. Both are irregular and must be memorised: almost every sentence you will build in the next months contains one of them, and both are also the auxiliaries of the Perfekt later on.',
 pattern:'ich bin / du bist / er ist … | ich habe / du hast / er hat …',
 rules:['sein: ich bin, du bist, er/sie/es ist, wir sind, ihr seid, sie/Sie sind.','haben: ich habe, du hast, er/sie/es hat, wir haben, ihr habt, sie/Sie haben.','German uses sein for age: Ich bin 20 Jahre alt.','haben expresses possession and is followed by the accusative: Ich habe einen Bruder.'],
 examples:[{de:'Ich bin müde.', en:'I am tired.'},{de:'Sie hat zwei Kinder.', en:'She has two children.'},{de:'Wir sind aus Kabul.', en:'We are from Kabul.'}],
 negativeExamples:[{wrong:'Ich habe zwanzig Jahre.', right:'Ich bin zwanzig Jahre alt.'}],
 mistakes:['Using haben for age, following Romance-language or Arabic patterns.','"du bist" mixed up with "du hast".'],
 exceptions:[], prereq:['g_pronouns']},

/* ---------------- A1 ---------------- */
{id:'g_praesens', level:'A1', category:'verb-conjugation', title:'Present Tense (Präsens) Conjugation',
 explanation:'German verbs change their ending depending on who is doing the action. Regular verbs follow a predictable pattern; some common verbs are irregular and change their stem vowel in the du and er/sie/es forms.',
 pattern:'Stamm + e / st / t / en / t / en',
 rules:['Regular pattern: ich -e, du -st, er/sie/es -t, wir -en, ihr -t, sie/Sie -en.','Stems ending in -t or -d insert an e: du arbeitest, er arbeitet.','Stems ending in -s, -ß, -z, -x lose the s of -st: du heißt, du tanzt.','Strong verbs change the stem vowel only in du and er/sie/es: fahren → du fährst, er fährt; sprechen → du sprichst, er spricht; nehmen → du nimmst, er nimmt.','German has one present tense: "ich lerne" covers both "I learn" and "I am learning".'],
 examples:[{de:'Ich lerne Deutsch. Du lernst Deutsch. Er lernt Deutsch.', en:'I learn German. You learn German. He learns German.'},{de:'Du arbeitest viel.', en:'You work a lot.'},{de:'Sie spricht drei Sprachen.', en:'She speaks three languages.'}],
 negativeExamples:[{wrong:'du fahrst', right:'du fährst'},{wrong:'er sprecht', right:'er spricht'}],
 mistakes:['Forgetting the vowel change in strong verbs (du fahrst → du fährst).','Building a progressive form with sein: "Ich bin lernen" does not exist.'],
 exceptions:['Modal verbs and wissen follow their own pattern (see g_modal).'],
 prereq:['g_sein_haben'], reviewRules:{intervalBoost:0.9, minAttempts:6}},
{id:'g_gender', level:'A1', category:'articles', title:'Nouns & Gender (der / die / das)',
 explanation:'Every German noun has a grammatical gender — masculine (der), feminine (die), or neuter (das). Gender is mostly not predictable from meaning, so it is learned together with each new word, not applied afterward.',
 pattern:'der + Nomen | die + Nomen | das + Nomen',
 rules:['Always learn a noun together with its article: not "Tisch" but "der Tisch".','In the plural all genders take die: der Tisch → die Tische.','Reliable endings: -ung, -heit, -keit, -schaft, -ion, -tät, -ei are die. -chen and -lein are das. -er (agent nouns), -ling, -ismus are der.','Male/female people usually match biological gender: der Vater, die Mutter — but das Mädchen is neuter because of -chen.'],
 examples:[{de:'der Tisch, die Tische', en:'the table, the tables'},{de:'die Wohnung, die Wohnungen', en:'the apartment, the apartments'},{de:'das Kind, die Kinder', en:'the child, the children'}],
 negativeExamples:[{wrong:'die Mädchen (singular)', right:'das Mädchen'}],
 mistakes:['Guessing gender from the English meaning.','Learning the bare noun without its article, then having to relearn it.'],
 exceptions:['das Mädchen, das Fräulein — diminutives override biological gender.'],
 prereq:['g_capitalisation'], reviewRules:{intervalBoost:0.8, minAttempts:8}},
{id:'g_plural', level:'A1', category:'articles', title:'Plural Formation',
 explanation:'German has five plural patterns rather than one -s. The plural is a property of each noun and is learned with it, exactly like the gender. All plurals take die in the nominative.',
 pattern:'-e / -er / -(e)n / -s / no ending (± Umlaut)',
 rules:['-e (often + Umlaut): der Tisch → die Tische, der Stuhl → die Stühle.','-er (often + Umlaut): das Kind → die Kinder, das Buch → die Bücher.','-(e)n: die Frau → die Frauen, die Lampe → die Lampen. Nearly all feminine nouns take -n/-en.','-s: mostly loanwords: das Auto → die Autos, das Handy → die Handys.','No ending (sometimes + Umlaut): der Lehrer → die Lehrer, der Vater → die Väter.'],
 examples:[{de:'ein Buch → zwei Bücher', en:'one book → two books'},{de:'eine Wohnung → drei Wohnungen', en:'one flat → three flats'}],
 negativeExamples:[{wrong:'die Kinds', right:'die Kinder'}],
 mistakes:['Adding -s to everything, as in English.'],
 exceptions:['Nouns ending in -in double the n: die Lehrerin → die Lehrerinnen.'],
 prereq:['g_gender']},
{id:'g_wordorder_main', level:'A1', category:'word-order', title:'Verb Second: The Main Clause',
 explanation:'The single most important structural rule of German: in a statement the conjugated verb stands in position two. Position one may be the subject, a time expression, a place or an object — whatever comes first, the verb still follows it immediately.',
 pattern:'[Position 1] – [VERB] – [rest]',
 rules:['Subject first is the neutral order: Ich gehe heute ins Kino.','Any other element may take position one, and then the subject moves behind the verb: Heute gehe ich ins Kino.','Only ONE element may stand before the verb.','Typical order in the "rest": time – manner – place (Ich fahre morgen mit dem Bus nach Köln).'],
 examples:[{de:'Ich trinke morgens Kaffee.', en:'I drink coffee in the morning.'},{de:'Morgens trinke ich Kaffee.', en:'In the morning I drink coffee.'}],
 negativeExamples:[{wrong:'Morgens ich trinke Kaffee.', right:'Morgens trinke ich Kaffee.'}],
 mistakes:['Keeping English order after a fronted time expression.'],
 exceptions:['Yes/no questions and imperatives put the verb first (see g_questions).'],
 prereq:['g_praesens'], reviewRules:{intervalBoost:0.85, minAttempts:8}},
{id:'g_questions', level:'A1', category:'word-order', title:'Questions: W-Questions and Yes/No Questions',
 explanation:'German has exactly two question structures. With a question word the verb comes second; without one, the verb comes first. There is no equivalent of English "do" in questions.',
 pattern:'W-Wort + VERB + Subjekt …?  |  VERB + Subjekt …?',
 rules:['W-questions: Wer, Was, Wo, Wann, Warum, Wie, Woher, Wohin, Welcher, Wie viel — question word, then verb, then subject.','Yes/no questions: conjugated verb first, subject second. Kommst du mit?','Never use a helper verb: "Do you work?" = Arbeitest du?','Answer a negative yes/no question with "doch" to contradict it: Kommst du nicht? – Doch, ich komme.'],
 examples:[{de:'Wo wohnst du?', en:'Where do you live?'},{de:'Hast du Zeit?', en:'Do you have time?'},{de:'Woher kommen Sie?', en:'Where do you come from? (formal)'}],
 negativeExamples:[{wrong:'Wo du wohnst?', right:'Wo wohnst du?'},{wrong:'Tust du arbeiten?', right:'Arbeitest du?'}],
 mistakes:['Translating English "do/does" into German.','Leaving the subject before the verb in a W-question.'],
 exceptions:[], prereq:['g_wordorder_main']},
{id:'g_negation', level:'A1', category:'negation', title:'Negation: nicht and kein',
 explanation:'German has two negators. kein negates a noun that has an indefinite article or no article at all; nicht negates everything else — verbs, adjectives, adverbs, and nouns with a definite article or possessive.',
 pattern:'kein + Nomen (unbestimmt) | nicht + alles andere',
 rules:['kein takes the same endings as ein: keinen Bruder (Akk. m.), keine Zeit, kein Auto, keine Kinder (Pl.).','nicht stands at the end of the sentence when it negates the whole statement: Ich arbeite heute nicht.','nicht stands directly before the element it negates: Ich fahre nicht nach Berlin (sondern nach Köln).','nicht stands before a predicate adjective and before a separable prefix: Das ist nicht gut. Ich rufe dich nicht an.'],
 examples:[{de:'Ich habe keine Zeit.', en:'I have no time.'},{de:'Das ist nicht mein Buch.', en:'That is not my book.'},{de:'Er kommt heute nicht.', en:'He is not coming today.'}],
 negativeExamples:[{wrong:'Ich habe nicht Zeit.', right:'Ich habe keine Zeit.'},{wrong:'Das ist kein mein Buch.', right:'Das ist nicht mein Buch.'}],
 mistakes:['Using nicht with an indefinite noun where kein is required.','Placing nicht before the verb, as in English "do not".'],
 exceptions:['Fixed expressions: Ich habe nicht viel Zeit (viel is negated, not the noun).'],
 prereq:['g_wordorder_main']},
{id:'g_akkusativ', level:'A1', category:'akkusativ', title:'The Accusative Case (Akkusativ)',
 explanation:'The accusative case marks the direct object — the thing that directly receives the action. Only the masculine article actually changes: der → den, ein → einen. Feminine, neuter and plural look exactly like the nominative.',
 pattern:'Subjekt (Nom.) + Verb + Objekt (Akk.)',
 rules:['Masculine: der → den, ein → einen, mein → meinen, kein → keinen.','Feminine die/eine, neuter das/ein, plural die: unchanged.','Test question: "wen oder was?" — Ich kaufe den Apfel. Was kaufe ich? Den Apfel.','Common accusative verbs: kaufen, haben, brauchen, sehen, essen, trinken, lesen, suchen, besuchen, verstehen.','Accusative prepositions (fixed set): durch, für, gegen, ohne, um, entlang.'],
 examples:[{de:'Ich kaufe den Apfel.', en:'I am buying the apple. (der Apfel → den Apfel)'},{de:'Ich brauche eine Tasche.', en:'I need a bag. (unchanged)'},{de:'Das Geschenk ist für meinen Bruder.', en:'The present is for my brother. (für + Akk.)'}],
 negativeExamples:[{wrong:'Ich sehe der Mann.', right:'Ich sehe den Mann.'},{wrong:'für mein Vater', right:'für meinen Vater'}],
 mistakes:['Leaving der unchanged for a masculine direct object — the single most common beginner case error.','Forgetting that für, ohne, gegen, um, durch always force the accusative.'],
 exceptions:['N-declension nouns add -n: der Student → Ich sehe den Studenten.'],
 prereq:['g_gender','g_wordorder_main'], reviewRules:{intervalBoost:0.8, minAttempts:10}},
{id:'g_possessiv', level:'A1', category:'articles', title:'Possessive Articles (mein, dein, sein …)',
 explanation:'Possessive articles say who something belongs to. They take exactly the same endings as ein/kein, so once you know one pattern you know all three.',
 pattern:'mein- / dein- / sein- / ihr- / unser- / euer- / ihr- / Ihr- + Endung',
 rules:['ich → mein, du → dein, er/es → sein, sie → ihr, wir → unser, ihr → euer, sie → ihr, Sie → Ihr.','Endings follow ein: mein Vater (Nom. m.), meinen Vater (Akk. m.), meine Mutter, mein Kind, meine Eltern.','The stem agrees with the OWNER, the ending agrees with the OWNED noun: Sie liebt ihren Mann.','euer loses the second e before an ending: euer Haus → eure Wohnung.'],
 examples:[{de:'Das ist meine Schwester.', en:'That is my sister.'},{de:'Ich besuche meinen Bruder.', en:'I am visiting my brother.'},{de:'Wie ist Ihre Telefonnummer?', en:'What is your phone number? (formal)'}],
 negativeExamples:[{wrong:'Ich besuche mein Bruder.', right:'Ich besuche meinen Bruder.'}],
 mistakes:['Matching the ending to the owner instead of to the owned noun.'],
 exceptions:[], prereq:['g_akkusativ']},
{id:'g_modal', level:'A1', category:'modal-verbs', title:'Modal Verbs',
 explanation:'Modal verbs (können, müssen, wollen, dürfen, sollen, möchten) express ability, necessity, desire, permission or obligation. They are almost always used with a second verb in the infinitive, which moves to the very end of the sentence — the "Satzklammer" (sentence bracket).',
 pattern:'Subjekt + MODALVERB(Pos. 2) + … + INFINITIV(Ende)',
 rules:['ich and er/sie/es have NO ending: ich kann, er kann, ich muss, er muss.','Stem vowel changes in the singular: können → ich kann; müssen → ich muss; dürfen → ich darf; wollen → ich will.','möchten is the polite form of wollen: ich möchte, du möchtest, er möchte.','The infinitive goes to the end: Ich kann heute nicht kommen.','A modal can stand alone when the meaning is clear: Ich muss jetzt nach Hause.'],
 examples:[{de:'Ich muss heute arbeiten.', en:'I have to work today.'},{de:'Kannst du mir helfen?', en:'Can you help me?'},{de:'Wir möchten einen Kaffee bestellen.', en:'We would like to order a coffee.'}],
 negativeExamples:[{wrong:'Ich kann sprechen Deutsch.', right:'Ich kann Deutsch sprechen.'},{wrong:'Er kannt schwimmen.', right:'Er kann schwimmen.'}],
 mistakes:['Leaving the infinitive in the middle of the sentence.','Adding -t to the er-form of a modal verb.'],
 exceptions:['nicht dürfen = must not (prohibition); nicht müssen = need not.'],
 prereq:['g_wordorder_main'], reviewRules:{intervalBoost:0.85, minAttempts:8}},
{id:'g_trennbar', level:'A1', category:'verb-forms', title:'Separable Verbs (trennbare Verben)',
 explanation:'Many German verbs consist of a prefix plus a base verb. In a main clause the prefix detaches and jumps to the end of the sentence, forming the same sentence bracket as a modal verb.',
 pattern:'Subjekt + VERB(Pos. 2) + … + PRÄFIX(Ende)',
 rules:['Common separable prefixes: an-, auf-, aus-, ein-, mit-, zu-, ab-, vor-, nach-, zurück-, fern-.','The prefix is stressed: ÁNrufen. Inseparable prefixes (be-, ver-, er-, ent-, ge-, zer-) are unstressed and never separate.','With a modal verb the separable verb stays whole at the end: Ich muss früh aufstehen.','In the Perfekt, ge- goes between prefix and stem: aufgestanden, eingekauft.'],
 examples:[{de:'Ich stehe um sechs Uhr auf.', en:'I get up at six.'},{de:'Rufst du mich heute an?', en:'Will you call me today?'},{de:'Wir kaufen im Supermarkt ein.', en:'We shop at the supermarket.'}],
 negativeExamples:[{wrong:'Ich aufstehe um sechs.', right:'Ich stehe um sechs auf.'}],
 mistakes:['Leaving the verb whole in a main clause.','Separating an inseparable verb: "Ich stehe das Buch ver" instead of "Ich verstehe das Buch".'],
 exceptions:['um-, über-, unter-, durch- can be either, with a meaning difference: úmfahren (run over) vs umfáhren (drive around).'],
 prereq:['g_wordorder_main']},
{id:'g_praep_akk_zeit', level:'A1', category:'prepositions', title:'First Prepositions: Time and Place',
 explanation:'Prepositions are learned as fixed pairs with their case. At A1 you need the time prepositions and a first set of place prepositions; the case comes with the word, not with the meaning.',
 pattern:'um + Uhrzeit | am + Tag | im + Monat | nach/zu/aus + Dativ | für/ohne/um + Akkusativ',
 rules:['Clock time: um acht Uhr. Days and parts of day: am Montag, am Abend (but: in der Nacht).','Months and seasons: im Januar, im Sommer. Years need no preposition: 2019 / im Jahr 2019.','aus = origin (Ich komme aus Syrien), in = location with an article (Ich wohne in der Stadt), nach = to a city/country without article (Ich fahre nach Berlin), zu = to a person or institution (Ich gehe zum Arzt).','Always dative: aus, bei, mit, nach, seit, von, zu. Always accusative: durch, für, gegen, ohne, um.'],
 examples:[{de:'Ich komme um neun Uhr.', en:'I am coming at nine.'},{de:'Am Samstag fahre ich nach Hamburg.', en:'On Saturday I am going to Hamburg.'},{de:'Ich wohne bei meiner Familie.', en:'I live with my family.'}],
 negativeExamples:[{wrong:'Ich gehe nach dem Arzt.', right:'Ich gehe zum Arzt.'}],
 mistakes:['Using nach with people or institutions instead of zu.','Translating "in" from English without checking the case.'],
 exceptions:['nach Hause / zu Hause are fixed: motion vs location.'],
 prereq:['g_akkusativ']},
{id:'g_imperativ', level:'A1', category:'verb-forms', title:'The Imperative',
 explanation:'The imperative gives instructions and requests. German has three forms, matching du, ihr and Sie. Adding "bitte" or "mal" makes an instruction sound friendly rather than blunt.',
 pattern:'Komm! / Kommt! / Kommen Sie!',
 rules:['du-form: verb stem, no ending, no pronoun: Komm! Geh! Warte!','ihr-form: same as the normal ihr-form, without the pronoun: Kommt! Wartet!','Sie-form: infinitive + Sie: Kommen Sie! Warten Sie bitte!','Strong verbs with e → i keep the vowel change in the du-imperative: sprechen → Sprich! nehmen → Nimm! But a→ä verbs lose the umlaut: fahren → Fahr!','sein is irregular: Sei! Seid! Seien Sie!'],
 examples:[{de:'Sprich bitte langsamer!', en:'Please speak more slowly!'},{de:'Nehmen Sie Platz.', en:'Please take a seat.'},{de:'Kommt mal her!', en:'Come here, you lot!'}],
 negativeExamples:[{wrong:'Du komm hier!', right:'Komm her!'}],
 mistakes:['Keeping the pronoun in the du-imperative.'],
 exceptions:[], prereq:['g_praesens']},
{id:'g_konjunktionen_a1', level:'A1', category:'word-order', title:'Coordinating Conjunctions (und, aber, oder, denn, sondern)',
 explanation:'These five conjunctions join two main clauses WITHOUT changing the word order. They occupy "position zero" — the verb of the second clause still stands in position two.',
 pattern:'Hauptsatz , und/aber/oder/denn/sondern + Hauptsatz (Verb bleibt auf Position 2)',
 rules:['und (and), aber (but), oder (or), denn (because), sondern (but rather) do not move the verb.','denn = because, and keeps normal order — unlike weil, which sends the verb to the end.','sondern is used only after a negation: Das ist nicht Tee, sondern Kaffee.','No comma before und/oder joining two main clauses is required by the current rules, but a comma is always correct before aber, denn and sondern.'],
 examples:[{de:'Ich lerne Deutsch, denn ich arbeite in Berlin.', en:'I am learning German because I work in Berlin.'},{de:'Sie ist müde, aber sie arbeitet weiter.', en:'She is tired but keeps working.'}],
 negativeExamples:[{wrong:'Ich bleibe zu Hause, denn es regnet heute nicht gut.', right:'Ich bleibe zu Hause, denn es regnet.'},{wrong:'…, aber sie weiter arbeitet.', right:'…, aber sie arbeitet weiter.'}],
 mistakes:['Treating denn like weil and pushing the verb to the end.'],
 exceptions:[], prereq:['g_wordorder_main']},

/* ---------------- A2 ---------------- */
{id:'g_perfekt', level:'A2', category:'perfekt', title:'Talking About the Past: Perfekt',
 explanation:'In spoken German the Perfekt is the normal past tense. It is built with haben or sein in position two plus a Partizip II at the end of the sentence — the same sentence bracket you already know from modal and separable verbs.',
 pattern:'haben/sein (Pos. 2) + … + Partizip II (Ende)',
 rules:['Most verbs take haben. Verbs of motion and change of state take sein: gehen, kommen, fahren, fliegen, aufstehen, einschlafen, werden, bleiben, sein, passieren.','Weak verbs: ge- + Stamm + -t (machen → gemacht, kaufen → gekauft).','Strong verbs: ge- + (often changed) Stamm + -en (sehen → gesehen, trinken → getrunken, gehen → gegangen).','Separable verbs put ge- inside: aufstehen → aufgestanden, einkaufen → eingekauft.','Verbs with inseparable prefixes and verbs in -ieren take NO ge-: verstanden, bekommen, telefoniert, studiert.'],
 examples:[{de:'Ich habe gestern Deutsch gelernt.', en:'I studied German yesterday.'},{de:'Wir sind nach Berlin gefahren.', en:'We travelled to Berlin.'},{de:'Er hat mit seiner Mutter telefoniert.', en:'He spoke to his mother on the phone.'}],
 negativeExamples:[{wrong:'Ich habe gegangen.', right:'Ich bin gegangen.'},{wrong:'Ich habe getelefoniert.', right:'Ich habe telefoniert.'}],
 mistakes:['Using haben with motion verbs.','Adding ge- to -ieren verbs and to inseparable verbs.'],
 exceptions:['fahren takes sein for motion but haben with a direct object: Ich habe das Auto gefahren.'],
 prereq:['g_praesens','g_trennbar'], reviewRules:{intervalBoost:0.8, minAttempts:10}},
{id:'g_praeteritum_a2', level:'A2', category:'verb-forms', title:'Präteritum of sein, haben and the Modals',
 explanation:'Even in speech, a small group of verbs prefers the Präteritum over the Perfekt: sein, haben and the modal verbs. These forms are worth memorising early because you will use them constantly.',
 pattern:'war / hatte / konnte / musste / wollte / durfte / sollte',
 rules:['sein: ich war, du warst, er war, wir waren, ihr wart, sie waren.','haben: ich hatte, du hattest, er hatte, wir hatten.','Modals drop the umlaut and add -te: können → konnte, müssen → musste, dürfen → durfte, wollen → wollte, sollen → sollte, mögen → mochte.','ich and er/sie/es forms are identical: ich war / er war.','"Es gibt" becomes "es gab".'],
 examples:[{de:'Gestern war ich krank.', en:'Yesterday I was ill.'},{de:'Wir hatten keine Zeit.', en:'We had no time.'},{de:'Ich konnte nicht kommen.', en:'I could not come.'}],
 negativeExamples:[{wrong:'Ich habe krank gewesen.', right:'Ich war krank.'}],
 mistakes:['Building a Perfekt of sein/haben in speech where the Präteritum is normal.'],
 exceptions:[], prereq:['g_perfekt']},
{id:'g_dativ', level:'A2', category:'dativ', title:'The Dative Case (Dativ)',
 explanation:'The dative marks the indirect object — usually the person who receives something or benefits from an action. It is also demanded by a fixed set of prepositions and by a small group of verbs.',
 pattern:'der → dem | die → der | das → dem | die (Pl.) → den + -n',
 rules:['Masculine dem/einem, feminine der/einer, neuter dem/einem, plural den + -n on the noun (den Kindern).','Test question: "wem?" — Ich gebe dem Kind das Buch. Wem? Dem Kind.','Dative verbs: helfen, danken, gehören, gefallen, antworten, folgen, passen, schmecken, glauben (a person).','Dative prepositions (always): aus, bei, mit, nach, seit, von, zu — plus gegenüber.','With two objects the person is dative and the thing accusative: Ich gebe meinem Bruder das Buch.'],
 examples:[{de:'Ich helfe meinem Freund.', en:'I am helping my friend.'},{de:'Ich fahre mit dem Bus.', en:'I travel by bus.'},{de:'Das Kleid gefällt der Frau.', en:'The woman likes the dress.'}],
 negativeExamples:[{wrong:'Ich helfe meinen Freund.', right:'Ich helfe meinem Freund.'},{wrong:'mit den Bus', right:'mit dem Bus'}],
 mistakes:['Mixing den (Akk. m.) with dem (Dat. m.).','Applying the English object pattern to dative verbs: "Ich helfe ihn".'],
 exceptions:['Plural nouns already ending in -n or -s add nothing: mit den Autos, mit den Frauen.'],
 prereq:['g_akkusativ'], reviewRules:{intervalBoost:0.8, minAttempts:10}},
{id:'g_wechselpraep', level:'A2', category:'prepositions', title:'Two-Way Prepositions (Wechselpräpositionen)',
 explanation:'Nine prepositions take either the accusative or the dative. The choice is not arbitrary: accusative signals movement towards a destination (wohin?), dative signals a fixed location (wo?).',
 pattern:'wohin? → Akkusativ | wo? → Dativ',
 rules:['The nine: an, auf, hinter, in, neben, über, unter, vor, zwischen.','Movement to a place → accusative: Ich gehe in die Küche.','Position at a place → dative: Ich bin in der Küche.','The verb usually signals which: stellen/legen/setzen/hängen (+Akk., action) vs stehen/liegen/sitzen/hängen (+Dat., state).','Common contractions: in dem → im, in das → ins, an dem → am, an das → ans, auf das → aufs.'],
 examples:[{de:'Ich hänge das Bild an die Wand.', en:'I hang the picture on the wall. (movement → Akk.)'},{de:'Das Bild hängt an der Wand.', en:'The picture hangs on the wall. (position → Dat.)'},{de:'Wir gehen ins Kino und sind dann im Restaurant.', en:'We go to the cinema and are then at the restaurant.'}],
 negativeExamples:[{wrong:'Ich gehe in der Schule.', right:'Ich gehe in die Schule.'}],
 mistakes:['Using the dative for movement because the noun "feels" static.'],
 exceptions:['Fixed expressions keep their case regardless: Ich warte auf den Bus (auf + Akk. with warten).'],
 prereq:['g_dativ']},
{id:'g_reflexiv', level:'A2', category:'verb-forms', title:'Reflexive Verbs',
 explanation:'Reflexive verbs need a reflexive pronoun referring back to the subject. Many everyday German verbs are reflexive where their English equivalents are not, so they must be learned as a unit: sich freuen, sich interessieren, sich beeilen.',
 pattern:'Subjekt + Verb + mich/dich/sich/uns/euch/sich',
 rules:['Accusative reflexives: mich, dich, sich, uns, euch, sich.','Dative reflexives (used when there is also a direct object): mir, dir, sich, uns, euch, sich — Ich wasche mir die Hände.','Several take a fixed preposition: sich freuen auf (+Akk., future), sich freuen über (+Akk., past/present), sich interessieren für (+Akk.), sich ärgern über (+Akk.).','The reflexive pronoun normally follows the conjugated verb: Ich habe mich beeilt.'],
 examples:[{de:'Ich interessiere mich für Musik.', en:'I am interested in music.'},{de:'Beeil dich!', en:'Hurry up!'},{de:'Wir freuen uns auf das Wochenende.', en:'We are looking forward to the weekend.'}],
 negativeExamples:[{wrong:'Ich interessiere für Musik.', right:'Ich interessiere mich für Musik.'}],
 mistakes:['Dropping the reflexive pronoun because English has none.'],
 exceptions:[], prereq:['g_akkusativ','g_dativ']},
{id:'g_wordorder', level:'A2', category:'word-order', title:'Word Order: Main and Subordinate Clauses',
 explanation:'In a main clause the conjugated verb is the second element. In a subordinate clause introduced by weil, dass, wenn, ob and similar, the conjugated verb moves to the very end of the clause.',
 pattern:'…, weil/dass/wenn + Subjekt + … + VERB.',
 rules:['Main clause: element – VERB – rest.','Subordinate clause: conjunction – subject – rest – conjugated verb (last).','If the subordinate clause comes first, it fills position one, so the main verb follows immediately after the comma: Weil es regnet, bleibe ich zu Hause.','With a modal, the modal itself goes last: …, weil ich arbeiten muss.','In the Perfekt inside a subordinate clause, the auxiliary goes last: …, weil ich gearbeitet habe.'],
 examples:[{de:'Ich lerne Deutsch, weil ich in Deutschland arbeiten will.', en:'I am learning German because I want to work in Germany.'},{de:'Weil es regnet, bleibe ich zu Hause.', en:'Because it is raining, I am staying home.'},{de:'Ich weiß, dass er morgen kommt.', en:'I know that he is coming tomorrow.'}],
 negativeExamples:[{wrong:'weil ich lerne Deutsch', right:'weil ich Deutsch lerne'},{wrong:'Weil es regnet, ich bleibe zu Hause.', right:'Weil es regnet, bleibe ich zu Hause.'}],
 mistakes:['Keeping main-clause order after weil.','Forgetting that the fronted subordinate clause counts as position one.'],
 exceptions:[], prereq:['g_wordorder_main','g_konjunktionen_a1'], reviewRules:{intervalBoost:0.8, minAttempts:10}},
{id:'g_komparativ', level:'A2', category:'adjectives', title:'Comparative and Superlative',
 explanation:'German forms comparison with endings, never with "more" + adjective. Short adjectives with a, o, u usually add an umlaut as well.',
 pattern:'schnell – schneller – am schnellsten',
 rules:['Comparative: adjective + -er. Superlative: am + adjective + -sten (predicative) or der/die/das + -ste (attributive).','Umlaut in many one-syllable adjectives: alt → älter → am ältesten; groß → größer → am größten; jung → jünger.','Comparison words: so … wie (equal), als (unequal): Er ist so alt wie ich. Sie ist älter als ich.','Irregular: gut – besser – am besten; viel – mehr – am meisten; gern – lieber – am liebsten; hoch – höher; nah – näher.','Adjectives in -t, -d, -s, -ß, -z add -esten: am ältesten, am kürzesten.'],
 examples:[{de:'Der Zug ist schneller als der Bus.', en:'The train is faster than the bus.'},{de:'Ich trinke am liebsten Tee.', en:'I like drinking tea most of all.'},{de:'Berlin ist so groß wie Hamburg? Nein, größer.', en:'Is Berlin as big as Hamburg? No, bigger.'}],
 negativeExamples:[{wrong:'mehr schnell als', right:'schneller als'},{wrong:'schneller wie der Bus', right:'schneller als der Bus'}],
 mistakes:['Using "mehr" + adjective like English "more".','Using wie instead of als after a comparative.'],
 exceptions:[], prereq:['g_praesens']},
{id:'g_adjektiv_a2', level:'A2', category:'adjectives', title:'Adjective Endings (Introduction)',
 explanation:'An adjective before a noun must carry an ending. An adjective after sein, werden or bleiben carries none. At A2 you need the two most frequent patterns: after a definite article, and after an indefinite article.',
 pattern:'der gute Mann | ein guter Mann | Das Essen ist gut.',
 rules:['No ending after sein/werden/bleiben: Der Kaffee ist heiß.','After der/die/das (definite): -e in the nominative singular, -en almost everywhere else: der gute Kaffee, den guten Kaffee, mit dem guten Kaffee, die guten Ideen.','After ein/kein/mein (indefinite): the adjective supplies the missing gender signal: ein guter Kaffee (m.), eine gute Idee (f.), ein gutes Buch (n.), keine guten Ideen (Pl.).','Rule of thumb: when the article already shows gender and case, the adjective takes -e or -en; when it does not, the adjective takes the strong ending (-er, -es, -e).'],
 examples:[{de:'Ich suche eine günstige Wohnung.', en:'I am looking for an affordable flat.'},{de:'Der neue Kollege ist sehr freundlich.', en:'The new colleague is very friendly.'},{de:'Das ist ein gutes Buch.', en:'That is a good book.'}],
 negativeExamples:[{wrong:'Der Kaffee ist heiße.', right:'Der Kaffee ist heiß.'},{wrong:'ein gut Buch', right:'ein gutes Buch'}],
 mistakes:['Adding an ending to a predicate adjective.','Leaving an attributive adjective without an ending.'],
 exceptions:['hoch loses the c: ein hoher Berg. Adjectives in -el/-er drop the e: teuer → ein teures Auto; dunkel → ein dunkles Zimmer.'],
 prereq:['g_akkusativ','g_dativ']},
{id:'g_nebensatz_a2', level:'A2', category:'word-order', title:'Subordinating Conjunctions: dass, ob, wenn, als',
 explanation:'Beyond weil, four subordinators do most of the everyday work. All of them send the conjugated verb to the end.',
 pattern:'…, dass/ob/wenn/als + … + VERB.',
 rules:['dass = that (reported content): Ich glaube, dass er Recht hat.','ob = whether/if (indirect yes/no question): Ich weiß nicht, ob er kommt.','wenn = if/whenever (condition or repeated past event): Wenn ich Zeit habe, koche ich.','als = when, for a single completed event in the past: Als ich zehn war, bin ich nach Deutschland gekommen.','wenn vs als: repeated or present → wenn; one past event → als.'],
 examples:[{de:'Ich hoffe, dass du bald gesund bist.', en:'I hope you get well soon.'},{de:'Weißt du, ob der Laden heute offen ist?', en:'Do you know whether the shop is open today?'},{de:'Als ich klein war, wohnte ich in Kabul.', en:'When I was little I lived in Kabul.'}],
 negativeExamples:[{wrong:'Wenn ich klein war, wohnte ich in Kabul.', right:'Als ich klein war, wohnte ich in Kabul.'}],
 mistakes:['Using wenn for a single past event.','Using if/ob where dass is needed.'],
 exceptions:[], prereq:['g_wordorder']},
{id:'g_um_zu', level:'A2', category:'word-order', title:'Purpose: um … zu and damit',
 explanation:'To say why you do something, German uses um … zu + infinitive when both clauses share the same subject, and damit when the subjects differ.',
 pattern:'…, um + … + zu + Infinitiv | …, damit + Subjekt + … + VERB',
 rules:['Same subject → um … zu: Ich lerne Deutsch, um in Deutschland zu arbeiten.','Different subjects → damit: Ich spreche langsam, damit du mich verstehst.','With a separable verb, zu goes inside: um früh aufzustehen.','damit is a subordinator, so the verb goes to the end.'],
 examples:[{de:'Ich gehe zum Arzt, um ein Rezept zu bekommen.', en:'I am going to the doctor to get a prescription.'},{de:'Ich erkläre es noch einmal, damit alle es verstehen.', en:'I will explain it again so that everyone understands it.'}],
 negativeExamples:[{wrong:'Ich lerne Deutsch, um ich arbeiten kann.', right:'Ich lerne Deutsch, um arbeiten zu können.'}],
 mistakes:['Using um … zu when the two subjects are different.'],
 exceptions:[], prereq:['g_nebensatz_a2']},

/* ---------------- B1 ---------------- */
{id:'g_relativsatz', level:'B1', category:'word-order', title:'Relative Clauses',
 explanation:'A relative clause adds information about a noun. The relative pronoun takes its GENDER and NUMBER from the noun it refers to, but its CASE from its role inside the relative clause. The verb goes to the end.',
 pattern:'…, der/die/das/den/dem/deren … + VERB.',
 rules:['Nominative: der, die, das, die (Pl.) — the pronoun is the subject of the relative clause.','Accusative: den, die, das, die — the pronoun is the object.','Dative: dem, der, dem, denen (Pl.) — after dative verbs and prepositions.','Genitive: dessen, deren, dessen, deren — possession: der Mann, dessen Auto kaputt ist.','A preposition stands before the pronoun: die Firma, bei der ich arbeite.','The relative clause is always separated by commas and the verb is final.'],
 examples:[{de:'Das ist der Kollege, der mir geholfen hat.', en:'That is the colleague who helped me.'},{de:'Die Wohnung, die wir gemietet haben, ist klein.', en:'The flat we rented is small.'},{de:'Der Kurs, an dem ich teilnehme, dauert drei Monate.', en:'The course I am attending lasts three months.'}],
 negativeExamples:[{wrong:'Das ist der Mann, der ich gesehen habe.', right:'Das ist der Mann, den ich gesehen habe.'}],
 mistakes:['Taking the case from the main clause instead of from the role inside the relative clause.','Omitting the relative pronoun, as English often does.'],
 exceptions:[], prereq:['g_wordorder','g_dativ'], reviewRules:{intervalBoost:0.85, minAttempts:8}},
{id:'g_passiv', level:'B1', category:'passiv', title:'The Passive (Vorgangspassiv)',
 explanation:'The passive puts the action, not the actor, at the centre. It is built with werden + Partizip II and is very frequent in written, official and technical German.',
 pattern:'werden (konjugiert) + … + Partizip II',
 rules:['Präsens: Das Haus wird gebaut. Präteritum: Das Haus wurde gebaut. Perfekt: Das Haus ist gebaut worden (worden, not geworden).','The agent, if mentioned, takes von + Dativ (person) or durch + Akkusativ (means/cause).','With a modal: Das Formular muss ausgefüllt werden.','Verbs without an accusative object form an impersonal passive: Hier wird nicht geraucht.'],
 examples:[{de:'Der Antrag wird geprüft.', en:'The application is being checked.'},{de:'Die Rechnung wurde gestern bezahlt.', en:'The invoice was paid yesterday.'},{de:'Das Paket ist gestern zugestellt worden.', en:'The parcel was delivered yesterday.'}],
 negativeExamples:[{wrong:'Das Haus ist gebaut geworden.', right:'Das Haus ist gebaut worden.'}],
 mistakes:['Using geworden instead of worden in the Perfekt passive.','Confusing the state passive (Das Geschäft ist geschlossen) with the process passive (Das Geschäft wird geschlossen).'],
 exceptions:['Zustandspassiv with sein describes the resulting state, not the action.'],
 prereq:['g_perfekt']},
{id:'g_konjunktiv2', level:'B1', category:'konjunktiv', title:'Konjunktiv II: Politeness, Wishes, Hypotheticals',
 explanation:'Konjunktiv II expresses what is not (yet) real: polite requests, wishes, advice and hypothetical situations. Most verbs use würde + infinitive; a small group of very common verbs has its own form.',
 pattern:'würde + Infinitiv | hätte, wäre, könnte, müsste, sollte, dürfte, wüsste',
 rules:['Standard: ich würde gern mehr Sport machen.','Own forms for haben (hätte), sein (wäre), modals (könnte, müsste, dürfte, sollte, möchte) and wissen (wüsste) — these are preferred over würde.','Polite requests: Könnten Sie mir bitte helfen? Hätten Sie kurz Zeit?','Unreal conditions: Wenn ich mehr Zeit hätte, würde ich reisen.','Past Konjunktiv II: hätte/wäre + Partizip II: Ich hätte dir geholfen.'],
 examples:[{de:'Ich hätte gern einen Termin.', en:'I would like an appointment.'},{de:'An deiner Stelle würde ich mit dem Chef sprechen.', en:'In your position I would talk to the boss.'},{de:'Wenn ich Zeit hätte, käme ich mit.', en:'If I had time, I would come along.'}],
 negativeExamples:[{wrong:'Wenn ich Zeit hätte, würde ich hätte kommen.', right:'Wenn ich Zeit hätte, würde ich mitkommen.'}],
 mistakes:['Using würde with haben/sein/modals where the simple form is expected.'],
 exceptions:[], prereq:['g_praeteritum_a2']},
{id:'g_adjektiv_voll', level:'B1', category:'adjectives', title:'Full Adjective Declension',
 explanation:'The complete system: strong endings when no article marks the case, weak endings after a definite article, mixed endings after ein-words. Learning it as "who shows the case first" makes the table unnecessary.',
 pattern:'Signal am Artikel? → schwache Endung (-e/-en). Kein Signal? → starke Endung (-er/-es/-e/-em/-en).',
 rules:['After der/die/das/diese/jede/alle: -e in Nom. Sg. (and Akk. n./f.), otherwise -en.','After ein/kein/mein: Nom. m. -er, Nom./Akk. n. -es, Nom./Akk. f. -e, otherwise -en.','With no article at all the adjective carries the full article ending: guter Kaffee, kaltes Wasser, mit großem Interesse.','In the dative and genitive, almost everything ends in -en.'],
 examples:[{de:'Wir suchen einen zuverlässigen Mitarbeiter.', en:'We are looking for a reliable employee.'},{de:'Mit freundlichen Grüßen', en:'Kind regards (no article → strong ending)'},{de:'Das ist die beste Lösung.', en:'That is the best solution.'}],
 negativeExamples:[{wrong:'Mit freundliche Grüßen', right:'Mit freundlichen Grüßen'}],
 mistakes:['Defaulting to -e everywhere.'],
 exceptions:[], prereq:['g_adjektiv_a2']},
{id:'g_genitiv', level:'B1', category:'cases', title:'The Genitive',
 explanation:'The genitive expresses possession and follows a set of mostly formal prepositions. In speech it is often replaced by von + Dativ, but you must recognise it in writing.',
 pattern:'des/eines + Nomen(-s) | der/einer + Nomen',
 rules:['Masculine and neuter: des Mannes, des Kindes (noun adds -s or -es). Feminine and plural: der Frau, der Kinder.','Genitive prepositions: wegen, während, trotz, aufgrund, innerhalb, außerhalb, statt.','Spoken alternative: das Auto von meinem Bruder instead of das Auto meines Bruders.','Names take -s without an apostrophe: Annas Auto.'],
 examples:[{de:'Das ist das Büro des Direktors.', en:'That is the director\u2019s office.'},{de:'Während der Woche arbeite ich.', en:'During the week I work.'},{de:'Trotz des Regens sind wir gelaufen.', en:'Despite the rain we walked.'}],
 negativeExamples:[{wrong:'wegen dem Wetter (formal writing)', right:'wegen des Wetters'}],
 mistakes:['Using an English apostrophe: "Anna\u2019s Auto".'],
 exceptions:['In everyday speech wegen + Dativ is widespread and tolerated.'],
 prereq:['g_dativ']},
{id:'g_konnektoren_b1', level:'B1', category:'word-order', title:'Connectors: obwohl, trotzdem, deshalb, seitdem, falls',
 explanation:'B1 writing needs connectors that mark contrast, consequence, condition and time. They fall into three groups, and the group decides the word order.',
 pattern:'Subjunktion (Verb ans Ende) | Konjunktionaladverb (Verb auf Position 2) | Konjunktion (Position 0)',
 rules:['Subordinators (verb last): obwohl, weil, damit, falls, seitdem, während, bevor, nachdem, sobald.','Conjunctional adverbs (take position one, so the verb follows): trotzdem, deshalb, deswegen, danach, außerdem, dennoch.','Coordinators (position zero, no change): und, aber, oder, denn, sondern.','obwohl and trotzdem are a pair: Obwohl es regnet, gehe ich. / Es regnet. Trotzdem gehe ich.','nachdem requires a tense shift: Nachdem ich gegessen hatte, ging ich (Plusquamperfekt + Präteritum).'],
 examples:[{de:'Obwohl ich müde war, habe ich weitergearbeitet.', en:'Although I was tired, I kept working.'},{de:'Es war spät. Deshalb bin ich mit dem Taxi gefahren.', en:'It was late. That is why I took a taxi.'},{de:'Falls Sie Fragen haben, rufen Sie mich an.', en:'If you have questions, call me.'}],
 negativeExamples:[{wrong:'Deshalb ich bin gefahren.', right:'Deshalb bin ich gefahren.'}],
 mistakes:['Treating trotzdem/deshalb as subordinators.'],
 exceptions:[], prereq:['g_nebensatz_a2']},
{id:'g_verben_praep', level:'B1', category:'prepositions', title:'Verbs with Fixed Prepositions & Präpositionaladverbien',
 explanation:'Many German verbs demand a particular preposition and case, and the pair has to be learned as one unit. When the object is a thing rather than a person, German fuses the preposition into da(r)- and wo(r)- forms.',
 pattern:'warten auf + Akk. | sich freuen über + Akk. | denken an + Akk. | darauf / worauf',
 rules:['Frequent pairs: warten auf (Akk.), denken an (Akk.), sich interessieren für (Akk.), sich freuen auf/über (Akk.), teilnehmen an (Dat.), sprechen über (Akk.), sich kümmern um (Akk.), abhängen von (Dat.), gehören zu (Dat.).','Things: da + preposition (darauf, damit, dafür); an r is inserted before a vowel: darauf, daran, darüber.','Questions about things: wo + preposition (worauf, womit, wofür). About people: preposition + wen/wem (auf wen, mit wem).','A da-form can also point forward to a dass-clause: Ich freue mich darauf, dass du kommst.'],
 examples:[{de:'Ich warte auf den Bus. – Ich warte darauf.', en:'I am waiting for the bus. – I am waiting for it.'},{de:'Worüber sprecht ihr?', en:'What are you talking about?'},{de:'Sie nimmt an einem Kurs teil.', en:'She is taking part in a course.'}],
 negativeExamples:[{wrong:'Ich warte für den Bus.', right:'Ich warte auf den Bus.'}],
 mistakes:['Translating the English preposition directly.'],
 exceptions:[], prereq:['g_wechselpraep']},
{id:'g_indirekte_frage', level:'B1', category:'word-order', title:'Indirect Questions',
 explanation:'An indirect question is a subordinate clause: the question word (or ob) introduces it and the verb goes to the end. This is the polite way to ask for information.',
 pattern:'Können Sie mir sagen, wo/wann/ob … + VERB?',
 rules:['With a W-word: Können Sie mir sagen, wo der Bahnhof ist?','Yes/no questions use ob: Ich möchte wissen, ob der Zug pünktlich ist.','No inversion inside the indirect question — the subject comes before the verb, which stands last.'],
 examples:[{de:'Wissen Sie, wann der Termin beginnt?', en:'Do you know when the appointment starts?'},{de:'Ich frage mich, ob das richtig war.', en:'I wonder whether that was right.'}],
 negativeExamples:[{wrong:'Wissen Sie, wann beginnt der Termin?', right:'Wissen Sie, wann der Termin beginnt?'}],
 mistakes:['Keeping direct-question order inside the indirect clause.'],
 exceptions:[], prereq:['g_nebensatz_a2']},
{id:'g_n_deklination', level:'B1', category:'cases', title:'N-Declension (schwache Maskulina)',
 explanation:'A group of masculine nouns adds -n or -en in every case except the nominative singular. Most of them denote people and many end in -e, -ent, -ant, -ist, -oge.',
 pattern:'der Student – den/dem/des Studenten',
 rules:['Typical members: der Student, der Kollege, der Junge, der Name, der Mensch, der Nachbar, der Kunde, der Polizist, der Praktikant.','All cases except nominative singular take -(e)n: Ich frage den Kollegen. Ich helfe dem Kollegen.','der Name and der Gedanke additionally take -ns in the genitive: des Namens.'],
 examples:[{de:'Ich habe mit dem Kunden gesprochen.', en:'I spoke to the customer.'},{de:'Kennst du den neuen Kollegen?', en:'Do you know the new colleague?'}],
 negativeExamples:[{wrong:'Ich helfe dem Student.', right:'Ich helfe dem Studenten.'}],
 mistakes:['Treating these nouns as ordinary masculines.'],
 exceptions:['der Herr adds -n in the singular but -en in the plural: dem Herrn, den Herren.'],
 prereq:['g_dativ']},
{id:'g_infinitiv_zu', level:'B1', category:'word-order', title:'Infinitive Clauses with zu',
 explanation:'Many verbs and expressions are continued with an infinitive clause introduced by zu. The infinitive stands at the end of the clause, and no second subject is used.',
 pattern:'Es ist wichtig, … zu + Infinitiv | Ich habe vor, … zu + Infinitiv',
 rules:['Common triggers: vorhaben, versuchen, vergessen, anfangen, aufhören, sich freuen, Lust haben, Zeit haben, es ist wichtig/schwierig/möglich.','Separable verbs take zu inside: anzurufen, einzukaufen, aufzustehen.','Modal verbs, sehen, hören, lassen, gehen take a bare infinitive without zu: Ich muss gehen. Ich höre ihn kommen.','A comma before the infinitive clause is optional but usual when the clause is extended.'],
 examples:[{de:'Ich habe vor, nächstes Jahr zu studieren.', en:'I plan to study next year.'},{de:'Es ist nicht leicht, eine Wohnung zu finden.', en:'It is not easy to find a flat.'},{de:'Vergiss nicht, mich anzurufen!', en:'Do not forget to call me!'}],
 negativeExamples:[{wrong:'Ich muss zu gehen.', right:'Ich muss gehen.'}],
 mistakes:['Adding zu after a modal verb.'],
 exceptions:[], prereq:['g_um_zu']},
{id:'g_praeteritum_b1', level:'B1', category:'verb-forms', title:'Präteritum in Written Narration',
 explanation:'In written German — reports, news, stories — the Präteritum replaces the Perfekt as the normal past tense. You need to produce the frequent forms and recognise the rest.',
 pattern:'weak: Stamm + -te | strong: Vokalwechsel + Nullendung',
 rules:['Weak verbs: machen → machte, arbeiten → arbeitete. Endings: -te, -test, -te, -ten, -tet, -ten.','Strong verbs change the vowel and take no ending in ich/er: gehen → ging, kommen → kam, sehen → sah, schreiben → schrieb, finden → fand.','Mixed verbs change vowel AND add -te: bringen → brachte, denken → dachte, wissen → wusste.','Plusquamperfekt (hatte/war + Partizip II) marks an event before another past event.'],
 examples:[{de:'Er kam spät nach Hause und machte das Licht an.', en:'He came home late and turned on the light.'},{de:'Nachdem sie gegessen hatte, ging sie ins Bett.', en:'After she had eaten, she went to bed.'}],
 negativeExamples:[{wrong:'Er kamte spät.', right:'Er kam spät.'}],
 mistakes:['Applying the weak -te ending to strong verbs.'],
 exceptions:[], prereq:['g_praeteritum_a2']},
{id:'g_futur', level:'B1', category:'verb-forms', title:'Futur I and Expressing the Future',
 explanation:'German normally expresses the future with the present tense plus a time word. Futur I (werden + Infinitiv) is used for predictions, promises and assumptions rather than for ordinary scheduling.',
 pattern:'Präsens + Zeitangabe | werden + Infinitiv',
 rules:['Neutral future: Morgen fahre ich nach Köln.','Futur I for prediction or promise: Es wird morgen regnen. Ich werde dir helfen.','werden + wohl/sicher expresses assumption about the present: Er wird wohl krank sein.','Do not confuse werden (to become) with the future auxiliary: Ich werde Lehrer (I am becoming a teacher).'],
 examples:[{de:'Nächste Woche beginne ich den Kurs.', en:'Next week I start the course.'},{de:'Das wird nicht einfach sein.', en:'That will not be easy.'}],
 negativeExamples:[{wrong:'Ich werde morgen zu arbeiten.', right:'Ich werde morgen arbeiten.'}],
 mistakes:['Overusing Futur I where the present is natural.'],
 exceptions:[], prereq:['g_praesens']},

/* ---------------- B2 ---------------- */
{id:'g_passiv_erweitert', level:'B2', category:'passiv', title:'Extended Passive: Modals, Zustandspassiv, Alternatives',
 explanation:'At B2 the passive has to be produced in all tenses, with modal verbs, and replaced by its common alternatives when a lighter style is wanted.',
 pattern:'muss … werden | ist … + Partizip II | sich lassen + Infinitiv | sein + zu + Infinitiv',
 rules:['Modal passive: Der Vertrag muss bis Freitag unterschrieben werden.','Zustandspassiv (result): Der Vertrag ist unterschrieben. Vorgangspassiv (process): Der Vertrag wird unterschrieben.','Passive alternatives: Das lässt sich leicht erklären. / Das ist leicht zu erklären. / Das Problem löst sich von selbst.','man + active is the most frequent spoken alternative: Man muss das Formular ausfüllen.'],
 examples:[{de:'Die Daten müssen geprüft werden.', en:'The data must be checked.'},{de:'Der Fehler lässt sich beheben.', en:'The error can be fixed.'},{de:'Das Geschäft ist seit Montag geschlossen.', en:'The shop has been closed since Monday.'}],
 negativeExamples:[{wrong:'Der Vertrag muss unterschrieben sein werden.', right:'Der Vertrag muss unterschrieben werden.'}],
 mistakes:['Mixing Zustandspassiv and Vorgangspassiv.'],
 exceptions:[], prereq:['g_passiv']},
{id:'g_konjunktiv1', level:'B2', category:'konjunktiv', title:'Konjunktiv I: Reported Speech',
 explanation:'Konjunktiv I marks reported speech in journalism, academic writing and official reports. It signals that the writer is repeating someone else\u2019s claim without endorsing it.',
 pattern:'Er sagt, er sei / habe / komme …',
 rules:['Formed from the infinitive stem + e, est, e, en, et, en: er sei, er habe, er komme, er müsse.','sein is irregular and the most frequent: ich sei, du seist, er sei, wir seien.','When the Konjunktiv I form is identical to the indicative (e.g. sie haben), Konjunktiv II is used instead: sie hätten.','Past reported speech uses habe/sei + Partizip II: Er sagte, er sei gekommen.'],
 examples:[{de:'Der Sprecher erklärte, die Lage sei stabil.', en:'The spokesperson explained that the situation was stable.'},{de:'Sie behauptet, sie habe nichts gewusst.', en:'She claims she knew nothing.'}],
 negativeExamples:[{wrong:'Er sagte, er ist müde. (journalistischer Text)', right:'Er sagte, er sei müde.'}],
 mistakes:['Using the indicative in formal reported speech.'],
 exceptions:[], prereq:['g_konjunktiv2']},
{id:'g_partizip_attr', level:'B2', category:'syntax', title:'Participles as Attributes',
 explanation:'German can compress a whole relative clause into an adjective-like participle before the noun. This is a hallmark of written and technical German.',
 pattern:'das lesende Kind (Partizip I, aktiv) | das gelesene Buch (Partizip II, passiv/abgeschlossen)',
 rules:['Partizip I = Infinitiv + d, active and simultaneous: die steigenden Preise (= die Preise, die steigen).','Partizip II = passive or completed: die gestiegenen Preise (= die Preise, die gestiegen sind); der unterschriebene Vertrag.','Participial attributes take normal adjective endings.','Extended attributes add their own complements before the participle: die in den letzten Jahren stark gestiegenen Preise.'],
 examples:[{de:'Die wachsende Nachfrage überrascht niemanden.', en:'The growing demand surprises nobody.'},{de:'Der gestern verschickte Bericht enthält Fehler.', en:'The report sent yesterday contains errors.'}],
 negativeExamples:[{wrong:'die gestiegende Preise', right:'die gestiegenen Preise'}],
 mistakes:['Mixing Partizip I and II and losing the active/passive distinction.'],
 exceptions:[], prereq:['g_adjektiv_voll','g_relativsatz']},
{id:'g_nominalisierung', level:'B2', category:'style', title:'Nominalisation and Verbalisation',
 explanation:'Formal German prefers nouns where spoken German uses verbs. Being able to move between the two registers deliberately is a core B2/C1 skill.',
 pattern:'weil die Preise steigen → wegen des Anstiegs der Preise',
 rules:['Nominal style markers: wegen, aufgrund, trotz, bei, durch, nach, vor + noun.','Frequent conversions: weil → wegen/aufgrund; wenn → bei; obwohl → trotz; nachdem → nach; bevor → vor; damit → zu/zwecks.','Nominalised verbs are neuter: das Lesen, das Einreichen.','Overuse makes text heavy; good writing alternates the two styles.'],
 examples:[{de:'Nach der Prüfung der Unterlagen entscheiden wir.', en:'After checking the documents we will decide.'},{de:'Trotz der hohen Kosten wurde das Projekt genehmigt.', en:'Despite the high costs the project was approved.'}],
 negativeExamples:[{wrong:'Wegen es regnet, bleiben wir.', right:'Wegen des Regens bleiben wir.'}],
 mistakes:['Keeping a full clause after a nominal preposition.'],
 exceptions:[], prereq:['g_genitiv','g_konnektoren_b1']},
{id:'g_konnektoren_b2', level:'B2', category:'word-order', title:'Advanced Connectors and Two-Part Connectors',
 explanation:'Argumentative German needs precise connectors for concession, consequence, restriction and alternatives — including two-part structures that distribute over the sentence.',
 pattern:'nicht nur … sondern auch | entweder … oder | zwar … aber | je … desto',
 rules:['zwar … aber = concession: Das Angebot ist zwar teuer, aber gut.','je + Komparativ (Nebensatz, Verb am Ende), desto + Komparativ (Hauptsatz, Verb direkt danach): Je länger man wartet, desto teurer wird es.','nicht nur … sondern auch adds; weder … noch negates both.','Formal consequence markers: folglich, infolgedessen, somit, demnach. Restriction: allerdings, jedoch, zumindest, sofern.'],
 examples:[{de:'Je mehr man liest, desto schneller lernt man.', en:'The more you read, the faster you learn.'},{de:'Das Projekt ist zwar aufwendig, aber notwendig.', en:'The project is demanding but necessary.'}],
 negativeExamples:[{wrong:'Je mehr man liest, desto man lernt schneller.', right:'Je mehr man liest, desto schneller lernt man.'}],
 mistakes:['Wrong verb position in the desto clause.'],
 exceptions:[], prereq:['g_konnektoren_b1']},
{id:'g_modalverben_subjektiv', level:'B2', category:'modal-verbs', title:'Modal Verbs with Subjective Meaning',
 explanation:'Beyond ability and obligation, modal verbs express how certain the speaker is about a claim. The form is identical; only the context distinguishes the two readings.',
 pattern:'Er muss krank sein. (Vermutung) vs Er muss arbeiten. (Notwendigkeit)',
 rules:['müssen = near certainty: Er muss zu Hause sein, das Licht brennt.','dürfte = polite probability: Das dürfte stimmen.','können/könnte = possibility: Das könnte teuer werden.','wollen = claims about oneself, reported sceptically: Er will nichts gewusst haben.','sollen = second-hand report: Der Film soll gut sein.'],
 examples:[{de:'Sie dürfte schon angekommen sein.', en:'She has probably arrived by now.'},{de:'Das Restaurant soll sehr gut sein.', en:'The restaurant is said to be very good.'}],
 negativeExamples:[],
 mistakes:['Reading "Der Film soll gut sein" as an obligation.'],
 exceptions:[], prereq:['g_modal','g_konjunktiv2']},

/* ---------------- C1 ---------------- */
{id:'g_funktionsverben', level:'C1', category:'style', title:'Funktionsverbgefüge',
 explanation:'Formal and administrative German replaces a simple verb with a fixed noun+verb combination. Recognising and producing these combinations is one of the clearest markers of C1 register.',
 pattern:'in Betracht ziehen | zur Verfügung stellen | Anwendung finden',
 rules:['The noun carries the meaning; the verb is semantically light: eine Entscheidung treffen (= entscheiden).','Frequent: in Frage stellen, zur Kenntnis nehmen, in Anspruch nehmen, unter Druck setzen, Bezug nehmen auf, in Kraft treten, zum Ausdruck bringen.','The preposition and article are fixed and cannot be varied freely.','They belong to written and formal registers; in speech the simple verb is usually better.'],
 examples:[{de:'Wir nehmen Ihr Angebot zur Kenntnis.', en:'We take note of your offer.'},{de:'Die Regelung tritt am 1. Januar in Kraft.', en:'The rule comes into force on 1 January.'}],
 negativeExamples:[{wrong:'eine Entscheidung machen', right:'eine Entscheidung treffen'}],
 mistakes:['Translating English light verbs literally ("make a decision").'],
 exceptions:[], prereq:['g_nominalisierung']},
{id:'g_modalpartikeln', level:'C1', category:'style', title:'Modal Particles (doch, ja, mal, eben, wohl, halt)',
 explanation:'Modal particles carry no dictionary meaning; they carry attitude. Used correctly they make German sound natural, and misused they make a sentence sound rude or odd.',
 pattern:'Komm doch mal vorbei! | Das ist ja interessant.',
 rules:['doch = contradiction or gentle insistence: Das weißt du doch!','ja = shared knowledge or surprise: Du bist ja schon da!','mal softens an imperative: Schau mal.','eben/halt = resignation, "that\u2019s just how it is": Das ist eben so.','wohl = assumption: Er ist wohl krank.','Particles are unstressed and sit in the middle field, never at the start.'],
 examples:[{de:'Setz dich doch!', en:'Do sit down. (friendly invitation)'},{de:'Das war ja klar.', en:'That was obvious, wasn\u2019t it.'}],
 negativeExamples:[{wrong:'Doch setz dich!', right:'Setz dich doch!'}],
 mistakes:['Translating particles as full words and placing them initially.'],
 exceptions:[], prereq:['g_konnektoren_b2']},
{id:'g_erweiterte_attribute', level:'C1', category:'syntax', title:'Extended Attributes and Attribute Chains',
 explanation:'Academic and technical German packs long modifiers between the article and the noun. Reading them requires locating the article and the head noun first, then unpacking backwards.',
 pattern:'die [in der Studie von 2019 erstmals beschriebene] Methode',
 rules:['Read: article → jump to the head noun → then unpack the material in between.','Extended attributes can be rewritten as relative clauses, and should be in clearer prose: die Methode, die in der Studie erstmals beschrieben wurde.','Multiple attributes can stack: genitive attribute + participial attribute + prepositional attribute.'],
 examples:[{de:'Die im letzten Quartal deutlich gestiegenen Kosten belasten das Budget.', en:'The costs, which rose significantly last quarter, are straining the budget.'}],
 negativeExamples:[],
 mistakes:['Losing track of the head noun and mis-assigning the case.'],
 exceptions:[], prereq:['g_partizip_attr']},
{id:'g_praep_genitiv', level:'C1', category:'prepositions', title:'Genitive Prepositions in Formal Register',
 explanation:'Formal written German uses a wide set of genitive prepositions. They are a reliable register signal in reports, legal texts and academic writing.',
 pattern:'aufgrund / hinsichtlich / mittels / infolge / seitens / zwecks + Genitiv',
 rules:['Frequent: aufgrund, hinsichtlich, bezüglich, infolge, mittels, seitens, zwecks, angesichts, anhand, anstelle, ungeachtet.','They govern the genitive; using the dative marks the text as informal.','Each usually has a neutral everyday equivalent: aufgrund → wegen; hinsichtlich → in Bezug auf; mittels → mit.'],
 examples:[{de:'Angesichts der aktuellen Lage verschieben wir den Termin.', en:'In view of the current situation we are postponing the appointment.'},{de:'Anhand der Daten lässt sich das belegen.', en:'The data allow this to be demonstrated.'}],
 negativeExamples:[{wrong:'aufgrund dem Wetter', right:'aufgrund des Wetters'}],
 mistakes:['Using the dative after genitive prepositions in formal writing.'],
 exceptions:[], prereq:['g_genitiv']},

/* ---------------- C2 ---------------- */
{id:'g_stilistische_wortstellung', level:'C2', category:'style', title:'Stylistic Word Order and Emphasis',
 explanation:'At C2 word order becomes a stylistic instrument: fronting, extraposition, ellipsis and inversion place emphasis deliberately rather than merely satisfying the grammar.',
 pattern:'Vorfeldbesetzung | Ausklammerung | Ellipse',
 rules:['What stands in the Vorfeld (position one) is what the sentence is "about": Gerade diesen Punkt halte ich für entscheidend.','Ausklammerung moves heavy material behind the final verb for readability: Ich habe lange nachgedacht über diese Frage.','Ellipsis is normal in speech and journalism: Alles klar? Kein Problem.','Marked inversions and archaic orders exist in literary and legal registers and should be recognised, not imitated without reason.'],
 examples:[{de:'Nicht das Ergebnis überrascht mich, sondern der Weg dorthin.', en:'It is not the result that surprises me, but how it came about.'}],
 negativeExamples:[],
 mistakes:['Copying literary inversions into neutral prose.'],
 exceptions:[], prereq:['g_erweiterte_attribute','g_modalpartikeln']},
{id:'g_register', level:'C2', category:'style', title:'Register and Connotation',
 explanation:'C2 command means choosing between near-synonyms on the basis of register and connotation rather than meaning alone, and keeping the choice consistent across a whole text.',
 pattern:'bekommen / erhalten / kriegen — same meaning, three registers',
 rules:['Everyday: kriegen, gucken, machen. Neutral: bekommen, sehen, tun. Formal: erhalten, betrachten, durchführen.','Nominal style, genitive prepositions and Funktionsverbgefüge raise register; Modalpartikeln, ellipsis and kriegen lower it.','Register must be consistent: one colloquial verb inside an official letter is more damaging than a grammar slip.','Connotation differs even within a register: Problem / Herausforderung / Schwierigkeit are not interchangeable.'],
 examples:[{de:'Ihr Antrag ist bei uns eingegangen.', en:'Your application has reached us. (official)'},{de:'Ich hab deine Mail gekriegt.', en:'I got your mail. (colloquial)'}],
 negativeExamples:[{wrong:'Sehr geehrte Damen und Herren, ich hab Ihre Mail gekriegt.', right:'Sehr geehrte Damen und Herren, ich habe Ihre E-Mail erhalten.'}],
 mistakes:['Mixing registers within one text.'],
 exceptions:[], prereq:['g_funktionsverben']},
];

if(typeof module !== 'undefined' && module.exports){ module.exports = { GRAMMAR_DB }; }
