/* ============================================================
   CURRICULUM — A2 (spec §11)
   A2 is not "A1 but harder": it adds the past tense, the dative
   system, subordinate clauses and comparison — i.e. genuinely
   new communicative ability. The two Phase-2.5 A2 lessons
   (l09 Perfekt, l11 Dativ) keep their ids inside the new units.
   ============================================================ */
const CURRICULUM_A2 = (() => {
  const D = (typeof DSL !== 'undefined') ? DSL : require('../core/dsl.js');

return D.buildLevel('A2', [
{
  title:'Über die Vergangenheit sprechen', theme:'Talking about the past',
  goal:'Report what you did, where you were and what happened.',
  canDo:['Tell someone about my weekend','Report a past event','Use the past tense of sein, haben and modals'],
  lessons:[
  {
    id:'l09', title:'The Perfekt: Regular and Irregular Participles', topic:'perfekt',
    goal:'Talk about the past with haben/sein plus a correctly formed Partizip II.',
    why:'In spoken German the Perfekt is THE past tense. Without it you cannot answer "Was hast du am Wochenende gemacht?"',
    intro:'The Perfekt has two parts: an auxiliary (haben or sein) in position two, and a past participle at the very end.',
    vocab:['v_gestern','v_damals','v_neulich','v_arbeiten','v_lernen','v_kaufen'],
    grammar:'g_perfekt', time:22, skills:['grammar','speaking'],
    teach:[
      ['Weak (regular) participles','ge- + stem + -t: machen → gemacht, kaufen → gekauft, lernen → gelernt, arbeiten → gearbeitet (extra e after t/d).'],
      ['Strong (irregular) participles','ge- + often changed stem + -en: sehen → gesehen, trinken → getrunken, schreiben → geschrieben, gehen → gegangen, essen → gegessen. These must be learned one by one — there are roughly 180 in common use, and about 60 cover everyday speech.'],
      ['haben or sein?','sein is used with verbs of motion from A to B (gehen, fahren, fliegen, kommen), with change of state (aufstehen, einschlafen, aufwachen, werden, wachsen) and with sein, bleiben, passieren. Everything else takes haben.'],
      ['No ge- in two cases','Verbs with an inseparable prefix (verstehen → verstanden, bekommen → bekommen, erklären → erklärt) and verbs ending in -ieren (telefonieren → telefoniert, studieren → studiert) take no ge-.'],
    ],
    commonMistake:'"Ich habe gegangen." Motion verbs take sein: Ich bin gegangen. The second most common error is adding ge- to -ieren verbs: "getelefoniert".',
    prog:['Building a past-tense report: „machen“',
      ['machen','to do','The infinitive.'],
      ['gemacht','done','Weak participle: ge + mach + t.'],
      ['Ich habe das gemacht.','I did that.','Auxiliary second, participle last.'],
      ['Am Wochenende habe ich nichts Besonderes gemacht.','At the weekend I did not do anything special.','A time expression in position one pushes "ich" behind the auxiliary.'],
    ],
    guided:[
      {prompt:'Ich ___ gestern Deutsch gelernt.', answer:'habe'},
      {prompt:'Wir ___ nach Berlin gefahren.', answer:'sind'},
      {prompt:'Er hat mit seiner Mutter ___. (telefonieren)', answer:'telefoniert'},
    ],
    ex:[
      'mcq|perfekt|Complete: "Ich ___ Deutsch gelernt."|bin;habe;ist;hat|habe|lernen takes haben.',
      'mcq|perfekt|Complete: "Wir ___ nach Hause gegangen."|haben;sind;ist;seid|sind|gehen is a motion verb and takes sein.',
      'fill|perfekt|Give the Partizip II of "kaufen".|gekauft|Weak verb: ge + kauf + t.',
      'fill|perfekt|Give the Partizip II of "trinken".|getrunken|Strong verb with a vowel change: ge + trunk + en.',
      'mcq|perfekt|Which participle is correct for "telefonieren"?|getelefoniert;telefoniert;telefoniergt;getelefonier|telefoniert|Verbs in -ieren take no ge-.',
      'correct|perfekt|Correct this sentence: Ich habe nach Köln gefahren.|Ich bin nach Köln gefahren.|fahren as a motion verb takes sein.',
      'build|word-order|Put in order: "Yesterday I bought a book."|Gestern habe ich ein Buch gekauft.|Time first, auxiliary second, participle last.',
    ],
    realLife:{situation:'Monday morning at work: „Wie war dein Wochenende?“', task:'Answer with four Perfekt sentences.'},
    summary:['haben/sein + Partizip II at the end','Motion and change of state take sein','No ge- with inseparable prefixes and -ieren verbs'],
  },
  {
    title:'Präteritum of sein, haben and the Modals', topic:'perfekt',
    goal:'Use war, hatte and konnte instead of a clumsy Perfekt.',
    why:'Even in speech, these verbs prefer the Präteritum — using the Perfekt here sounds wrong to a native ear.',
    intro:'A small group of high-frequency verbs keeps the simple past in everyday speech.',
    vocab:['v_damals','v_ploetzlich','v_zuerst','v_danach'],
    grammar:'g_praeteritum_a2', time:16, skills:['grammar','writing'],
    teach:[
      ['sein and haben','war, warst, war, waren, wart, waren — hatte, hattest, hatte, hatten, hattet, hatten. Note that ich and er/sie/es are identical.'],
      ['Modals','No umlaut, plus -te: können → konnte, müssen → musste, dürfen → durfte, wollen → wollte, sollen → sollte, mögen → mochte.'],
      ['es gibt → es gab','Gestern gab es ein Problem. This form appears constantly in reports and stories.'],
    ],
    commonMistake:'"Ich habe krank gewesen." Say "Ich war krank."',
    ex:[
      'mcq|verb-forms|Complete: "Gestern ___ ich krank."|bin;war;habe;hatte|war|sein in the Präteritum: ich war.',
      'mcq|verb-forms|Complete: "Wir ___ leider keine Zeit."|haben;hatten;waren;sind|hatten|haben in the Präteritum: wir hatten.',
      'fill|verb-forms|Put into the Präteritum: "Ich kann nicht kommen."|ich konnte nicht kommen|können → konnte, without the umlaut.',
      'mcq|verb-forms|What is the Präteritum of "es gibt"?|es gabt;es gab;es hat gegeben;es war|es gab|es gab is the standard past form.',
      'correct|verb-forms|Correct this sentence: Ich habe gestern müde gewesen.|Ich war gestern müde.|sein uses the Präteritum in everyday speech.',
    ],
    realLife:{situation:'Explaining an absence to a teacher.', task:'Say you were ill, had a fever, and could not come.'},
    summary:['war / hatte / konnte are the everyday past forms','ich and er forms are identical','es gibt → es gab'],
  },
  {
    title:'Telling a Story: Time Expressions & Order', topic:'time2',
    goal:'Sequence a story with zuerst, dann, danach, später, schließlich.',
    why:'Grammatically correct sentences in the wrong order are still hard to follow. Sequencing words make a story listenable.',
    intro:'Sequencing adverbs take position one, which pushes the subject behind the verb.',
    vocab:['v_zuerst','v_danach','v_schliesslich','v_ploetzlich','v_neulich'],
    grammar:'g_wordorder_main', time:15, skills:['writing','speaking'],
    teach:[
      ['The sequence set','zuerst (first), dann (then), danach (afterwards), später (later), am Ende / schließlich (finally).'],
      ['Word order','Each of these occupies position one, so the verb follows immediately: Dann bin ich nach Hause gegangen. Writing "Dann ich bin …" is the single most common error here.'],
      ['Time anchors','gestern, vorgestern, letzte Woche, letztes Jahr, vor drei Tagen, neulich, damals.'],
    ],
    commonMistake:'"Danach ich habe gegessen." After a fronted adverb the verb must come next: Danach habe ich gegessen.',
    ex:[
      'mcq|word-order|Which sentence is correct?|Dann ich bin nach Hause gegangen.;Dann bin ich nach Hause gegangen.;Dann nach Hause bin ich gegangen.;Ich dann bin nach Hause gegangen.|Dann bin ich nach Hause gegangen.|A fronted adverb fills position one; the verb follows.',
      'fill|vocab|Which word means "finally"?|schließlich;am ende|schließlich or am Ende.',
      'build|word-order|Put in order: "Afterwards we went to the cinema."|Danach sind wir ins Kino gegangen.|Danach in position one, auxiliary second, participle last.',
      'mcq|vocab|What does "vor drei Tagen" mean?|in three days;three days ago;for three days;every three days|three days ago|vor + time expression = ago.',
      'correct|word-order|Correct this sentence: Zuerst ich habe gefrühstückt.|Zuerst habe ich gefrühstückt.|The verb must be the second element.',
    ],
    realLife:{situation:'Telling a colleague about your holiday.', task:'Tell a five-sentence story using zuerst, dann, danach and schließlich.'},
    summary:['Sequencing words take position one','The verb follows immediately','vor + time = ago'],
  },
  ]},
{
  title:'Der Dativ', theme:'The dative system',
  goal:'Use the dative with verbs, prepositions and two objects.',
  canDo:['Say who I gave something to','Use mit, bei, nach, zu correctly','Say where something is'],
  lessons:[
  {
    id:'l11', title:'The Dative Case', topic:'dativ',
    goal:'Form the dative and use it with dative verbs and prepositions.',
    why:'The dative is the case of people — who you help, who you give things to, who you travel with.',
    intro:'The dative changes all four articles, which makes it more visible than the accusative — and more useful.',
    vocab:['v_helfen','v_geben','v_bus','v_kollege','v_freund'],
    grammar:'g_dativ', time:22, skills:['grammar','speaking'],
    teach:[
      ['The forms','der → dem, die → der, das → dem, die (pl.) → den + an -n on the noun: den Kindern, den Kollegen. ein → einem/einer/einem; mein → meinem/meiner/meinem/meinen.'],
      ['Dative verbs','helfen, danken, gefallen, gehören, antworten, passen, schmecken, folgen. These take a dative object where English uses a direct object: Ich helfe dir (not "dich").'],
      ['Dative prepositions','aus, bei, mit, nach, seit, von, zu — always dative, without exception. Worth memorising as a chant.'],
      ['Two objects','Person in the dative, thing in the accusative: Ich gebe meinem Bruder das Buch. If both are pronouns, the accusative comes first: Ich gebe es ihm.'],
    ],
    commonMistake:'"Ich helfe dich." helfen always takes the dative: Ich helfe dir.',
    prog:['From noun to dative sentence: „der Kollege“',
      ['der Kollege','the colleague','Nominative — and an n-declension noun.'],
      ['dem Kollegen','to the colleague','Dative: der → dem, and the noun adds -n.'],
      ['Ich helfe dem Kollegen.','I am helping the colleague.','helfen requires the dative.'],
      ['Ich habe dem neuen Kollegen bei der Arbeit geholfen.','I helped the new colleague with the work.','Dative + adjective ending -en + bei + dative, in the Perfekt.'],
    ],
    ex:[
      'mcq|dativ|Complete: "Ich helfe ___ Mann."|der;den;dem;des|dem|helfen takes the dative; der Mann → dem Mann.',
      'mcq|dativ|Complete: "Ich fahre mit ___ Bus."|der;den;dem;des|dem|mit always takes the dative.',
      'mcq|dativ|Complete: "Ich gebe ___ Frau das Geld."|die;der;dem;den|der|Feminine die becomes der in the dative.',
      'fill|dativ|Complete: "Das Buch gehört ___ Kindern." (die Kinder)|den|Plural dative: die → den, plus -n on the noun.',
      'match|dativ|Match each dative preposition to its meaning.|mit=with;nach=to / after;seit=since;bei=at / with|aus, bei, mit, nach, seit, von, zu always take the dative.',
      'correct|dativ|Correct this sentence: Ich danke dich für die Hilfe.|Ich danke dir für die Hilfe.|danken takes a dative object.',
      'mcq|dativ|Which sentence is correct?|Ich gebe das Buch meinen Bruder.;Ich gebe meinem Bruder das Buch.;Ich gebe meinen Bruder das Buch.;Ich gebe meinem Bruder den Buch.|Ich gebe meinem Bruder das Buch.|Person dative, thing accusative.',
    ],
    realLife:{situation:'Explaining who helped you with a form.', task:'Say who helped you, what you gave them, and how you travelled there.'},
    summary:['dem / der / dem / den + -n','Dative verbs: helfen, danken, gefallen, gehören','aus, bei, mit, nach, seit, von, zu'],
  },
  {
    title:'Personal Pronouns in the Accusative and Dative', topic:'grammar',
    goal:'Replace nouns with the right pronoun in both cases.',
    why:'Repeating full nouns sounds unnatural. Pronouns are what make speech flow.',
    intro:'Each pronoun has an accusative and a dative form, and the case is decided by the verb or preposition, exactly as with nouns.',
    vocab:['v_helfen','v_geben','v_schicken'],
    grammar:'g_dativ', time:16, skills:['grammar','speaking'],
    teach:[
      ['Accusative','mich, dich, ihn, sie, es, uns, euch, sie, Sie. Ich sehe ihn. Ich frage sie.'],
      ['Dative','mir, dir, ihm, ihr, ihm, uns, euch, ihnen, Ihnen. Er hilft mir. Ich gebe ihr das Buch.'],
      ['Order of two pronouns','Accusative before dative: Ich gebe es ihm (not "ihm es"). With a noun and a pronoun, the pronoun comes first: Ich gebe ihm das Buch.'],
    ],
    commonMistake:'Using "ihn" after a dative verb: "Ich helfe ihn" instead of "Ich helfe ihm".',
    ex:[
      'mcq|dativ|Complete: "Kannst du ___ helfen?" (to me)|mich;mir;ich;mein|mir|helfen takes the dative: mir.',
      'mcq|akkusativ|Complete: "Ich sehe ___ morgen." (him)|er;ihm;ihn;ihr|ihn|sehen takes the accusative: ihn.',
      'mcq|dativ|Complete: "Das Buch gehört ___." (to her)|sie;ihr;ihnen;ihre|ihr|gehören takes the dative; sie (she) → ihr.',
      'fill|grammar|Replace the nouns: "Ich gebe meinem Bruder das Buch." → Ich gebe ___ ___.|es ihm|Accusative pronoun before dative pronoun: es ihm.',
      'correct|dativ|Correct this sentence: Ich danke Ihnen sehr, können Sie mich bitte helfen?|Ich danke Ihnen sehr, können Sie mir bitte helfen?|helfen requires the dative: mir.',
    ],
    realLife:{situation:'Asking a colleague for a small favour.', task:'Ask for help, thank them, and offer to help them in return — using pronouns, not repeated nouns.'},
    summary:['mich/dich/ihn vs mir/dir/ihm','The verb decides the case','Accusative pronoun before dative pronoun'],
  },
  {
    title:'Two-Way Prepositions: wo? and wohin?', topic:'grammar',
    goal:'Choose accusative or dative after an, auf, in, über, unter, vor, hinter, neben, zwischen.',
    why:'This is the point where German case use becomes meaningful rather than arbitrary: the case carries the meaning.',
    intro:'Nine prepositions take two cases. Movement to a destination takes the accusative; position at a place takes the dative.',
    vocab:['v_tisch','v_schrank','v_fenster','v_zimmer'],
    grammar:'g_wechselpraep', time:20, skills:['grammar','writing'], difficulty:'challenging',
    teach:[
      ['The test question','wohin? (where to) → accusative. wo? (where) → dative. Ich gehe in die Küche (wohin?). Ich bin in der Küche (wo?).'],
      ['Verb pairs','Action verbs take the accusative: stellen, legen, setzen, hängen, gehen, fahren. State verbs take the dative: stehen, liegen, sitzen, hängen, sein, bleiben.'],
      ['Contractions','in dem → im, in das → ins, an dem → am, an das → ans, auf das → aufs. These are not optional in speech; using the full form sounds stilted.'],
    ],
    commonMistake:'Choosing the case by feel rather than asking wohin/wo. "Ich gehe in der Schule" means you are walking around inside the school.',
    ex:[
      'mcq|prepositions|Complete: "Ich gehe in ___ Küche." (movement)|der;die;dem;den|die|Movement → accusative; die Küche stays die.',
      'mcq|prepositions|Complete: "Ich bin in ___ Küche." (position)|der;die;dem;den|der|Position → dative; die Küche → der Küche.',
      'mcq|prepositions|Complete: "Das Bild hängt an ___ Wand."|die;der;den;dem|der|hängen as a state verb → dative; die Wand → der Wand.',
      'fill|prepositions|Complete: "Ich lege das Buch auf ___ Tisch."|den|legen is an action verb → accusative; der Tisch → den Tisch.',
      'mcq|prepositions|What does "ins" stand for?|in dem;in das;in den;in der|in das|in + das = ins.',
      'correct|prepositions|Correct this sentence: Wir gehen heute Abend in dem Kino.|Wir gehen heute Abend ins Kino.|Movement takes the accusative, contracted to ins.',
    ],
    realLife:{situation:'Describing where furniture should go in a new flat.', task:'Give four instructions using stellen/legen plus a two-way preposition.'},
    summary:['wohin? → Akkusativ, wo? → Dativ','Action verbs vs state verbs','im, ins, am, ans are standard contractions'],
  },
  ]},
{
  title:'Meinungen und Gründe', theme:'Opinions and reasons',
  goal:'Give reasons, opinions and conditions in connected sentences.',
  canDo:['Say why I think something','Report what someone said','Talk about conditions'],
  lessons:[
  {
    title:'Subordinate Clauses with weil and dass', topic:'grammar',
    goal:'Give reasons and report content with the verb at the end.',
    why:'"Why?" is the most common follow-up question in any conversation, and answering it properly needs weil.',
    intro:'weil and dass are subordinators: they push the conjugated verb to the very end of their clause.',
    vocab:['v_grund','v_meinung','v_denken','v_glauben'],
    grammar:'g_wordorder', time:20, skills:['grammar','speaking','writing'],
    teach:[
      ['The rule','Comma, conjunction, subject, everything else, conjugated verb LAST: Ich lerne Deutsch, weil ich hier arbeite.'],
      ['With a modal or a Perfekt','The modal or auxiliary is the conjugated verb and therefore goes last: …, weil ich arbeiten muss. …, weil ich gearbeitet habe.'],
      ['Fronting the clause','Weil es regnet, bleibe ich zu Hause. The whole subordinate clause counts as position one, so the main verb comes right after the comma.'],
      ['weil vs denn','Same meaning, different structure: denn keeps normal order, weil sends the verb to the end. In speech both are used constantly.'],
    ],
    commonMistake:'"weil ich lerne Deutsch" — the verb must move: "weil ich Deutsch lerne".',
    prog:['Turning a reason into a clause',
      ['Ich arbeite hier.','I work here.','A main clause.'],
      ['weil ich hier arbeite','because I work here','The conjunction sends the verb to the end.'],
      ['Ich lerne Deutsch, weil ich hier arbeite.','I am learning German because I work here.','Main clause plus reason.'],
      ['Weil ich hier arbeite, lerne ich Deutsch.','Because I work here, I am learning German.','Fronted clause: the main verb follows the comma directly.'],
    ],
    ex:[
      'mcq|word-order|Which sentence is correct?|Ich bleibe zu Hause, weil ich bin krank.;Ich bleibe zu Hause, weil ich krank bin.;Ich bleibe zu Hause, weil bin ich krank.;Ich bleibe zu Hause, weil krank ich bin.|Ich bleibe zu Hause, weil ich krank bin.|weil sends the conjugated verb to the end.',
      'mcq|word-order|Complete: "Ich glaube, dass er morgen ___."|kommt;kommen;kommt er;er kommt|kommt|After dass the verb stands at the end.',
      'build|word-order|Put in order: "I am learning German because I want to work here."|Ich lerne Deutsch, weil ich hier arbeiten will.|The modal is the conjugated verb, so it goes last.',
      'fill|word-order|Join with weil: "Ich komme nicht." + "Ich habe keine Zeit."|ich komme nicht weil ich keine zeit habe|The conjugated verb habe moves to the end.',
      'correct|word-order|Correct this sentence: Weil es regnet, ich bleibe zu Hause.|Weil es regnet, bleibe ich zu Hause.|The fronted clause fills position one, so the verb comes next.',
      'mcq|word-order|Which sentence uses denn correctly?|Ich bleibe hier, denn es regnet.;Ich bleibe hier, denn es regnet stark heute nicht.;Ich bleibe hier, denn regnet es.;Ich bleibe hier, denn es stark regnet.|Ich bleibe hier, denn es regnet.|denn does not change the word order.',
    ],
    realLife:{situation:'Explaining to your boss why you need to leave early.', task:'Give a reason with weil and a plan with dass or a modal.'},
    summary:['weil/dass send the verb to the end','A modal or auxiliary goes last','A fronted clause fills position one'],
  },
  {
    title:'Conditions and Past Time: wenn and als', topic:'grammar',
    goal:'Distinguish wenn (repeated/conditional) from als (one past event).',
    why:'Both translate as "when", and choosing wrongly changes the meaning of your sentence.',
    intro:'German splits English "when" into two words depending on whether the event happened once in the past.',
    vocab:['v_damals','v_frueher','v_immer','v_manchmal'],
    grammar:'g_nebensatz_a2', time:16, skills:['grammar','writing'],
    teach:[
      ['als = one completed past event','Als ich nach Deutschland kam, sprach ich kein Wort Deutsch.'],
      ['wenn = repeated events or conditions','Wenn ich Zeit habe, koche ich. (whenever) — Wenn es regnet, bleiben wir zu Hause. (if)'],
      ['A memory aid','If you could replace "when" by "whenever" or "if", use wenn. If it happened exactly once and is over, use als.'],
    ],
    commonMistake:'Using wenn for a single past event: "Wenn ich zehn war…" should be "Als ich zehn war…".',
    ex:[
      'mcq|word-order|Complete: "___ ich klein war, wohnte ich in Kabul."|Wenn;Als;Wann;Ob|Als|A single completed past event takes als.',
      'mcq|word-order|Complete: "___ ich Zeit habe, gehe ich schwimmen."|Als;Wenn;Wann;Ob|Wenn|A repeated or conditional situation takes wenn.',
      'mcq|word-order|Which word introduces a question about time?|wenn;als;wann;ob|wann|wann is the question word; wenn and als are conjunctions.',
      'fill|word-order|Complete: "Ich weiß nicht, ___ er kommt." (whether)|ob|ob introduces an indirect yes/no question.',
      'correct|word-order|Correct this sentence: Wenn ich nach Deutschland kam, war alles neu.|Als ich nach Deutschland kam, war alles neu.|A single past event requires als.',
    ],
    realLife:{situation:'Telling someone about your first weeks in a new country.', task:'Use als for two past events and wenn for one habit.'},
    summary:['als = once in the past','wenn = whenever / if','wann = the question word'],
  },
  {
    title:'Comparing Things', topic:'grammar',
    goal:'Compare two things and name the best one.',
    why:'Choosing a flat, a job, a phone or a route always involves comparison.',
    intro:'German compares with endings, never with "more": schnell → schneller → am schnellsten.',
    vocab:['v_teuer','v_billig','v_gross','v_klein','v_gut','v_schlecht'],
    grammar:'g_komparativ', time:16, skills:['grammar','speaking'],
    teach:[
      ['The three steps','Positive: schnell. Comparative: schneller. Superlative: am schnellsten (after the verb) or der/die/das schnellste (before a noun).'],
      ['Umlaut in short adjectives','alt → älter → am ältesten; groß → größer → am größten; jung, kurz, lang, warm, kalt, stark behave the same.'],
      ['als and wie','als after a comparative (Er ist älter als ich), so … wie for equality (Sie ist so alt wie ich). Mixing them up is one of the most noticeable A2 errors.'],
      ['Irregulars','gut – besser – am besten; viel – mehr – am meisten; gern – lieber – am liebsten; hoch – höher; nah – näher.'],
    ],
    commonMistake:'"Er ist mehr alt als ich" or "älter wie ich". German uses -er plus als.',
    ex:[
      'mcq|adjectives|Complete: "Der Zug ist ___ als der Bus."|schnell;schneller;am schnellsten;mehr schnell|schneller|Comparative = adjective + -er.',
      'mcq|adjectives|Complete: "Sie ist so alt ___ ich."|als;wie;denn;dass|wie|so … wie expresses equality.',
      'fill|adjectives|Give the comparative and superlative of "gut".|besser am besten;besser, am besten|gut – besser – am besten is irregular.',
      'mcq|adjectives|Which sentence is correct?|Diese Wohnung ist teurer als die andere.;Diese Wohnung ist mehr teuer als die andere.;Diese Wohnung ist teurer wie die andere.;Diese Wohnung ist am teuer.|Diese Wohnung ist teurer als die andere.|-er plus als.',
      'fill|adjectives|Complete: "Ich trinke ___ Tee." (most of all)|am liebsten|gern – lieber – am liebsten.',
      'correct|adjectives|Correct this sentence: Mein Zimmer ist mehr klein wie deins.|Mein Zimmer ist kleiner als deins.|Comparative with -er and als.',
    ],
    realLife:{situation:'Choosing between two flats with a friend.', task:'Compare them on three points and say which is better and why.'},
    summary:['-er / am -sten','Short adjectives often add an umlaut','als after a comparative, so … wie for equality'],
  },
  ]},
{
  title:'Alltag bewältigen', theme:'Handling everyday life',
  goal:'Deal with problems, services and arrangements.',
  canDo:['Complain politely','Cancel and reschedule in writing','Describe a problem in a flat'],
  lessons:[
  {
    title:'Reflexive Verbs & Daily Care', topic:'feelings',
    goal:'Use reflexive verbs for routines, feelings and reactions.',
    why:'Many of the most common German verbs about yourself are reflexive, and English gives you no warning.',
    intro:'A reflexive verb needs a pronoun pointing back at the subject: Ich freue mich. Ich beeile mich.',
    vocab:['v_sich_freuen','v_sich_aergern','v_sich_fuehlen','v_sich_interessieren','v_nervoes','v_zufrieden'],
    grammar:'g_reflexiv', time:18, skills:['grammar','speaking'],
    teach:[
      ['Accusative reflexive pronouns','mich, dich, sich, uns, euch, sich. Ich wasche mich. Er beeilt sich.'],
      ['Dative reflexive','Used when there is already a direct object: Ich wasche mir die Hände. Ich putze mir die Zähne.'],
      ['Fixed prepositions','sich freuen auf (looking forward), sich freuen über (about something that happened), sich interessieren für, sich ärgern über, sich kümmern um. The preposition is part of the verb.'],
    ],
    commonMistake:'Dropping the pronoun because English has none: "Ich interessiere für Musik" instead of "Ich interessiere mich für Musik".',
    ex:[
      'mcq|verb-forms|Complete: "Ich interessiere ___ für Technik."|mir;mich;sich;mein|mich|sich interessieren takes an accusative reflexive pronoun.',
      'mcq|verb-forms|Complete: "Wir freuen ___ auf das Wochenende."|uns;sich;unser;euch|uns|wir → uns.',
      'fill|verb-forms|Complete: "Ich putze ___ die Zähne."|mir|With a direct object (die Zähne) the reflexive pronoun is dative: mir.',
      'mcq|prepositions|Complete: "Ich ärgere mich ___ den Lärm."|auf;über;für;von|über|sich ärgern über + accusative.',
      'correct|verb-forms|Correct this sentence: Er beeilt, weil der Zug gleich fährt.|Er beeilt sich, weil der Zug gleich fährt.|beeilen is only used reflexively.',
    ],
    realLife:{situation:'Describing a morning routine to a classmate.', task:'Use three reflexive verbs in sequence.'},
    summary:['mich/dich/sich after the verb','Dative reflexive when a direct object is present','The preposition belongs to the verb'],
  },
  {
    title:'Writing Messages: Invitations, Cancellations, Complaints', topic:'services',
    goal:'Write a short, correctly structured German message for three common purposes.',
    why:'At A2 most written German you produce will be a message with a purpose: inviting, cancelling or complaining.',
    intro:'German messages have a fixed skeleton: greeting, reason, request, closing. Filling the skeleton matters more than length.',
    vocab:['v_nachricht','v_absagen','v_verschieben','v_rechnung','v_formular','v_ausfuellen'],
    grammar:'g_wordorder', time:20, skills:['writing'], difficulty:'challenging',
    teach:[
      ['Greetings and closings','Informal: Hallo Anna, … Liebe Grüße / Viele Grüße. Formal: Sehr geehrte Frau Weber, … Mit freundlichen Grüßen. Note the comma after the greeting and the lower-case start of the first line.'],
      ['The three-part body','1) Why you are writing (Ich schreibe Ihnen, weil …). 2) The detail (Der Termin am Montag passt mir leider nicht). 3) The request (Könnten wir den Termin verschieben?).'],
      ['Politeness markers','leider, könnten Sie, wäre es möglich, ich würde gern. These turn a blunt statement into an acceptable German request.'],
    ],
    commonMistake:'Starting the first sentence with a capital letter after the comma in the greeting. German continues in lower case: "Hallo Anna, ich schreibe dir …"',
    ex:[
      'mcq|writing|Which closing belongs in a formal email?|Liebe Grüße;Tschüss;Mit freundlichen Grüßen;Bis bald|Mit freundlichen Grüßen|The standard formal closing, no comma after it.',
      'mcq|writing|Which greeting is correct for a woman whose name you know, in a formal letter?|Liebe Frau Weber,;Sehr geehrte Frau Weber,;Hallo Weber,;Sehr geehrter Frau Weber,|Sehr geehrte Frau Weber,|geehrte agrees with the feminine form.',
      'fill|writing|Write a polite request to postpone an appointment.|könnten wir den termin verschieben;könnten wir den termin bitte verschieben|Könnten Sie / Könnten wir is the standard polite request form.',
      'mcq|writing|What comes immediately after "Sehr geehrte Frau Weber,"?|A capital letter;A lower-case letter;A blank line and then a capital;A colon|A lower-case letter|German continues the sentence in lower case after the greeting comma.',
      'build|word-order|Put in order: "Unfortunately I cannot come on Monday."|Am Montag kann ich leider nicht kommen.|Time first, modal second, infinitive last.',
    ],
    realLife:{situation:'You have to cancel a viewing appointment for a flat.', task:'Write a five-line message: greeting, reason, apology, new suggestion, closing.'},
    summary:['Greeting, reason, request, closing','Lower case after the greeting comma','leider / könnten Sie carry the politeness'],
  },
  {
    title:'Problems, Complaints & Solutions', topic:'services',
    goal:'Describe something that does not work and ask for it to be fixed.',
    why:'Heating, internet, deliveries, bills — complaining clearly and politely is a survival skill in Germany.',
    intro:'A German complaint states the fact, the consequence and the request — in that order, and without anger.',
    vocab:['v_problem','v_loesung','v_funktionieren','v_reparieren','v_sich_beschweren','v_rechnung','v_heizung'],
    grammar:'g_wordorder', time:18, skills:['speaking','writing','conversation'],
    teach:[
      ['Stating the problem','Die Heizung funktioniert nicht. Das Gerät ist kaputt. Die Lieferung ist nicht angekommen. Die Rechnung stimmt nicht.'],
      ['Adding the consequence','Deshalb ist es sehr kalt in der Wohnung. / Ich kann nicht arbeiten.'],
      ['Making the request','Könnten Sie das bitte reparieren lassen? Ich bitte Sie um eine Lösung bis Freitag. Was können Sie tun?'],
    ],
    commonMistake:'Making the complaint personal ("Sie haben schlecht gearbeitet") instead of factual. German complaints stay on the object and the deadline.',
    ex:[
      'mcq|vocab|How do you say "The heating is not working"?|Die Heizung ist nicht arbeiten.;Die Heizung funktioniert nicht.;Die Heizung geht nicht funktionieren.;Die Heizung hat kein Funktion.|Die Heizung funktioniert nicht.|funktionieren is the standard verb for devices.',
      'fill|writing|Ask politely for a repair.|könnten sie das bitte reparieren lassen;können sie das bitte reparieren|reparieren lassen = to have it repaired by someone.',
      'mcq|word-order|Which sentence is correct?|Deshalb ich kann nicht arbeiten.;Deshalb kann ich nicht arbeiten.;Ich deshalb kann nicht arbeiten.;Deshalb nicht arbeiten kann ich.|Deshalb kann ich nicht arbeiten.|deshalb occupies position one, so the verb follows.',
      'match|vocab|Match each problem to its natural verb.|die Heizung=funktioniert nicht;die Rechnung=stimmt nicht;die Lieferung=ist nicht angekommen;das Gerät=ist kaputt|German pairs each type of problem with a fixed verb.',
      'fill|writing|Set a deadline politely: "by Friday".|bis freitag|bis + day is the standard deadline phrase.',
    ],
    realLife:{situation:'Your internet has not worked for four days.', task:'Phone the provider: state the problem, the duration, the consequence and your request.'},
    summary:['Fact, consequence, request','funktioniert nicht / stimmt nicht / ist kaputt','Set a clear deadline'],
  },
  ]},
{
  title:'Adjektive und Beschreibungen', theme:'Describing precisely',
  goal:'Use adjective endings before nouns.',
  canDo:['Describe things precisely','Write a flat or job advert','Understand adverts'],
  lessons:[
  {
    title:'Adjective Endings After der and ein', topic:'grammar',
    goal:'Add the right ending to an adjective standing before a noun.',
    why:'Adverts, descriptions and any precise statement need adjective endings — it is the last big A2 hurdle.',
    intro:'An adjective before a noun must carry an ending. Which ending depends on whether the article already shows the gender and case.',
    vocab:['v_gemuetlich','v_hell','v_guenstig','v_zuverlaessig','v_neu'],
    grammar:'g_adjektiv_a2', time:22, skills:['grammar','writing'], difficulty:'challenging',
    teach:[
      ['No ending after sein','Die Wohnung ist schön. Nothing changes here — this is the position you already know.'],
      ['After a definite article','der/die/das already signal everything, so the adjective takes the weak ending -e in the nominative singular and -en almost everywhere else: der neue Kollege, den neuen Kollegen, mit dem neuen Kollegen, die neuen Kollegen.'],
      ['After ein/kein/mein','ein does not show the gender, so the adjective does it instead: ein neuer Kollege (m.), eine neue Kollegin (f.), ein neues Buch (n.), keine neuen Bücher (pl.).'],
      ['The shortcut','Ask: does the article already show gender and case? If yes → -e or -en. If no → the adjective takes the ending the article would have had (-er, -es, -e).'],
    ],
    commonMistake:'"ein gut Buch" or "der neue Kollegen". The article and the ending must work together, not be chosen separately.',
    ex:[
      'mcq|adjectives|Complete: "Das ist ein ___ Kollege."|neu;neuer;neue;neuen|neuer|ein does not show masculine, so the adjective takes -er.',
      'mcq|adjectives|Complete: "Ich suche eine ___ Wohnung."|günstig;günstige;günstiger;günstigen|günstige|Feminine accusative after eine takes -e.',
      'mcq|adjectives|Complete: "Der ___ Kollege heißt Ahmed."|neu;neue;neuer;neuen|neue|After der in the nominative singular the ending is -e.',
      'fill|adjectives|Complete: "Das ist ein ___ Buch." (gut)|gutes|Neuter after ein takes -es.',
      'mcq|adjectives|Which sentence is correct?|Die Wohnung ist kleine.;Die Wohnung ist klein.;Die kleine Wohnung ist klein e.;Die Wohnung klein ist.|Die Wohnung ist klein.|After sein there is no ending.',
      'correct|adjectives|Correct this sentence: Ich habe ein neu Auto gekauft.|Ich habe ein neues Auto gekauft.|das Auto is neuter, so after ein the adjective takes -es.',
    ],
    realLife:{situation:'Writing a short advert to sell something.', task:'Describe the item in three sentences using at least three adjective+noun pairs.'},
    summary:['No ending after sein','After der: -e or -en','After ein: the adjective shows the gender'],
  },
  {
    title:'A2 Review & Readiness Check', topic:'grammar',
    goal:'Verify that Perfekt, dative, subordinate clauses and comparison are secure.',
    why:'B1 assumes all four are automatic. This check tells you honestly whether they are.',
    intro:'A mixed review of everything A2 introduced.',
    vocab:[], grammar:'g_wordorder', time:20, skills:['grammar','vocabulary'], difficulty:'challenging',
    teach:[
      ['What A2 really means','You can handle routine situations, talk about the past, give reasons, and describe problems — with simple but connected language.'],
      ['The four A2 load-bearing structures','Perfekt with the right auxiliary; the dative after verbs and prepositions; verb-final order after weil/dass/wenn; comparison with -er … als.'],
    ],
    commonMistake:'Moving on while the dative is still guesswork. B1 relative clauses depend entirely on secure case knowledge.',
    ex:[
      'mcq|perfekt|Complete: "Ich ___ gestern ins Kino gegangen."|habe;bin;war;hatte|bin|gehen takes sein.',
      'mcq|dativ|Complete: "Ich habe ___ Kollegen geholfen."|den;dem;der;des|dem|helfen takes the dative.',
      'mcq|word-order|Complete: "Ich komme nicht, weil ich arbeiten ___."|muss;müssen;musst;gemusst|muss|The modal is the conjugated verb, so it stands last.',
      'mcq|adjectives|Complete: "Diese Wohnung ist ___ als die andere."|günstig;günstiger;am günstigsten;mehr günstig|günstiger|Comparative + als.',
      'mcq|prepositions|Complete: "Stell die Flasche bitte auf ___ Tisch."|dem;den;der;das|den|Movement → accusative.',
      'fill|dativ|Complete: "Wir fahren mit ___ Auto." (das Auto)|dem|mit always takes the dative.',
      'correct|word-order|Correct this sentence: Ich glaube, dass er kommt morgen.|Ich glaube, dass er morgen kommt.|After dass the verb stands at the very end.',
      'fill|perfekt|Put into the Perfekt: "Ich verstehe das nicht."|ich habe das nicht verstanden|verstehen has an inseparable prefix, so there is no ge-.',
    ],
    realLife:{situation:'An A2 exam speaking task.', task:'Describe a past experience, give a reason, and compare two options.'},
    summary:['Perfekt auxiliary must be right','Dative after verbs and fixed prepositions','Verb last after weil/dass/wenn','Comparative with -er … als'],
  },
  ]},
]);
})();

if(typeof module !== 'undefined' && module.exports){ module.exports = { CURRICULUM_A2 }; }
