/* ============================================================
   CURRICULUM — A0 (Foundation) and A1 (spec §9, §10)

   Units are the pedagogical unit of planning; lessons inside a
   unit are in teaching order and are chained as prerequisites
   automatically by DSL.buildLevel(). Every lesson follows the
   teaching cycle INTRODUCE → EXPLAIN → DEMONSTRATE → BREAK DOWN
   → GUIDE → PRACTISE → CORRECT → APPLY → ASSESS → REVIEW:
     intro/goal/why        → introduce & motivate
     teach                 → explain
     sentenceProgression   → demonstrate & break down (word → real use)
     guided                → guided practice with the answer visible
     exercises             → independent practice + correction
     realLife              → apply
     summary               → review

   The eleven Phase-2.5 lesson ids (l01–l11) are reused for the
   lessons that carry the same material, so existing learner
   progress continues to resolve after this expansion.
   ============================================================ */
const CURRICULUM_A0A1 = (() => {
  const D = (typeof DSL !== 'undefined') ? DSL : require('../core/dsl.js');

/* ================================================================
   A0 — FOUNDATION
   ================================================================ */
const A0 = D.buildLevel('A0', [
{
  title:'Schrift und Laute', theme:'The writing and sound system',
  goal:'Read any German word aloud correctly and write it with the right umlauts.',
  canDo:['Read German letters aloud','Spell my name in German','Recognise umlauts and ß'],
  lessons:[
  {
    id:'l01', title:'The Alphabet & the Sounds That Differ', topic:'pronunciation',
    goal:'Recognise and pronounce the German sounds that differ most from English.',
    why:'German spelling is regular. Getting the sound rules right now means every word you meet later is already readable.',
    intro:'German has 26 letters plus ä, ö, ü and ß. Only a handful of them sound different from English — and those few explain almost every pronunciation mistake beginners make.',
    vocab:['v_buchstabe','v_wort','v_umlaut','v_buchstabieren','v_schreiben','v_lesen'],
    grammar:'g_alphabet', time:15, skills:['pronunciation','vocabulary'],
    teach:[
      ['The umlauts: ä, ö, ü','ä sounds like the "e" in "bed" (Mädchen). For ö, say "e" and round your lips (können). For ü, say "ee" and round your lips (für). They are separate letters, not decorated vowels — changing them changes the word: schon (already) vs schön (beautiful).'],
      ['ei versus ie','ei is pronounced like English "eye": mein, Wein, heißen. ie is pronounced like English "ee": Bier, Sie, wie. Read the SECOND letter of the pair to get the sound right.'],
      ['ch, sch, sp, st','sch = English "sh" (Schule). At the start of a word, sp = "shp" (sprechen) and st = "sht" (Stadt). ch after a, o, u is a rough back-of-throat sound (Buch); after e, i and the umlauts it is soft, like a whispered "h" in "huge" (ich).'],
      ['ß and double consonants','ß is always a sharp, voiceless "ss" and never begins a word. It follows long vowels and diphthongs (heißen, Straße); after a short vowel you write ss instead (Fluss, muss).'],
    ],
    commonMistake:'Reading "ei" as "ee" and "ie" as "eye" — exactly the reverse of what English spelling suggests. Almost every learner does this for the first few weeks.',
    prog:['From sound to real exchange: „heißen“',
      ['heißen','to be called','Two sound rules in one word: ei = "eye", ß = sharp s.'],
      ['Wie heißt du?','What is your name?','A whole question. Say it "vee HYST doo".'],
      ['Ich heiße Sara.','My name is Sara.','The answer pattern: "ish HY-suh".'],
      ['Ich heiße Sara. Und wie heißt du?','My name is Sara. And what is your name?','Handing the question back is how a real conversation starts.'],
    ],
    guided:[
      {prompt:'Read aloud: Bier', answer:'"beer" — ie = ee'},
      {prompt:'Read aloud: mein', answer:'"mine" — ei = eye'},
      {prompt:'Read aloud: Stadt', answer:'"shtat" — st at the start = sht'},
    ],
    ex:[
      'mcq|pronunciation|Which word contains the "eye" sound (as in English "my")?|Bier;mein;Sie;wie|mein|ei is pronounced like English "eye". ie (Bier, Sie, wie) is pronounced like English "ee".',
      'mcq|pronunciation|Which letter combination makes the "sh" sound in "Schule"?|sp;ch;sch;st|sch|sch is always pronounced like English "sh".',
      'mcq|pronunciation|How does "Stadt" begin?|"stat";"shtat";"sdatt";"ztat"|"shtat"|At the start of a word or syllable, st is pronounced "sht".',
      'mcq|pronunciation|Which word has the hard, back-of-throat ch?|ich;Buch;München;Mädchen|Buch|After a, o, u the ch is hard. After e, i, ä, ö, ü it is soft.',
      'fill|spelling|Write the German word for "street" (with ß).|straße;strasse|Straße has a long a, so it takes ß. Writing "Strasse" is accepted in Switzerland but ß is standard in Germany and Austria.',
    ],
    realLife:{situation:'Someone at a Bürgeramt asks you to spell your surname.', task:'Say each letter of your name using German letter names.'},
    summary:['ei = "eye", ie = "ee"','sch = sh; word-initial sp/st = shp/sht','ch is hard after a/o/u, soft elsewhere','ß = sharp s, never at the start of a word'],
  },
  {
    id:'l_a0_spelling', title:'Spelling Your Name & Numbers 0–20', topic:'alphabet',
    goal:'Spell your name aloud and understand numbers up to twenty.',
    why:'At every office, doctor and phone call in Germany you will be asked to spell your name and hear numbers.',
    intro:'The German letter names are not the English ones. E is "ay", I is "ee", J is "yot", V is "fau", W is "vay", Y is "üpsilon", Z is "tset".',
    vocab:['v_buchstabieren','v_nummer','v_zahl','v_wie_bitte','v_konnen_sie_das_wiederholen'],
    grammar:'g_alphabet', time:12, skills:['pronunciation','listening'],
    teach:[
      ['Dangerous letter pairs','E ("ay") and I ("ee") are the pair learners confuse most, because English reverses them. A is "ah", J is "yot" not "jay", V is "fau", W is "vay", Z is "tset".'],
      ['Numbers 0–20','null, eins, zwei, drei, vier, fünf, sechs, sieben, acht, neun, zehn, elf, zwölf, dreizehn, vierzehn, fünfzehn, sechzehn (no -s!), siebzehn (no -en!), achtzehn, neunzehn, zwanzig.'],
      ['Asking for a repeat','"Wie bitte?" (Pardon?), "Können Sie das bitte wiederholen?" (Can you repeat that?), "Langsamer, bitte." (Slower, please.) These three phrases will save you constantly.'],
    ],
    commonMistake:'Saying the English letter names for E, I, J, V, W and Z when spelling — the listener will write something completely different.',
    ex:[
      'mcq|pronunciation|How is the letter "W" pronounced in German?|"double-u";"vay";"way";"vee"|"vay"|German W sounds like an English V; the German V sounds like an English F.',
      'mcq|pronunciation|How is the letter "E" pronounced in German?|"ee";"ay";"eh";"ay-ee"|"ay"|German E = "ay"; German I = "ee". This is the reverse of English.',
      'mcq|vocab|Which number is "sechzehn"?|6;16;60;66|16|sechzehn is 16. Note the shortened form: sech- not sechs-.',
      'fill|vocab|Write the German word for the number 12.|zwölf|zwölf — with ö, not "zwolf".',
      'fill|vocab|How do you politely ask someone to repeat something? (three words, with a question mark not required)|können sie das wiederholen;wie bitte|Both work: "Wie bitte?" is short, "Können Sie das wiederholen?" is more explicit.',
    ],
    realLife:{situation:'A receptionist asks: „Wie schreibt man das?“', task:'Spell your surname letter by letter in German.'},
    summary:['German letter names differ from English for E, I, J, V, W, Y, Z','sechzehn and siebzehn are shortened','"Wie bitte?" is the most useful phrase you know'],
  },
  ]},
{
  title:'Erste Wörter', theme:'First survival words',
  goal:'Greet, thank, apologise and manage a first classroom or shop exchange.',
  canDo:['Greet formally and informally','Say please and thank you','Say I do not understand'],
  lessons:[
  {
    title:'Greetings & Politeness', topic:'greetings',
    goal:'Greet and take leave at the right time of day and in the right register.',
    why:'The first three seconds of every German interaction are a greeting; getting the register right sets the tone for everything after.',
    intro:'German greetings depend on the time of day and on how well you know the person.',
    vocab:['v_wie_bitte','v_ich_verstehe_nicht','v_sprechen_sie_bitte_langsamer','v_frage','v_antwort'],
    grammar:'g_capitalisation', time:12, skills:['vocabulary','conversation'],
    teach:[
      ['Time of day','Guten Morgen (until about 11), Guten Tag (until early evening), Guten Abend (evening), Gute Nacht (only when going to bed — not a greeting).'],
      ['Formal and informal','Hallo and Tschüss are informal and very common. Guten Tag and Auf Wiedersehen are neutral to formal. In the south you will hear Grüß Gott, in Switzerland Grüezi.'],
      ['Politeness words','bitte (please / you are welcome / here you are), danke (thank you), Entschuldigung (excuse me / sorry). "Danke schön" and "Bitte schön" are the fuller forms.'],
    ],
    commonMistake:'Using "Gute Nacht" as an evening greeting. It means "good night" in the going-to-bed sense only; the evening greeting is "Guten Abend".',
    ex:[
      'mcq|greetings|It is 9 a.m. and you enter a bakery. What do you say?|Guten Abend;Guten Morgen;Gute Nacht;Auf Wiedersehen|Guten Morgen|Guten Morgen is used until about 11 a.m.',
      'mcq|greetings|Which greeting is informal?|Guten Tag;Hallo;Auf Wiedersehen;Guten Abend|Hallo|Hallo (and Tschüss for goodbye) are informal.',
      'mcq|greetings|What does "bitte" mean when you hand someone something?|Thank you;Here you are;Sorry;Goodbye|Here you are|bitte covers please, you are welcome, and here you are.',
      'fill|greetings|Translate: "Thank you very much!"|danke schön;vielen dank;danke sehr|Danke schön and Vielen Dank are both natural.',
      'match|greetings|Match each expression with its use.|Guten Morgen=before 11 a.m.;Guten Abend=evening greeting;Gute Nacht=going to bed;Tschüss=informal goodbye|Time of day decides which greeting is correct.',
    ],
    realLife:{situation:'You enter a small shop at 6 p.m.', task:'Greet the shopkeeper appropriately and say goodbye when you leave.'},
    summary:['Morgen / Tag / Abend depend on the clock','Hallo and Tschüss are informal','Gute Nacht is not an evening greeting'],
  },
  {
    title:'Nouns Are Capitalised — and Carry an Article', topic:'articles',
    goal:'Recognise that every German noun is capitalised and belongs to der, die or das.',
    why:'Learning a noun without its article means relearning it later; starting right saves months.',
    intro:'Two facts about German nouns are visible on the page: they are capitalised, and they come with an article.',
    vocab:['v_tisch','v_buch','v_frage','v_antwort','v_farbe'],
    grammar:'g_capitalisation', time:12, skills:['grammar','vocabulary'],
    teach:[
      ['Capital letters are a rule, not a style','Every noun is capitalised anywhere in the sentence: Der Mann kauft ein Buch. This is also a reading aid — a capital letter mid-sentence signals a noun.'],
      ['Three genders, no logic','der (masculine), die (feminine), das (neuter). The gender is a property of the word, not of the thing: das Mädchen (the girl) is neuter because words ending in -chen always are.'],
      ['Learn the article with the word','Never write "Tisch = table" in your notes. Write "der Tisch = table, die Tische". The article and the plural are part of the word.'],
    ],
    commonMistake:'Noting new nouns without their article. Every later case ending depends on the gender you did not learn.',
    ex:[
      'mcq|articles|Which sentence is written correctly?|Der mann kauft ein buch.;Der Mann kauft ein Buch.;der Mann kauft ein Buch.;Der Mann Kauft ein Buch.|Der Mann kauft ein Buch.|Nouns are capitalised; verbs are not.',
      'art|articles|Tisch|der|der Tisch, die Tische.',
      'art|articles|Buch|das|das Buch, die Bücher.',
      'art|articles|Frage|die|die Frage, die Fragen. Nouns ending in -e are very often feminine.',
      'mcq|articles|Why is "das Mädchen" neuter?|Because girls are neutral;Because it ends in -chen;Because it is a loanword;It is an error|Because it ends in -chen|All -chen and -lein diminutives are neuter, regardless of meaning.',
    ],
    realLife:{situation:'You start a vocabulary notebook.', task:'Write five nouns you already know with article and plural.'},
    summary:['All nouns are capitalised','der / die / das is part of the word','-chen and -lein are always das'],
  },
  {
    title:'Pronouns, sein and Word Order Awareness', topic:'basics',
    goal:'Build your first complete German sentences with ich/du/er and the verb sein.',
    why:'"Ich bin …" and "Das ist …" are the frames you will use in every conversation for the next months.',
    vocab:['v_sein','v_frage','v_antwort','v_richtig','v_falsch'],
    grammar:'g_sein_haben', time:15, skills:['grammar','speaking'],
    intro:'German has six subject pronouns and three ways to say "you". The verb sein is irregular and must simply be memorised.',
    teach:[
      ['The pronouns','ich (I), du (you, one person, informal), er/sie/es (he/she/it), wir (we), ihr (you, several, informal), sie (they), Sie (you, formal, always capitalised).'],
      ['sein — the most important verb','ich bin, du bist, er/sie/es ist, wir sind, ihr seid, sie/Sie sind. There is no pattern to derive; learn it as a chant.'],
      ['Verb in position two','In a German statement the conjugated verb is the second element. Ich bin müde. Heute bin ich müde. Whatever comes first, the verb follows immediately.'],
    ],
    commonMistake:'Keeping English order after a time word: "Heute ich bin müde" instead of "Heute bin ich müde".',
    prog:['From pronoun to statement: „sein“',
      ['ich','I','A pronoun alone is not yet a sentence.'],
      ['ich bin','I am','Adding the conjugated verb creates the frame.'],
      ['Ich bin müde.','I am tired.','A complete sentence: subject, verb, adjective.'],
      ['Heute bin ich sehr müde.','Today I am very tired.','Fronting "heute" pushes "ich" behind the verb — the verb stays in position two.'],
    ],
    ex:[
      'mcq|verb-conjugation|Complete: "Du ___ sehr freundlich."|bin;bist;ist;sind|bist|du bist.',
      'mcq|verb-conjugation|Complete: "Wir ___ aus Kabul."|sind;seid;bin;ist|sind|wir sind.',
      'mcq|word-order|Which sentence is correct?|Heute ich bin müde.;Heute bin ich müde.;Ich heute bin müde.;Bin heute ich müde.|Heute bin ich müde.|The conjugated verb must be the second element.',
      'build|word-order|Put the words in order: "Today I am tired."|Heute bin ich müde.|Position 1 = Heute, position 2 = the verb, then the subject.',
      'fill|verb-conjugation|Complete: "Er ___ Lehrer." (sein)|ist|er ist.',
    ],
    realLife:{situation:'A neighbour asks who you are.', task:'Say three sentences: your name, where you are from, and that you are learning German.'},
    summary:['Six pronouns, three ways to say "you"','sein: bin, bist, ist, sind, seid, sind','The verb is always the second element of a statement'],
  },
  ]},
]);

/* ================================================================
   A1
   ================================================================ */
const A1 = D.buildLevel('A1', [
{
  title:'Sich vorstellen', theme:'Introducing yourself',
  goal:'Give and ask for personal information in both registers.',
  canDo:['Introduce myself','Ask someone their name, origin and residence','Fill in a simple form'],
  lessons:[
  {
    id:'l02', title:'Greetings & Introductions', topic:'greetings',
    goal:'Introduce yourself and greet people appropriately in formal and informal situations.',
    why:'Greeting and self-introduction are usually the very first real conversation you will have in German.',
    intro:'Three verbs carry a whole self-introduction: heißen (to be called), kommen (to come from) and wohnen (to live).',
    vocab:['v_heissen','v_wohnen','v_kommen','v_vorname','v_nachname','v_land','v_stadt','v_sprache'],
    grammar:'g_praesens', time:18, skills:['grammar','vocabulary','speaking'],
    teach:[
      ['The three frames','Ich heiße … (name). Ich komme aus … (country/city of origin). Ich wohne in … (where you live now). Together they answer the three questions you will be asked most often.'],
      ['Regular present-tense endings','ich -e, du -st, er/sie/es -t, wir -en, ihr -t, sie/Sie -en. heißen is slightly irregular in the du-form because the stem already ends in ß: du heißt.'],
      ['du or Sie?','du with friends, family, children, fellow students. Sie with strangers, officials, in shops, at work — until you are invited to switch. Getting this wrong is a social error, not a grammar error, and it is noticed.'],
    ],
    commonMistake:'Using "du" with a stranger or an official. When in doubt use Sie; a German speaker will offer "du" if they want it.',
    prog:['From word to real sentence: „kommen“',
      ['kommen','to come','The infinitive — the dictionary form.'],
      ['Ich komme.','I come. / I am coming.','Drop -en, add -e. Already a complete sentence.'],
      ['Ich komme aus Pakistan.','I come from Pakistan.','aus + country states origin.'],
      ['Ich komme aus Pakistan und wohne jetzt in Berlin.','I come from Pakistan and live in Berlin now.','und joins two facts; "wohne" shares the subject "ich".'],
    ],
    guided:[
      {prompt:'Ich ___ (heißen) Amina.', answer:'heiße'},
      {prompt:'Woher ___ (kommen) Sie?', answer:'kommen'},
      {prompt:'Wo ___ (wohnen) du?', answer:'wohnst'},
    ],
    ex:[
      'mcq|verb-conjugation|Complete: "Ich ___ Sara." (heißen)|heißt;heiße;heißen;heißest|heiße|With ich, regular verbs take -e: ich heiße.',
      'mcq|verb-conjugation|Complete: "Woher ___ du?" (kommen)|kommst;komme;kommt;kommen|kommst|With du, regular verbs take -st: du kommst.',
      'fill|greetings|Translate: "Good morning!"|guten morgen|Guten Morgen is used until around 11 a.m.',
      'mcq|greetings|You are speaking formally to a stranger. How do you ask their name?|Wie heißt du?;Wie heißen Sie?;Wie heißen wir?;Wie heißt ihr?|Wie heißen Sie?|Sie is the formal form, used with people you do not know well.',
      'build|word-order|Put the words in order: "I come from Pakistan."|Ich komme aus Pakistan.|Subject, conjugated verb in position two, then the rest.',
      'mcq|verb-conjugation|Complete: "Wir ___ in Hamburg." (wohnen)|wohne;wohnst;wohnt;wohnen|wohnen|wir takes the -en ending, identical to the infinitive.',
    ],
    realLife:{situation:'First day of a German course; everyone introduces themselves.', task:'Give four sentences: name, origin, current city, and the languages you speak.'},
    summary:['heißen / kommen aus / wohnen in','Regular endings: -e, -st, -t, -en, -t, -en','du informal, Sie formal'],
  },
  {
    title:'W-Questions: Asking for Information', topic:'personal',
    goal:'Ask and answer the seven question words used in everyday German.',
    why:'A conversation you can only answer is not a conversation. Asking keeps it alive.',
    intro:'German question words nearly all begin with W — and the structure never changes: W-word, verb, subject.',
    vocab:['v_frage','v_antwort','v_adresse','v_telefonnummer','v_beruf','v_e_mail'],
    grammar:'g_questions', time:16, skills:['grammar','speaking','listening'],
    teach:[
      ['The seven basics','Wer (who), Was (what), Wo (where, location), Woher (where from), Wohin (where to), Wann (when), Wie (how), Warum (why). Wie viel / Wie alt / Wie lange extend Wie.'],
      ['Structure','W-word – conjugated verb – subject – rest. Wo wohnst du? Wann kommt der Bus? There is no "do" in German questions.'],
      ['Yes/no questions','No question word: verb first. Kommst du mit? Hast du Zeit? Answer with ja, nein — or doch to contradict a negative question.'],
    ],
    commonMistake:'Translating English "do/does": "Tust du arbeiten?" does not exist. The verb alone forms the question: Arbeitest du?',
    ex:[
      'mcq|word-order|Which question is correctly formed?|Wo du wohnst?;Wo wohnst du?;Wohnst wo du?;Du wohnst wo?|Wo wohnst du?|W-word, then verb, then subject.',
      'mcq|vocab|Which word asks about origin?|Wo;Wohin;Woher;Wann|Woher|Woher kommst du? = Where do you come from?',
      'fill|word-order|Ask formally: "Where do you live?"|wo wohnen sie|Wo wohnen Sie? — verb in position two, Sie capitalised.',
      'mcq|word-order|How do you ask "Do you have time?" informally?|Du hast Zeit?;Hast du Zeit?;Tust du Zeit haben?;Zeit hast du?|Hast du Zeit?|Yes/no question: conjugated verb first.',
      'match|vocab|Match each question word to its meaning.|Wer=who;Was=what;Wann=when;Warum=why|These four cover most everyday questions.',
      'correct|word-order|Correct this sentence: Wie alt du bist?|Wie alt bist du?|After the question phrase the verb must come before the subject.',
    ],
    realLife:{situation:'You meet a new colleague.', task:'Ask four questions: name, origin, residence, occupation.'},
    summary:['W-word – verb – subject','Yes/no questions start with the verb','No "do" auxiliary in German'],
  },
  {
    title:'Numbers, Age & Prices', topic:'numbers', id:'l03',
    goal:'Count, state your age, and understand prices and phone numbers.',
    why:'Numbers appear in every price, appointment, address and form you will meet.',
    intro:'German builds two-digit numbers backwards compared with English, and uses sein — not haben — for age.',
    vocab:['v_zahl','v_nummer','v_preis','v_euro','v_cent','v_geld','v_kosten','v_teuer','v_billig'],
    grammar:'g_sein_haben', time:16, skills:['vocabulary','listening'],
    teach:[
      ['21–99 are built backwards','einundzwanzig = "one-and-twenty" = 21. zweiunddreißig = 32. Written as one word, units first, joined with und.'],
      ['Age uses sein','Ich bin zwanzig Jahre alt. Never "Ich habe zwanzig Jahre" — that is a direct translation from other languages and is immediately noticeable.'],
      ['Prices','2,50 € is said "zwei Euro fünfzig". The comma is the decimal separator; the full stop marks thousands: 1.250,00 €.'],
    ],
    commonMistake:'Using haben for age: "Ich habe zwanzig Jahre" instead of "Ich bin zwanzig Jahre alt".',
    prog:['From word to exchange: talking about age',
      ['alt','old','A bare adjective.'],
      ['zwanzig Jahre alt','twenty years old','Number + Jahre + alt behaves as one block.'],
      ['Ich bin zwanzig Jahre alt.','I am twenty years old.','sein + the block = a full sentence.'],
      ['Wie alt bist du? – Ich bin zwanzig.','How old are you? – I am twenty.','In the answer "Jahre alt" is usually dropped.'],
    ],
    ex:[
      'mcq|vocab|Which number is "einundvierzig"?|14;41;49;91|41|Units first: ein-und-vierzig = 1 + 40.',
      'mcq|grammar|Complete: "Ich ___ 25 Jahre alt."|habe;bin;ist;hat|bin|German uses sein for age.',
      'fill|vocab|How do you say 2,50 € in German words?|zwei euro fünfzig|"zwei Euro fünfzig" — the comma is read as the split between euros and cents.',
      'mcq|vocab|The cashier says "Das macht neunzehn Euro achtzig." How much do you pay?|19,08 €;19,80 €;90,80 €;9,80 €|19,80 €|neunzehn = 19, achtzig = 80 cents.',
      'fill|vocab|Write the number 67 in German.|siebenundsechzig|Units first, one word: siebenundsechzig.',
      'correct|grammar|Correct this sentence: Ich habe dreißig Jahre.|Ich bin dreißig Jahre alt.|Age always uses sein plus Jahre alt.',
    ],
    realLife:{situation:'Paying at a bakery.', task:'Understand the total, hand over the money, ask for a receipt: „Die Quittung, bitte.“'},
    summary:['Units before tens: einundzwanzig','Age with sein','Comma = decimal separator in prices'],
  },
  ]},
{
  title:'Menschen und Familie', theme:'People and family',
  goal:'Describe your family and the people around you.',
  canDo:['Name family members','Say who belongs to whom','Describe people simply'],
  lessons:[
  {
    id:'l04', title:'Family & Possessive Articles', topic:'family',
    goal:'Describe your family using mein, dein, sein and ihr with the correct ending.',
    why:'Family is the most common small-talk topic in a German class and in everyday conversation.',
    intro:'To talk about family you need the words themselves plus one grammar point: possessive articles, which take the same endings as ein.',
    vocab:['v_eltern','v_geschwister','v_grossvater','v_grossmutter','v_onkel','v_tante','v_kind','v_besuchen'],
    grammar:'g_possessiv', time:18, skills:['grammar','vocabulary'],
    teach:[
      ['The possessive stems','ich → mein, du → dein, er/es → sein, sie → ihr, wir → unser, ihr → euer, sie → ihr, Sie → Ihr (capitalised).'],
      ['Endings follow ein','mein Vater (m. nom.), meine Mutter (f.), mein Kind (n.), meine Eltern (pl.). In the accusative the masculine adds -en: Ich besuche meinen Bruder.'],
      ['Two agreements at once','The STEM agrees with the owner, the ENDING with the thing owned: Sie besucht ihren Vater (she → ihr; Vater is masculine accusative → -en).'],
    ],
    commonMistake:'Matching the ending to the owner: "Sie besucht ihr Vater". The ending belongs to the owned noun, not the owner.',
    prog:['From noun to description: „der Bruder“',
      ['der Bruder','the brother','Learned with its article.'],
      ['mein Bruder','my brother','mein replaces der in the nominative.'],
      ['Ich habe einen Bruder.','I have a brother.','haben takes the accusative: ein → einen.'],
      ['Ich besuche meinen Bruder jedes Wochenende.','I visit my brother every weekend.','mein + accusative masculine = meinen.'],
    ],
    ex:[
      'mcq|articles|Complete: "Das ist ___ Mutter." (my)|mein;meine;meinen;meiner|meine|die Mutter is feminine, so the nominative form is meine.',
      'mcq|akkusativ|Complete: "Ich besuche ___ Bruder." (my)|mein;meine;meinen;meinem|meinen|Masculine accusative takes -en.',
      'mcq|articles|Complete: "___ Eltern wohnen in Kabul." (my)|Mein;Meine;Meinen;Meiner|Meine|Plural nominative takes -e.',
      'fill|vocab|Translate: "I have two siblings."|ich habe zwei geschwister|Geschwister is a plural noun; there is no common singular.',
      'match|vocab|Match each family word to its English meaning.|die Tante=aunt;der Onkel=uncle;die Großmutter=grandmother;die Eltern=parents|Learn each noun with its article.',
      'correct|articles|Correct this sentence: Ich besuche mein Schwester.|Ich besuche meine Schwester.|die Schwester is feminine; the accusative feminine stays meine.',
    ],
    realLife:{situation:'Small talk in a language course.', task:'Describe your family in five sentences: how many people, who they are, where they live.'},
    summary:['mein/dein/sein/ihr take ein-endings','Masculine accusative = -en','Stem = owner, ending = owned thing'],
  },
  {
    title:'Describing People & Things', topic:'basics',
    goal:'Describe people and objects with simple adjectives after sein.',
    why:'Adjectives make your German sound like description rather than a list of facts.',
    intro:'After sein, werden and bleiben, a German adjective takes no ending at all — this is the easiest adjective position, and it is where you should start.',
    vocab:['v_gross','v_klein','v_jung','v_alt','v_freundlich','v_neu','v_schon','v_schwierig','v_einfach'],
    grammar:'g_praesens', time:14, skills:['vocabulary','writing'],
    teach:[
      ['No ending after sein','Der Mann ist groß. Die Wohnung ist klein. Das Buch ist neu. Never "ist große".'],
      ['Intensifiers','sehr (very), ziemlich (quite), zu (too — always negative), nicht so (not very): Die Wohnung ist zu teuer. Das Zimmer ist ziemlich klein.'],
      ['Opposites come in pairs','groß/klein, alt/neu, alt/jung, teuer/billig, gut/schlecht, einfach/schwierig, laut/leise. Learning them as pairs doubles your vocabulary for free.'],
    ],
    commonMistake:'Adding an adjective ending after sein: "Das Zimmer ist kleines".',
    ex:[
      'mcq|grammar|Which sentence is correct?|Das Zimmer ist kleines.;Das Zimmer ist klein.;Das Zimmer klein ist.;Das kleine Zimmer ist.|Das Zimmer ist klein.|After sein the adjective has no ending.',
      'fill|vocab|Give the opposite of "teuer".|billig;günstig|billig (cheap) or günstig (reasonably priced).',
      'mcq|vocab|What does "zu klein" mean?|quite small;very small;too small;not small|too small|zu before an adjective always signals a problem: too much of it.',
      'build|word-order|Put in order: "The flat is very expensive."|Die Wohnung ist sehr teuer.|Subject, verb, intensifier, adjective.',
      'match|vocab|Match the opposites.|groß=klein;alt=neu;gut=schlecht;einfach=schwierig|Adjectives are most efficiently learned in pairs.',
    ],
    realLife:{situation:'Viewing a flat.', task:'Say three things about it: size, brightness, price.'},
    summary:['No ending after sein','sehr / ziemlich / zu modify adjectives','Learn adjectives in opposite pairs'],
  },
  ]},
{
  title:'Alltag', theme:'Daily life',
  goal:'Describe your day, your habits and your free time.',
  canDo:['Tell the time','Describe my daily routine','Talk about what I like doing'],
  lessons:[
  {
    title:'Telling the Time', topic:'time',
    goal:'Ask and tell the time in both the everyday and the official system.',
    why:'Appointments, timetables and opening hours all depend on it — and Germany uses both a 12-hour and a 24-hour system.',
    intro:'German has a colloquial way of telling the time and an official one. You need to produce the first and understand the second.',
    vocab:['v_uhrzeit','v_stunde','v_minute','v_morgen','v_vormittag','v_mittag','v_nachmittag','v_abend','v_nacht'],
    grammar:'g_praep_akk_zeit', time:16, skills:['vocabulary','listening'],
    teach:[
      ['Colloquial time','Es ist acht Uhr. Es ist Viertel nach acht (8:15). Es ist halb neun (8:30 — careful: HALF TO nine, not half past). Es ist Viertel vor neun (8:45).'],
      ['Official time','Used in timetables and announcements: Der Zug fährt um 14:37 Uhr — "vierzehn Uhr siebenunddreißig".'],
      ['Prepositions','um + clock time (um acht Uhr), am + day or part of day (am Montag, am Abend), in der Nacht, von … bis (von neun bis fünf).'],
    ],
    commonMistake:'Reading "halb neun" as 9:30. German counts towards the coming hour: halb neun = 8:30.',
    ex:[
      'mcq|vocab|What time is "halb sieben"?|7:30;6:30;7:00;6:00|6:30|halb + hour means half an hour BEFORE that hour.',
      'mcq|vocab|How do you say 8:15 colloquially?|halb acht;Viertel vor acht;Viertel nach acht;acht Uhr fünfzehn|Viertel nach acht|Viertel nach = quarter past.',
      'fill|grammar|Complete: "Der Kurs beginnt ___ neun Uhr."|um|um is used with clock times.',
      'mcq|grammar|Complete: "___ Montag habe ich einen Termin."|Um;In;Am;Bei|Am|am (an + dem) is used with days and parts of the day.',
      'fill|vocab|Write 14:45 as an official announcement would say it.|vierzehn uhr fünfundvierzig|Official times are read as hour + Uhr + minutes.',
    ],
    realLife:{situation:'At a station, an announcement gives a new departure time.', task:'Note the time and say it back colloquially.'},
    summary:['halb neun = 8:30','um + time, am + day','Official time uses the 24-hour clock'],
  },
  {
    id:'l05', title:'Daily Routine & Separable Verbs', topic:'routine',
    goal:'Describe your day using separable verbs in the correct position.',
    why:'Half the verbs describing a normal day are separable — without this rule your daily routine will be ungrammatical.',
    intro:'Verbs like aufstehen, einkaufen, anrufen and fernsehen split in a main clause: the prefix jumps to the end.',
    vocab:['v_aufstehen','v_fernsehen','v_anrufen','v_einkaufen','v_arbeiten','v_lernen','v_immer','v_oft','v_manchmal','v_nie'],
    grammar:'g_trennbar', time:18, skills:['grammar','speaking'],
    teach:[
      ['The sentence bracket','Ich stehe um sechs Uhr auf. The conjugated part is in position two, the prefix is at the very end, and everything else sits between them. This bracket is a structural signature of German.'],
      ['Separable or not?','Separable prefixes are stressed: ÁNrufen, ÁUFstehen, ÉINkaufen, FÉRNsehen, MÍTkommen. Inseparable prefixes (be-, ver-, er-, ent-, ge-, zer-) are unstressed and never split: verstehen, bekommen, erklären.'],
      ['Frequency adverbs','immer (always), meistens (mostly), oft (often), manchmal (sometimes), selten (rarely), nie (never). They sit in the middle field: Ich stehe immer früh auf.'],
    ],
    commonMistake:'Leaving the verb whole: "Ich aufstehe um sechs." The prefix must go to the end in a main clause.',
    prog:['Building a routine sentence: „aufstehen“',
      ['aufstehen','to get up','The infinitive, still in one piece.'],
      ['Ich stehe auf.','I get up.','In a main clause the prefix goes to the end.'],
      ['Ich stehe um sechs Uhr auf.','I get up at six.','The time expression goes inside the bracket.'],
      ['Ich stehe immer um sechs Uhr auf und frühstücke.','I always get up at six and have breakfast.','A frequency adverb and a second clause with und.'],
    ],
    ex:[
      'mcq|word-order|Which sentence is correct?|Ich aufstehe um sieben.;Ich stehe um sieben auf.;Ich stehe auf um sieben.;Um sieben ich aufstehe.|Ich stehe um sieben auf.|Conjugated part second, prefix at the end.',
      'build|word-order|Put in order: "I call my mother every day."|Ich rufe jeden Tag meine Mutter an.|anrufen splits: rufe … an.',
      'mcq|verb-conjugation|Which verb is NOT separable?|anrufen;verstehen;einkaufen;mitkommen|verstehen|ver- is an inseparable prefix and is never stressed.',
      'fill|word-order|Complete: "Am Abend ___ ich ___." (fernsehen)|sehe;fern|fernsehen splits into sehe … fern.',
      'correct|word-order|Correct this sentence: Ich einkaufe im Supermarkt.|Ich kaufe im Supermarkt ein.|Separable verbs split in a main clause.',
      'mcq|vocab|Which adverb means "rarely"?|immer;oft;selten;nie|selten|Frequency scale: immer > meistens > oft > manchmal > selten > nie.',
    ],
    realLife:{situation:'Describing your day to a classmate.', task:'Give six sentences from waking up to going to bed, using at least two separable verbs.'},
    summary:['Separable prefix goes to the end of a main clause','Stressed prefix = separable','Frequency adverbs sit in the middle field'],
  },
  {
    title:'Hobbies, Likes & Dislikes', topic:'freetime',
    goal:'Say what you like doing, prefer doing and do not like doing.',
    why:'"gern" is how German expresses liking an activity — there is no separate verb like English "to like doing".',
    intro:'German does not say "I like to cook". It says "Ich koche gern" — literally "I cook gladly".',
    vocab:['v_freizeit','v_sport','v_musik','v_film','v_spielen','v_hoeren','v_schwimmen','v_gern','v_lieber','v_moegen'],
    grammar:'g_praesens', time:15, skills:['vocabulary','speaking'],
    teach:[
      ['gern + verb','Ich koche gern. Ich lese gern. The negative is "nicht gern": Ich putze nicht gern.'],
      ['Preference and superlative','gern → lieber (rather) → am liebsten (most of all): Ich trinke gern Tee, lieber Kaffee, am liebsten Wasser.'],
      ['mögen for things','mögen is used with nouns, not activities: Ich mag Kaffee. For activities use gern: Ich trinke gern Kaffee.'],
    ],
    commonMistake:'Translating "I like to swim" as "Ich mag schwimmen". German says "Ich schwimme gern".',
    ex:[
      'mcq|vocab|How do you say "I like cooking"?|Ich mag kochen.;Ich koche gern.;Ich bin gern kochen.;Ich liebe kochen.|Ich koche gern.|gern after the verb expresses liking an activity.',
      'mcq|vocab|What does "am liebsten" mean?|gladly;rather;most of all;not at all|most of all|gern – lieber – am liebsten.',
      'fill|vocab|Translate: "I do not like working on Sundays." (use: am Sonntag)|ich arbeite am sonntag nicht gern;ich arbeite nicht gern am sonntag|"nicht gern" is the negative of gern.',
      'build|word-order|Put in order: "I would rather drink tea."|Ich trinke lieber Tee.|lieber sits after the conjugated verb.',
      'mcq|grammar|Complete: "Ich ___ keinen Kaffee." (mögen)|mag;möchte;magst;mögt|mag|ich mag — mögen has no ending in the ich-form.',
    ],
    realLife:{situation:'Someone asks what you do at the weekend.', task:'Name three activities you like and one you do not, using gern / nicht gern / am liebsten.'},
    summary:['gern = like doing','gern → lieber → am liebsten','mögen for nouns, gern for activities'],
  },
  ]},
{
  title:'Essen und Einkaufen', theme:'Food and shopping',
  goal:'Shop, order food and handle prices and quantities.',
  canDo:['Order in a café','Ask prices','Say what I need and how much'],
  lessons:[
  {
    id:'l06', title:'Food, Shopping & the Accusative in Practice', topic:'food',
    goal:'Buy food and order drinks using the accusative correctly.',
    why:'Shopping is where German beginners first need the accusative — and where the der/den mistake is heard most.',
    intro:'Almost every shopping sentence has a direct object: Ich kaufe den Apfel. Ich nehme einen Kaffee. That object is in the accusative.',
    vocab:['v_brot','v_milch','v_gemuese','v_obst','v_supermarkt','v_geschaeft','v_baeckerei','v_einkaufen','v_brauchen','v_kosten','v_kasse'],
    grammar:'g_akkusativ', time:20, skills:['grammar','vocabulary','speaking'],
    teach:[
      ['Only the masculine changes','der → den, ein → einen. Feminine, neuter and plural articles look exactly like the nominative. This is genuinely good news: three quarters of the work is already done.'],
      ['Ordering politely','Ich hätte gern … / Ich nehme … / Einen Kaffee, bitte. "Ich will einen Kaffee" is grammatically correct but sounds blunt in a shop.'],
      ['Quantities','ein Kilo Äpfel, ein halbes Kilo Käse, eine Flasche Wasser, eine Packung Milch, 200 Gramm Schinken. The measure word is not followed by "von".'],
    ],
    commonMistake:'"Ich kaufe der Apfel." Masculine direct objects take den — this single change is the most common accusative error in German.',
    prog:['From word to shop counter: „der Kaffee“',
      ['der Kaffee','the coffee','Masculine noun, learned with its article.'],
      ['einen Kaffee','a coffee (accusative)','ein → einen for masculine objects.'],
      ['Ich nehme einen Kaffee.','I will take a coffee.','A complete order.'],
      ['Ich nehme einen Kaffee und ein Wasser, bitte.','A coffee and a water, please.','das Wasser is neuter, so ein stays unchanged.'],
    ],
    guided:[
      {prompt:'Ich kaufe ___ Apfel. (der)', answer:'den'},
      {prompt:'Ich brauche ___ Flasche Wasser. (eine)', answer:'eine'},
      {prompt:'Ich nehme ___ Brot. (das)', answer:'das'},
    ],
    ex:[
      'mcq|akkusativ|Complete: "Ich kaufe ___ Apfel."|der;den;dem;das|den|der Apfel is masculine; as a direct object it becomes den.',
      'mcq|akkusativ|Complete: "Ich brauche ___ Tasche." (die Tasche)|die;den;der;dem|die|Feminine articles do not change in the accusative.',
      'mcq|akkusativ|Complete: "Ich nehme ___ Kaffee." (ein)|ein;einen;einem;eine|einen|Masculine indefinite: ein → einen.',
      'fill|vocab|Order politely: "I would like a kilo of apples."|ich hätte gern ein kilo äpfel|"Ich hätte gern" is the standard polite request form.',
      'correct|akkusativ|Correct this sentence: Ich esse der Apfel.|Ich esse den Apfel.|A masculine direct object requires den.',
      'match|vocab|Match each shop to what you buy there.|die Bäckerei=Brot;die Apotheke=Medikamente;der Supermarkt=Lebensmittel;der Markt=Obst und Gemüse|Knowing the shop names makes errands much faster.',
    ],
    realLife:{situation:'At a bakery counter.', task:'Order two items, ask the price, and pay: „Was kostet das?“ – „Ich zahle mit Karte.“'},
    summary:['der → den, ein → einen','Feminine/neuter/plural unchanged','Ich hätte gern … is the polite order form'],
  },
  {
    id:'l07', title:'Negation: nicht and kein', topic:'grammar',
    goal:'Say what you do not have, do not do and do not want, choosing correctly between nicht and kein.',
    why:'Half of everyday communication is negative: no time, no money, not today, not yet.',
    intro:'German splits negation in two. kein negates nouns without a definite article; nicht negates everything else.',
    vocab:['v_geld','v_zeit','v_brauchen','v_leider','v_vielleicht'],
    grammar:'g_negation', time:18, skills:['grammar','speaking'],
    teach:[
      ['kein for indefinite nouns','Ich habe kein Geld. Ich habe keine Zeit. Ich habe keinen Bruder. kein takes exactly the ein endings, including keinen in the masculine accusative.'],
      ['nicht for everything else','With a definite article or possessive: Das ist nicht mein Buch. With verbs: Ich arbeite heute nicht. With adjectives: Das ist nicht gut.'],
      ['Where nicht goes','At the end when it negates the whole sentence (Ich komme heute nicht), but directly before the element it negates (Ich fahre nicht nach Berlin) and before a predicate adjective or a separable prefix (Ich rufe dich nicht an).'],
    ],
    commonMistake:'"Ich habe nicht Zeit." An indefinite noun requires kein: Ich habe keine Zeit.',
    ex:[
      'mcq|negation|Complete: "Ich habe ___ Geld."|nicht;kein;keine;keinen|kein|das Geld, no article → kein.',
      'mcq|negation|Complete: "Ich habe ___ Bruder."|kein;keine;keinen;nicht|keinen|der Bruder is masculine and is here a direct object → keinen.',
      'mcq|negation|Complete: "Das ist ___ mein Auto."|kein;keine;nicht;nichts|nicht|A possessive is definite, so nicht is used.',
      'fill|negation|Translate: "I am not working today."|ich arbeite heute nicht|nicht goes to the end when the whole statement is negated.',
      'correct|negation|Correct this sentence: Ich habe nicht Zeit.|Ich habe keine Zeit.|die Zeit without an article is negated with keine.',
      'mcq|negation|Which sentence is correct?|Ich rufe nicht dich an.;Ich rufe dich nicht an.;Ich nicht rufe dich an.;Ich rufe dich an nicht.|Ich rufe dich nicht an.|nicht stands before the separable prefix at the end.',
    ],
    realLife:{situation:'Declining an invitation.', task:'Say you cannot come, give a reason, and suggest another day.'},
    summary:['kein + indefinite noun','nicht + everything else','nicht before the element it negates, otherwise at the end'],
  },
  ]},
{
  title:'Unterwegs', theme:'Out and about',
  goal:'Use transport, ask for directions and manage appointments.',
  canDo:['Buy a ticket','Ask and understand directions','Make and cancel an appointment'],
  lessons:[
  {
    title:'Transport & Directions', topic:'city',
    goal:'Ask for and understand directions and buy a ticket.',
    why:'You will need this on your first day in any German city, and the answers use a small, predictable set of phrases.',
    intro:'Directions in German rely on a handful of prepositions and imperatives — once you recognise them, most answers become understandable even at speed.',
    vocab:['v_bahnhof','v_haltestelle','v_bus','v_zug','v_fahrkarte','v_links','v_rechts','v_geradeaus','v_fahren','v_gehen'],
    grammar:'g_imperativ', time:18, skills:['vocabulary','listening','conversation'],
    teach:[
      ['Asking','Entschuldigung, wie komme ich zum Bahnhof? / Wo ist die nächste Haltestelle? / Ist es weit?'],
      ['Understanding the answer','Gehen Sie geradeaus. Nehmen Sie die zweite Straße rechts. Biegen Sie links ab. Es ist gegenüber der Post. Das sind etwa fünf Minuten zu Fuß.'],
      ['zum, zur, nach','zu + dem = zum (masc./neuter), zu + der = zur (feminine): zum Bahnhof, zur Apotheke. For cities and countries use nach: nach Berlin. For "home" the fixed forms are nach Hause (motion) and zu Hause (location).'],
    ],
    commonMistake:'"Ich gehe nach dem Arzt." Use zu with people and institutions: Ich gehe zum Arzt.',
    ex:[
      'mcq|prepositions|Complete: "Wie komme ich ___ Bahnhof?"|zur;zum;nach;bei|zum|der Bahnhof → zu dem → zum.',
      'mcq|prepositions|Complete: "Ich gehe ___ Apotheke."|zum;zur;nach;in|zur|die Apotheke → zu der → zur.',
      'mcq|prepositions|Complete: "Wir fahren morgen ___ Hamburg."|zu;zum;nach;in|nach|Cities and countries without an article take nach.',
      'fill|vocab|Translate: "Go straight ahead and then turn left." (formal)|gehen sie geradeaus und dann links;gehen sie geradeaus und biegen sie links ab|Both are natural; abbiegen is the precise verb for turning.',
      'match|vocab|Match each phrase to its meaning.|geradeaus=straight ahead;gegenüber=opposite;in der Nähe=nearby;zu Fuß=on foot|These four appear in almost every direction you will be given.',
      'correct|prepositions|Correct this sentence: Ich gehe nach dem Arzt.|Ich gehe zum Arzt.|People and institutions take zu, not nach.',
    ],
    realLife:{situation:'You are lost near the city centre.', task:'Stop someone politely, ask the way to the station, and confirm what you understood.'},
    summary:['zum / zur / nach','Direction answers use the Sie-imperative','nach Hause vs zu Hause'],
  },
  {
    id:'l08', title:'Appointments & Modal Verbs', topic:'appointments',
    goal:'Make, change and cancel an appointment using modal verbs.',
    why:'German life runs on Termine — doctor, office, landlord, school. Cancelling politely is a skill in itself.',
    intro:'Appointments need modal verbs: ich kann nicht, ich muss, können wir …? Modals put the main verb at the end of the sentence.',
    vocab:['v_termin','v_absagen','v_verschieben','v_anrufen','v_passen','v_praxis','v_warten'],
    grammar:'g_modal', time:20, skills:['grammar','conversation','speaking'],
    teach:[
      ['The six modals','können (can), müssen (must), wollen (want), dürfen (may), sollen (should), möchten (would like). ich and er/sie/es take NO ending: ich kann, er kann.'],
      ['The bracket again','Modal in position two, infinitive at the very end: Ich kann am Montag nicht kommen. Können Sie mir helfen?'],
      ['Appointment phrases','Ich hätte gern einen Termin. Passt Ihnen Donnerstag um zehn? Leider kann ich nicht kommen. Können wir den Termin verschieben? Ich muss den Termin leider absagen.'],
    ],
    commonMistake:'"Ich kann kommen nicht am Montag." The infinitive belongs at the very end: Ich kann am Montag nicht kommen.',
    prog:['Building a cancellation: „können“',
      ['kommen','to come','The infinitive.'],
      ['Ich kann kommen.','I can come.','Modal second, infinitive last.'],
      ['Ich kann leider nicht kommen.','Unfortunately I cannot come.','leider and nicht sit in the middle field.'],
      ['Ich kann am Donnerstag leider nicht kommen. Können wir den Termin verschieben?','I unfortunately cannot come on Thursday. Can we postpone the appointment?','A complete, polite cancellation.'],
    ],
    ex:[
      'mcq|modal-verbs|Complete: "Ich ___ heute nicht kommen."|kann;kannst;können;könnt|kann|ich kann — modals take no ending in the ich-form.',
      'mcq|word-order|Which sentence is correct?|Ich muss arbeiten morgen.;Ich muss morgen arbeiten.;Ich morgen muss arbeiten.;Morgen ich muss arbeiten.|Ich muss morgen arbeiten.|The infinitive goes to the end of the sentence.',
      'fill|modal-verbs|Ask politely: "Can you help me?" (formal)|können sie mir helfen|Können Sie mir helfen? — modal first in a yes/no question, infinitive last.',
      'mcq|modal-verbs|Which modal expresses permission?|müssen;dürfen;sollen;wollen|dürfen|dürfen = may, be allowed to. nicht dürfen = must not.',
      'correct|word-order|Correct this sentence: Ich kann sprechen Deutsch.|Ich kann Deutsch sprechen.|The infinitive must stand at the end.',
      'fill|vocab|Translate: "I have to cancel the appointment."|ich muss den termin absagen|der Termin → den Termin (accusative), absagen stays whole at the end after the modal.',
    ],
    realLife:{situation:'You are ill and cannot attend a doctor\u2019s appointment tomorrow.', task:'Phone the practice: greet, state your name, cancel, and ask for a new appointment.'},
    summary:['Modals take no ending in ich/er','Infinitive goes to the end','Cancellation phrases are fixed and worth memorising'],
  },
  ]},
{
  title:'Wohnen und Arbeiten', theme:'Living and working',
  goal:'Describe where you live and what you do.',
  canDo:['Describe my flat','Talk about my job or studies','Say where things are'],
  lessons:[
  {
    title:'My Home & Where Things Are', topic:'home',
    goal:'Describe a flat and say where objects are located.',
    why:'Flat descriptions are a standard A1 exam task and a constant everyday topic.',
    intro:'Describing a home needs room vocabulary plus a first look at location prepositions — the ones that will later become the two-way prepositions.',
    vocab:['v_wohnung','v_zimmer','v_kueche','v_bad','v_bett','v_schrank','v_fenster','v_tuer','v_miete','v_gemuetlich','v_hell'],
    grammar:'g_praep_akk_zeit', time:18, skills:['vocabulary','writing','reading'],
    teach:[
      ['There is / there are','German uses "es gibt" + accusative: Es gibt einen Balkon. In a flat description "haben" is even more common: Die Wohnung hat drei Zimmer.'],
      ['Saying where things are','Das Bett steht am Fenster. Die Lampe hängt über dem Tisch. Der Stuhl steht neben dem Bett. At A1 you can learn these as fixed phrases; A2 explains the case behind them.'],
      ['Describing quality','Die Wohnung ist hell und gemütlich, aber ziemlich klein. Die Miete beträgt 650 Euro warm. ("warm" = including bills, "kalt" = excluding them — this appears in every German rental advert.)'],
    ],
    commonMistake:'Saying "Es gibt ein Balkon". es gibt always takes the accusative: es gibt einen Balkon.',
    ex:[
      'mcq|akkusativ|Complete: "Es gibt ___ Balkon."|ein;einen;einem;eine|einen|es gibt is followed by the accusative; der Balkon → einen Balkon.',
      'fill|vocab|Translate: "The flat has three rooms."|die wohnung hat drei zimmer|das Zimmer has no plural ending: drei Zimmer.',
      'mcq|vocab|In a rental advert, what does "650 Euro warm" mean?|650 € plus bills;650 € including bills;650 € deposit;650 € per week|650 € including bills|warm = Nebenkosten included; kalt = rent only.',
      'match|vocab|Match each room to its use.|die Küche=kochen;das Bad=duschen;das Schlafzimmer=schlafen;der Balkon=draußen sitzen|Room vocabulary plus one verb each is enough to describe any flat.',
      'build|word-order|Put in order: "The flat is bright and cosy."|Die Wohnung ist hell und gemütlich.|Two adjectives joined with und after sein, no endings.',
    ],
    realLife:{situation:'A friend asks about your new flat in a voice message.', task:'Describe it in five sentences: size, rooms, light, rent, what you like about it.'},
    summary:['es gibt + accusative','Flat descriptions use haben and sein','warm vs kalt rent'],
  },
  {
    title:'Work, Study & Talking About Your Day', topic:'work-school',
    goal:'Say what you do for a living or study, and describe a working day.',
    why:'"Was machen Sie beruflich?" is asked in every first conversation with an adult in Germany.',
    intro:'Professions in German take no article after sein: Ich bin Lehrer, not "Ich bin ein Lehrer".',
    vocab:['v_arbeit','v_firma','v_kollege','v_chef','v_kurs','v_studieren','v_arbeiten','v_anfangen','v_hausaufgabe'],
    grammar:'g_praesens', time:16, skills:['vocabulary','speaking'],
    teach:[
      ['Professions take no article','Ich bin Lehrer. Sie ist Ärztin. Er ist Student. Adding "ein" is a classic English-influenced error.'],
      ['Female forms','Most professions add -in for women: der Lehrer → die Lehrerin, der Arzt → die Ärztin (with umlaut), der Verkäufer → die Verkäuferin.'],
      ['Talking about your day at work','Ich arbeite als Verkäuferin bei Rewe. Ich arbeite Vollzeit / Teilzeit / in Schichten. Der Unterricht fängt um acht an und dauert vier Stunden.'],
    ],
    commonMistake:'"Ich bin ein Lehrer." No article is used with professions after sein or werden.',
    ex:[
      'mcq|grammar|Which sentence is correct?|Ich bin ein Lehrer.;Ich bin Lehrer.;Ich bin der Lehrer von Beruf.;Ich habe Lehrer.|Ich bin Lehrer.|Professions after sein take no article.',
      'fill|vocab|Give the female form of "der Verkäufer".|die verkäuferin;verkäuferin|Add -in: die Verkäuferin.',
      'mcq|vocab|What does "Ich arbeite Teilzeit" mean?|I work overtime;I work part-time;I work shifts;I am unemployed|I work part-time|Vollzeit = full-time, Teilzeit = part-time.',
      'fill|word-order|Complete: "Der Unterricht ___ um acht ___." (anfangen)|fängt;an|anfangen is separable: fängt … an.',
      'build|word-order|Put in order: "I work as a nurse in a hospital."|Ich arbeite als Krankenpfleger in einem Krankenhaus.|als + profession without an article; in + dative for the workplace.',
    ],
    realLife:{situation:'Small talk at a neighbour\u2019s barbecue.', task:'Answer „Was machen Sie beruflich?“ in three sentences.'},
    summary:['No article with professions','-in marks female professions','als + profession'],
  },
  ]},
{
  title:'Gesundheit und Alltagsprobleme', theme:'Health and everyday problems',
  goal:'Manage a doctor\u2019s visit and describe simple problems.',
  canDo:['Describe symptoms','Understand simple instructions','Ask for help'],
  lessons:[
  {
    title:'At the Doctor', topic:'health',
    goal:'Describe symptoms and understand the doctor\u2019s basic instructions.',
    why:'Health vocabulary is the one set of words you cannot postpone learning — you may need it without warning.',
    intro:'Symptoms in German use two patterns: "Ich habe …" for a condition and "… tut mir weh" for pain.',
    vocab:['v_arzt','v_aerztin','v_schmerz','v_kopf','v_bauch','v_medikament','v_krank','v_muede','v_rezept'],
    grammar:'g_sein_haben', time:16, skills:['vocabulary','conversation','listening'],
    teach:[
      ['Two symptom patterns','Ich habe Kopfschmerzen / Fieber / Husten. — or — Mein Kopf tut weh. / Der Rücken tut mir weh. Both are correct; the first is more common.'],
      ['At reception','Ich habe einen Termin um zehn. Ich bin gesetzlich / privat versichert. Hier ist meine Versichertenkarte.'],
      ['Instructions you will hear','Nehmen Sie die Tabletten dreimal täglich. Bleiben Sie im Bett. Kommen Sie in einer Woche wieder. Trinken Sie viel.'],
    ],
    commonMistake:'Translating "I am cold" literally as "Ich bin kalt" — that means your body temperature is low to the touch. Say "Mir ist kalt".',
    ex:[
      'mcq|vocab|How do you say "I have a headache"?|Ich bin Kopfschmerzen.;Ich habe Kopfschmerzen.;Mein Kopf ist Schmerz.;Ich mache Kopfschmerzen.|Ich habe Kopfschmerzen.|Symptoms usually use haben.',
      'mcq|grammar|Which is correct for "I am cold"?|Ich bin kalt.;Mir ist kalt.;Ich habe kalt.;Es ist mich kalt.|Mir ist kalt.|German uses a dative construction for how you feel.',
      'fill|vocab|Translate: "I need a prescription."|ich brauche ein rezept|das Rezept is neuter, so ein does not change in the accusative.',
      'match|vocab|Match each instruction to its meaning.|dreimal täglich=three times a day;nach dem Essen=after meals;im Bett bleiben=stay in bed;viel trinken=drink a lot|These four cover most simple medical instructions.',
      'fill|vocab|Tell the receptionist you have an appointment at ten.|ich habe einen termin um zehn|der Termin → einen Termin in the accusative.',
    ],
    realLife:{situation:'Your first visit to a German doctor\u2019s practice.', task:'Check in at reception, describe two symptoms, and confirm the instruction you were given.'},
    summary:['Ich habe + symptom / … tut mir weh','Mir ist kalt, not Ich bin kalt','Instructions come as Sie-imperatives'],
  },
  {
    title:'Weather & Small Talk', topic:'weather',
    goal:'Talk about the weather and use it to open a conversation.',
    why:'Weather is the standard neutral opening in German small talk, and it recycles all the sentence structures you already know.',
    intro:'Weather sentences use impersonal "es": Es regnet. Es ist kalt. Es gibt Schnee.',
    vocab:['v_wetter','v_regen','v_schnee','v_sonne','v_warm','v_kalt','v_regnen','v_scheinen'],
    grammar:'g_praesens', time:12, skills:['vocabulary','conversation'],
    teach:[
      ['The impersonal es','Es regnet. Es schneit. Es ist windig. The subject "es" has no meaning here but cannot be left out.'],
      ['Temperature','Es sind 18 Grad. Es ist minus fünf Grad / fünf Grad unter null.'],
      ['Small talk formulas','Schönes Wetter heute, oder? Furchtbares Wetter! Es soll morgen regnen. Any of these opens a conversation at a bus stop.'],
    ],
    commonMistake:'Dropping "es": "Regnet heute" is not a sentence. German always needs the subject: Es regnet heute.',
    ex:[
      'mcq|grammar|Which sentence is correct?|Regnet heute.;Es regnet heute.;Heute regnet.;Ist regnen heute.|Es regnet heute.|Weather verbs need the impersonal subject es.',
      'fill|vocab|Translate: "It is very cold today."|es ist heute sehr kalt;heute ist es sehr kalt|Both orders are correct; the verb stays in position two.',
      'mcq|vocab|What does "Es sind zwanzig Grad" mean?|It is twenty degrees;It is twenty o\u2019clock;There are twenty people;It costs twenty|It is twenty degrees|Grad = degrees of temperature.',
      'build|word-order|Put in order: "Tomorrow it is supposed to rain."|Morgen soll es regnen.|Morgen fills position one, the modal follows, the infinitive goes last.',
    ],
    realLife:{situation:'Waiting at a bus stop next to a neighbour.', task:'Open a conversation about the weather and keep it going for two turns.'},
    summary:['Weather verbs take impersonal es','Es sind … Grad','Weather is the standard small-talk opener'],
  },
  ]},
{
  title:'A1-Abschluss', theme:'Consolidation and A1 review',
  goal:'Consolidate A1 grammar and prove you can handle everyday situations.',
  canDo:['Combine all A1 structures in one conversation','Write a short personal text','Pass an A1-style test'],
  lessons:[
  {
    id:'l10', title:'Putting It Together: Connected Sentences', topic:'grammar',
    goal:'Join simple sentences into connected speech with und, aber, oder and denn.',
    why:'A1 speech stops sounding like a list the moment you can connect two ideas in one sentence.',
    intro:'Five conjunctions join two main clauses without touching the word order: und, aber, oder, denn, sondern.',
    vocab:['v_leider','v_vielleicht','v_auch','v_noch','v_schon'],
    grammar:'g_konjunktionen_a1', time:16, skills:['grammar','writing','speaking'],
    teach:[
      ['Position zero','und, aber, oder, denn and sondern do not count as a sentence element, so the verb of the second clause still stands in position two: Ich bleibe zu Hause, denn ich bin krank.'],
      ['denn vs weil','Both mean "because". denn keeps normal word order; weil (which you meet at A2) sends the verb to the end. At A1, use denn.'],
      ['sondern','Only after a negation, to correct it: Das ist nicht Tee, sondern Kaffee.'],
    ],
    commonMistake:'Treating denn like weil and pushing the verb to the end: "denn ich krank bin" is wrong.',
    ex:[
      'mcq|word-order|Which sentence is correct?|Ich bleibe zu Hause, denn ich bin krank.;Ich bleibe zu Hause, denn ich krank bin.;Ich bleibe zu Hause, denn bin ich krank.;Ich bleibe zu Hause denn krank ich bin.|Ich bleibe zu Hause, denn ich bin krank.|denn does not change the word order.',
      'mcq|word-order|Complete: "Das ist nicht Tee, ___ Kaffee."|aber;sondern;oder;denn|sondern|sondern corrects a preceding negation.',
      'build|word-order|Put in order: "I am tired but I am still working."|Ich bin müde, aber ich arbeite noch.|aber sits at position zero; the verb of the second clause stays second.',
      'fill|word-order|Join with "denn": "Ich lerne Deutsch." + "Ich arbeite in Berlin."|ich lerne deutsch denn ich arbeite in berlin|denn keeps normal order in the second clause.',
      'correct|word-order|Correct this sentence: Ich komme nicht, denn ich keine Zeit habe.|Ich komme nicht, denn ich habe keine Zeit.|After denn the verb stays in position two.',
    ],
    realLife:{situation:'Writing a short message explaining why you are late.', task:'Write three connected sentences using und, aber and denn.'},
    summary:['und/aber/oder/denn/sondern = position zero','denn keeps normal order','sondern only after a negation'],
  },
  {
    title:'A1 Review & Self-Check', topic:'grammar',
    goal:'Check that every A1 structure is secure before moving to A2.',
    why:'A2 assumes A1 grammar is automatic. Ten minutes of honest self-checking now saves weeks of confusion later.',
    intro:'This lesson mixes everything from A1: conjugation, word order, questions, negation, accusative, possessives, modals and separable verbs.',
    vocab:[],
    grammar:'g_akkusativ', time:20, skills:['grammar','vocabulary'], difficulty:'challenging',
    teach:[
      ['What A1 really means','You can handle predictable everyday situations with simple sentences. You are not expected to speak about the past, give extended reasons, or use the dative freely — that is A2.'],
      ['The four structures that must be automatic','1) Verb in position two. 2) Verb ending matching the subject. 3) den/einen for masculine direct objects. 4) The bracket: modal/separable verb sends material to the end.'],
    ],
    commonMistake:'Moving on while the accusative is still guessed. Every later case builds on it.',
    ex:[
      'mcq|verb-conjugation|Complete: "Er ___ jeden Tag zur Arbeit." (fahren)|fahre;fahrst;fährt;fahren|fährt|fahren is a strong verb: du fährst, er fährt.',
      'mcq|akkusativ|Complete: "Ich sehe ___ Mann."|der;den;dem;des|den|Masculine direct object → den.',
      'mcq|negation|Complete: "Ich habe ___ Auto."|nicht;kein;keine;keinen|kein|das Auto without an article → kein.',
      'mcq|word-order|Which sentence is correct?|Morgen ich muss arbeiten.;Morgen muss ich arbeiten.;Morgen arbeiten ich muss.;Ich morgen muss arbeiten.|Morgen muss ich arbeiten.|The conjugated verb stays second.',
      'fill|word-order|Complete: "Ich ___ um sieben Uhr ___." (aufstehen)|stehe;auf|Separable verb: stehe … auf.',
      'fill|articles|Complete: "Ich besuche ___ Schwester." (my)|meine|die Schwester is feminine; the accusative feminine keeps meine.',
      'correct|akkusativ|Correct this sentence: Ich kaufe ein Apfel.|Ich kaufe einen Apfel.|der Apfel → einen Apfel in the accusative.',
      'mcq|modal-verbs|Complete: "___ du mir helfen?"|Kann;Kannst;Können;Könnt|Kannst|du kannst; in a yes/no question the verb comes first.',
    ],
    realLife:{situation:'An A1 speaking test.', task:'Introduce yourself, describe your day, and ask your partner three questions.'},
    summary:['Verb second; endings match the subject','den/einen for masculine objects','The bracket sends infinitives and prefixes to the end'],
  },
  ]},
]);

  return { A0, A1 };
})();

if(typeof module !== 'undefined' && module.exports){ module.exports = CURRICULUM_A0A1; }
