/* ============================================================
   CEFR LEVEL METADATA (spec §8)
   Not "A1 = beginner". Each level carries the curriculum
   metadata the engine needs: scope, skill expectations,
   assessment criteria, prerequisites and readiness thresholds.
   A0 is explicitly flagged as a pre-CEFR foundation level.
   ============================================================ */
const LEVEL_META = [
{
  id:'level_a0', level:'A0', official:false, title:'Foundation (pre-A1)',
  description:'Absolute beginner foundation. Before CEFR A1 begins: the writing system, the sound system, and the handful of fixed phrases that make a first German classroom or first German street conversation survivable.',
  objectives:[
    'Read every German letter aloud, including ä, ö, ü and ß.',
    'Recognise that all nouns are capitalised and carry a gender article.',
    'Greet, say goodbye, say please and thank you, and ask for repetition.',
    'Count to twenty and give a phone number digit by digit.',
    'Understand that the conjugated verb sits in position two of a statement.',
  ],
  skills:{reading:'Single words, names and very short labels.', writing:'Copy words correctly, including umlauts and ß.',
    listening:'Recognise greetings, numbers and spelled-out names.', speaking:'Produce fixed greeting formulas intelligibly.',
    vocabulary:'~120 words and fixed phrases.', grammar:'Sound–spelling rules, noun capitalisation, article awareness, verb-second awareness.',
    pronunciation:'Umlauts, ch, sch, sp/st, ei vs ie, final -er, w/v/z/s sounds.', conversation:'Two-turn greeting exchange.'},
  grammarScope:['alphabet and spelling','noun capitalisation','der/die/das awareness','personal pronouns','sein (ich/du/er) as fixed forms','verb-second awareness','yes/no vs W-questions awareness'],
  vocabularyScope:['alphabet','numbers 0–20','greetings and politeness','classroom language','days of the week','colours','a first set of concrete nouns'],
  communicationGoals:['Greet and take leave','Say your name','Spell your name','Say you do not understand','Ask someone to speak more slowly'],
  assessmentCriteria:['Correct letter–sound mapping','Correct spelling of umlaut words','Recognition of article + noun as one unit'],
  prerequisites:[], nextLevel:'A1',
  readiness:{ lessonCompletionPct:70, grammarMastery:0.55, vocabMastery:0.5, minSkills:{pronunciation:0.5, vocabulary:0.5} },
  targetVocabCumulative:120, examAlignment:[],
},
{
  id:'level_a1', level:'A1', official:true, title:'Breakthrough',
  description:'The learner can understand and use familiar everyday expressions and very basic phrases aimed at satisfying concrete needs, introduce themselves and others, and ask and answer questions about personal details such as where they live, people they know and things they have.',
  objectives:[
    'Introduce yourself and others and give personal details.',
    'Handle shopping, ordering food, prices, times and appointments.',
    'Describe your family, home, daily routine and free time in simple sentences.',
    'Ask and answer W-questions and yes/no questions.',
    'Negate with nicht and kein correctly.',
    'Use the nominative and accusative with definite, indefinite and possessive articles.',
  ],
  skills:{reading:'Short simple texts: forms, notices, postcards, short personal descriptions.',
    writing:'Simple sentences and short personal messages; fill in a form.',
    listening:'Slow, clearly articulated everyday speech on familiar topics.',
    speaking:'Simple interaction where the partner repeats or rephrases.',
    vocabulary:'~650–900 words of concrete everyday German.',
    grammar:'Present tense, verb position, questions, negation, articles, nominative/accusative, modal verbs, separable verbs, possessives.',
    pronunciation:'Intelligible pronunciation of learned material.', conversation:'Short scripted everyday exchanges.'},
  grammarScope:['personal pronouns','sein / haben','regular present tense','strong verbs with vowel change','verb-second word order','W-questions','yes/no questions','imperative (Sie/du)','negation with nicht','negation with kein','definite and indefinite articles','noun gender','plural formation','nominative','accusative','possessive articles','modal verbs','separable verbs','prepositions of place and time (first set)','coordinating conjunctions und/aber/oder/denn','first dative exposure (mit, Personalpronomen im Dativ)'],
  vocabularyScope:['personal information','numbers, prices, dates, time','family','home and furniture','food and drink','shopping','restaurant','clothing','weather','city and transport','directions','appointments','school and work','health basics','free time'],
  communicationGoals:['Introduce yourself','Ask for and give personal information','Buy something and ask the price','Order in a restaurant','Ask for and follow directions','Make and change an appointment','Describe your day','Express likes and dislikes','Ask for help'],
  assessmentCriteria:['Accuracy of verb conjugation and verb position','Correct article and case in short sentences','Comprehension of short everyday texts','Production of 3–5 connected simple sentences'],
  prerequisites:['A0'], nextLevel:'A2',
  readiness:{ lessonCompletionPct:80, grammarMastery:0.65, vocabMastery:0.6, minSkills:{grammar:0.6, vocabulary:0.6, reading:0.5, writing:0.4} },
  targetVocabCumulative:900, examAlignment:['Goethe-Zertifikat A1','telc Deutsch A1','ÖSD Zertifikat A1'],
},
{
  id:'level_a2', level:'A2', official:true, title:'Waystage',
  description:'The learner can understand sentences and frequently used expressions related to areas of most immediate relevance, communicate in simple routine tasks, and describe in simple terms aspects of their background, immediate environment and matters of immediate need.',
  objectives:[
    'Talk about the past with the Perfekt and the common Präteritum forms.',
    'Use the dative confidently: dative verbs, dative prepositions, two-way prepositions.',
    'Join ideas with weil, dass, wenn and handle the resulting word order.',
    'Compare things with comparative and superlative forms.',
    'Write short emails, invitations, cancellations and descriptions.',
  ],
  skills:{reading:'Short practical texts: emails, ads, notices, schedules, forms, short articles.',
    writing:'Short connected texts: message, email, invitation, cancellation, description of an experience.',
    listening:'Short announcements, simple phone calls, everyday conversations.',
    speaking:'Routine exchanges requiring simple, direct exchange of information.',
    vocabulary:'~1500–2000 cumulative words.',
    grammar:'Perfekt, Präteritum of sein/haben/modals, dative, two-way prepositions, reflexives, subordinate clauses, comparison, adjective endings (introduction).',
    pronunciation:'Sentence stress and question intonation.', conversation:'Manage a problem: complaint, cancellation, doctor, housing.'},
  grammarScope:['Perfekt with haben and sein','Partizip II of weak, strong and mixed verbs','Präteritum of sein, haben and modals','dative case','dative verbs (helfen, gefallen, gehören, danken)','dative prepositions','two-way prepositions (Wechselpräpositionen)','reflexive verbs','separable vs inseparable verbs','comparative and superlative','subordinate clauses with weil, dass, wenn','indirect questions with ob','temporal expressions','adjective endings after definite/indefinite articles','Imperativ','um … zu'],
  vocabularyScope:['travel','housing','work and study','health and body','feelings','problems and complaints','services and bureaucracy','media and free time','food beyond the basics','past-time expressions'],
  communicationGoals:['Tell someone what you did','Make plans and invitations','Cancel and apologise','Describe a problem and ask for a solution','Give reasons with weil','Express opinions simply','Compare two options','Describe your flat, job or studies'],
  assessmentCriteria:['Correct auxiliary and participle in the Perfekt','Correct case after dative and two-way prepositions','Verb-final order in subordinate clauses','Coherence of a 60–80 word written text'],
  prerequisites:['A1'], nextLevel:'B1',
  readiness:{ lessonCompletionPct:80, grammarMastery:0.68, vocabMastery:0.62, minSkills:{grammar:0.62, vocabulary:0.62, reading:0.55, writing:0.5} },
  targetVocabCumulative:2000, examAlignment:['Goethe-Zertifikat A2','telc Deutsch A2','ÖSD Zertifikat A2'],
},
{
  id:'level_b1', level:'B1', official:true, title:'Threshold',
  description:'The learner can deal with most situations likely to arise while travelling, produce simple connected text on familiar topics, describe experiences, events, dreams and ambitions, and briefly give reasons and explanations for opinions and plans.',
  objectives:[
    'Hold an everyday conversation independently, including unexpected turns.',
    'Give and justify opinions, agree and disagree politely.',
    'Use relative clauses, the passive, Konjunktiv II for politeness and hypotheticals.',
    'Handle German bureaucracy, housing, work and health situations.',
    'Write structured emails, complaints and opinion texts.',
  ],
  skills:{reading:'Longer everyday and informational texts, straightforward newspaper articles, official letters.',
    writing:'Structured paragraphs, formal and informal emails, complaints, opinion texts (150–200 words).',
    listening:'Standard speech on familiar matters, radio/podcast items, longer announcements.',
    speaking:'Sustained conversation, describing experiences, giving reasons, handling problems.',
    vocabulary:'~3000–4000 cumulative words, including abstract everyday vocabulary.',
    grammar:'Relative clauses, passive, Konjunktiv II, adjective declension, genitive, connectors, indirect questions, tense consolidation.',
    pronunciation:'Clear sentence rhythm; stress for contrast and emphasis.', conversation:'Workplace, discussion, complaint, negotiation of everyday matters.'},
  grammarScope:['relative clauses (Nominativ, Akkusativ, Dativ)','Passiv Präsens and Präteritum','Konjunktiv II (würde, hätte, wäre, könnte)','full adjective declension','Genitiv','two-part connectors (entweder … oder, nicht nur … sondern auch)','subordinating conjunctions (obwohl, damit, seitdem, falls, während)','indirect questions','Präteritum in written narration','Futur I','n-Deklination','verbs with fixed prepositions','Infinitiv mit zu'],
  vocabularyScope:['work and career','education and training','housing and moving','health system','authorities and paperwork','media and internet','environment','relationships','travel and mobility','money and consumption','opinions and argument markers'],
  communicationGoals:['Explain a problem to an authority','Take part in a discussion','Justify an opinion','Describe an experience in detail','Write a formal complaint','Conduct a job-related conversation','Understand and give instructions'],
  assessmentCriteria:['Correct relative pronoun and case','Appropriate register in formal writing','Coherent paragraph structure with connectors','Spontaneous speech with limited hesitation'],
  prerequisites:['A2'], nextLevel:'B2',
  readiness:{ lessonCompletionPct:80, grammarMastery:0.7, vocabMastery:0.65, minSkills:{grammar:0.65, vocabulary:0.65, reading:0.6, writing:0.55} },
  targetVocabCumulative:4000, examAlignment:['Goethe-Zertifikat B1','telc Deutsch B1','ÖSD Zertifikat B1','DTZ (telc Deutsch-Test für Zuwanderer)'],
},
{
  id:'level_b2', level:'B2', official:true, title:'Vantage',
  description:'The learner can understand the main ideas of complex text on both concrete and abstract topics, interact with a degree of fluency and spontaneity, and produce clear, detailed text on a wide range of subjects, explaining a viewpoint and the advantages and disadvantages of options.',
  objectives:[
    'Argue a position with structured reasoning and concessions.',
    'Use nominalisation, participial constructions and the full passive system.',
    'Operate in professional German: meetings, emails, presentations, reports.',
    'Read and summarise informational and journalistic texts.',
  ],
  skills:{reading:'Articles, reports, commentary, specialised texts in a familiar field.',
    writing:'Argumentative essays, formal correspondence, summaries, reports (200–300 words).',
    listening:'Extended speech, lectures, discussions, most broadcast material.',
    speaking:'Fluent, spontaneous interaction; structured presentation of an argument.',
    vocabulary:'~5000–7000 cumulative words including abstract and professional lexis.',
    grammar:'Passive with modals, Zustandspassiv, Partizipialattribute, nominalisation, Konjunktiv I and II, complex connectors, formal register.',
    pronunciation:'Natural rhythm; conscious use of stress for argumentation.', conversation:'Debate, negotiation, professional discussion.'},
  grammarScope:['Passiv (all tenses, with modals, Zustandspassiv)','Konjunktiv I for reported speech','Konjunktiv II (irreal, Wunsch, höfliche Bitte)','Partizip I and II as attributes','Nominalisierung and Verbalisierung','erweiterte Infinitivsätze','Konnektoren (dennoch, folglich, zumal, sofern)','Präpositionaladverbien (darauf, womit)','Passiversatzformen (sich lassen, sein + zu + Infinitiv)','Modalverben in subjektiver Bedeutung','Nebensatzverkürzungen'],
  vocabularyScope:['society and politics as language content','economy and work','science and technology','environment and sustainability','education systems','media and communication','culture and art','argument and discourse vocabulary'],
  communicationGoals:['Present and defend an argument','Chair or contribute to a meeting','Write a formal report','Summarise a complex text','Express nuanced agreement and disagreement','Give a short presentation'],
  assessmentCriteria:['Argument structure and coherence','Register consistency','Range and precision of connectors','Grammatical accuracy under spontaneous conditions'],
  prerequisites:['B1'], nextLevel:'C1',
  readiness:{ lessonCompletionPct:80, grammarMastery:0.72, vocabMastery:0.68, minSkills:{grammar:0.68, vocabulary:0.68, reading:0.65, writing:0.6} },
  targetVocabCumulative:7000, examAlignment:['Goethe-Zertifikat B2','telc Deutsch B2','ÖSD Zertifikat B2','TestDaF (TDN 3–4)'],
},
{
  id:'level_c1', level:'C1', official:true, title:'Effective Operational Proficiency',
  description:'The learner can understand demanding, longer texts and recognise implicit meaning, express ideas fluently and spontaneously without much obvious searching for expressions, and use language flexibly and effectively for social, academic and professional purposes.',
  objectives:[
    'Write academic and professional German with appropriate register.',
    'Understand implicit meaning, irony and attitude in demanding texts.',
    'Use idioms, collocations and discourse markers accurately.',
    'Structure long spoken and written contributions clearly.',
  ],
  skills:{reading:'Academic articles, literary prose, legal and administrative texts.',
    writing:'Academic essays, professional reports, structured argumentation (300–450 words).',
    listening:'Fast native speech, lectures, dialect-coloured standard speech.',
    speaking:'Fluent, precise, register-appropriate contributions; presentations.',
    vocabulary:'~8000–10000 cumulative words including abstract, academic and idiomatic lexis.',
    grammar:'Full command of complex syntax, Funktionsverbgefüge, advanced connectors, stylistic variation.',
    pronunciation:'Natural, flexible intonation; conscious stylistic variation.', conversation:'Academic discussion, professional negotiation, nuanced disagreement.'},
  grammarScope:['Funktionsverbgefüge (in Betracht ziehen, zur Verfügung stellen)','erweiterte Partizipialattribute','Konjunktiv I and II in full','Nominalstil vs Verbalstil','Textkohäsion and Konnektoren','Modalpartikeln (doch, ja, mal, eben, wohl)','subjektive Modalverben','Passiversatz','Ellipsen and Inversionen for emphasis','Präpositionen mit Genitiv (aufgrund, hinsichtlich, mittels)'],
  vocabularyScope:['academic discourse','professional specialisation','abstract concepts','idioms and fixed expressions','collocations','stylistic and register markers','hedging and qualification'],
  communicationGoals:['Write an academic essay','Deliver a structured presentation','Argue a nuanced position','Summarise and critique a demanding text','Adapt register to audience'],
  assessmentCriteria:['Register control','Idiomatic accuracy','Cohesion across long texts','Precision of abstract vocabulary'],
  prerequisites:['B2'], nextLevel:'C2',
  readiness:{ lessonCompletionPct:80, grammarMastery:0.75, vocabMastery:0.7, minSkills:{grammar:0.7, vocabulary:0.72, reading:0.7, writing:0.65} },
  targetVocabCumulative:10000, examAlignment:['Goethe-Zertifikat C1','telc Deutsch C1','ÖSD Zertifikat C1','TestDaF (TDN 5)','DSH-2'],
},
{
  id:'level_c2', level:'C2', official:true, title:'Mastery',
  description:'The learner can understand with ease virtually everything heard or read, summarise information from different spoken and written sources, and express themselves spontaneously, very fluently and precisely, differentiating finer shades of meaning even in complex situations.',
  objectives:[
    'Control nuance, connotation and register deliberately.',
    'Reproduce and reshape arguments from multiple sources.',
    'Use idiomatic and figurative German precisely and appropriately.',
    'Write in distinct styles: journalistic, academic, literary, administrative.',
  ],
  skills:{reading:'Any text type, including literary, satirical and highly specialised material.',
    writing:'Publication-quality argumentation, stylistic variation, précis.',
    listening:'Any native speech, including regional colouring and fast interaction.',
    speaking:'Precise, fluent, stylistically controlled speech.',
    vocabulary:'Nuanced, specialised and figurative lexis; conscious synonym differentiation.',
    grammar:'Full stylistic command; deviation from the norm used deliberately.',
    pronunciation:'Near-native rhythm and expressive intonation.', conversation:'Any professional or social register.'},
  grammarScope:['stilistische Varianten der Wortstellung','Archaismen and gehobener Stil','Konjunktiv in indirekter Rede über mehrere Sätze','komplexe Attributketten','Rhetorische Figuren','Textsortenspezifische Syntax'],
  vocabularyScope:['synonym differentiation','connotation and register','idioms and proverbs','Fachsprache','journalistic and literary lexis','Modalpartikel nuance'],
  communicationGoals:['Summarise conflicting sources into one coherent argument','Write in a chosen style deliberately','Detect and use irony, understatement and implicature','Interpret literary and journalistic nuance'],
  assessmentCriteria:['Precision of word choice','Stylistic appropriateness','Handling of implicit meaning','Consistency across long production'],
  prerequisites:['C1'], nextLevel:null,
  readiness:{ lessonCompletionPct:80, grammarMastery:0.8, vocabMastery:0.75, minSkills:{grammar:0.75, vocabulary:0.78, reading:0.75, writing:0.7} },
  targetVocabCumulative:14000, examAlignment:['Goethe-Zertifikat C2: Großes Deutsches Sprachdiplom','telc Deutsch C2','ÖSD Zertifikat C2'],
},
];

if(typeof module !== 'undefined' && module.exports){ module.exports = { LEVEL_META }; }
