/* ============================================================
   VOCABULARY — A0 / A1 / A2 (spec §16, §17)
   Authored in the compact DSL (see src/core/dsl.js). Every line
   is hand-written German: gender, plural, verb forms and the
   example sentence are checked, not generated.
   Groups carry level + topic; the parser expands each line into
   a full vocabulary record with a stable id (v_<lemma>).
   ============================================================ */
const VOCAB_CORE = (() => {
  const D = (typeof DSL !== 'undefined') ? DSL : require('../core/dsl.js');
  const out = [];
  const g = (level, topic, lines) => { out.push(...D.vocab(level, topic, lines)); };

  /* ================= A0 ================= */
  g('A0','alphabet',[
    "n|Buchstabe|der|die Buchstaben|letter (of the alphabet)|Das Wort hat fünf Buchstaben.=The word has five letters.",
    "n|Wort|das|die Wörter|word|Wie schreibt man dieses Wort?=How do you write this word?",
    "n|Umlaut|der|die Umlaute|umlaut|Ä, ö und ü sind Umlaute.=Ä, ö and ü are umlauts.",
    "v|buchstabieren|buchstabiere/buchstabierst/buchstabiert|hat buchstabiert|to spell|Buchstabieren Sie bitte Ihren Namen.=Please spell your name.",
    "v|schreiben|schreibe/schreibst/schreibt|hat geschrieben|to write|Ich schreibe eine E-Mail.=I am writing an email.",
    "v|lesen|lese/liest/liest|hat gelesen|to read|Sie liest ein Buch.=She is reading a book.",
    "v|sprechen|spreche/sprichst/spricht|hat gesprochen|to speak|Ich spreche ein bisschen Deutsch.=I speak a little German.",
    "v|!kommen|komme/kommst/kommt|ist gekommen|to come|Ich komme aus Pakistan.=I come from Pakistan.",
  ]);
  g('A0','classroom',[
    "p|Wie bitte?|Pardon? / Sorry?|Wie bitte? Das habe ich nicht verstanden.=Pardon? I did not understand that.",
    "p|Ich verstehe nicht.|I do not understand.|Entschuldigung, ich verstehe nicht.=Sorry, I do not understand.",
    "p|Können Sie das wiederholen?|Can you repeat that?|Können Sie das bitte wiederholen?=Can you please repeat that?|+id:v_konnen_sie_das_wiederholen",
    "p|Sprechen Sie bitte langsamer.|Please speak more slowly.|Sprechen Sie bitte langsamer.=Please speak more slowly.",
    "p|Wie sagt man das auf Deutsch?|How do you say that in German?|Wie sagt man \"table\" auf Deutsch?=How do you say \"table\" in German?",
    "p|Was bedeutet das?|What does that mean?|Was bedeutet \"Rechnung\"?=What does \"Rechnung\" mean?",
    "n|Frage|die|die Fragen|question|Ich habe eine Frage.=I have a question.",
    "n|Antwort|die|die Antworten|answer|Die Antwort ist richtig.=The answer is correct.",
    "n|Übung|die|die Übungen|exercise|Machen Sie bitte Übung drei.=Please do exercise three.",
    "a|richtig||correct|Das ist richtig.=That is correct.",
    "a|falsch||wrong|Die Antwort ist falsch.=The answer is wrong.",
  ]);
  g('A0','colours',[
    "a|rot||red|Der Apfel ist rot.=The apple is red.",
    "a|blau||blue|Der Himmel ist blau.=The sky is blue.",
    "a|grün||green|Das Auto ist grün.=The car is green.",
    "a|gelb||yellow|Die Banane ist gelb.=The banana is yellow.",
    "a|schwarz|schwärzer/am schwärzesten|black|Meine Jacke ist schwarz.=My jacket is black.",
    "a|weiß|weißer/am weißesten|white|Das Hemd ist weiß.=The shirt is white.",
    "n|Farbe|die|die Farben|colour|Welche Farbe hat dein Auto?=What colour is your car?",
  ]);
  g('A0','days',[
    "n|Montag|der|die Montage|Monday|Am Montag arbeite ich.=On Monday I work.",
    "n|Dienstag|der|die Dienstage|Tuesday|Der Kurs ist am Dienstag.=The course is on Tuesday.",
    "n|Mittwoch|der|die Mittwoche|Wednesday|Am Mittwoch habe ich einen Termin.=On Wednesday I have an appointment.",
    "n|Donnerstag|der|die Donnerstage|Thursday|Donnerstag passt mir gut.=Thursday suits me well.",
    "n|Freitag|der|die Freitage|Friday|Am Freitag ist der Laden bis acht offen.=On Friday the shop is open until eight.",
    "n|Samstag|der|die Samstage|Saturday|Am Samstag kaufe ich ein.=On Saturday I go shopping.",
    "n|Sonntag|der|die Sonntage|Sunday|Am Sonntag sind die Geschäfte zu.=On Sunday the shops are closed.",
    "n|Wochenende|das|die Wochenenden|weekend|Schönes Wochenende!=Have a nice weekend!",
  ]);

  /* ================= A1 ================= */
  g('A1','personal',[
    "n|Vorname|der|die Vornamen|first name|Mein Vorname ist Amina.=My first name is Amina.",
    "n|Nachname|der|die Nachnamen|surname|Wie ist Ihr Nachname?=What is your surname?",
    "n|Adresse|die|die Adressen|address|Meine Adresse ist Hauptstraße 12.=My address is Hauptstraße 12.",
    "n|Straße|die|die Straßen|street|Ich wohne in der Goethestraße.=I live on Goethestraße.",
    "n|Hausnummer|die|die Hausnummern|house number|Die Hausnummer ist 24b.=The house number is 24b.",
    "n|Postleitzahl|die|die Postleitzahlen|postcode|Die Postleitzahl von Berlin-Mitte ist 10115.=The postcode for Berlin-Mitte is 10115.",
    "n|Telefonnummer|die|die Telefonnummern|telephone number|Wie ist deine Telefonnummer?=What is your phone number?",
    "n|Handy|das|die Handys|mobile phone|Mein Handy ist kaputt.=My mobile phone is broken.",
    "n|E-Mail|die|die E-Mails|email|Ich schreibe Ihnen eine E-Mail.=I will write you an email.",
    "n|Land|das|die Länder|country|Aus welchem Land kommst du?=Which country are you from?",
    "n|Stadt|die|die Städte|city|München ist eine große Stadt.=Munich is a big city.",
    "n|Sprache|die|die Sprachen|language|Ich spreche drei Sprachen.=I speak three languages.",
    "n|Beruf|der|die Berufe|occupation|Was sind Sie von Beruf?=What is your occupation?",
    "n|Geburtsdatum|das|die Geburtsdaten|date of birth|Mein Geburtsdatum ist der 3. Mai 1998.=My date of birth is 3 May 1998.",
    "v|heißen|heiße/heißt/heißt|hat geheißen|to be called|Ich heiße Karim.=My name is Karim.",
    "v|!sein|bin/bist/ist|ist gewesen|to be|Ich bin Student.=I am a student.",
    "v|wohnen|wohne/wohnst/wohnt|hat gewohnt|to live, to reside|Wir wohnen in Hamburg.=We live in Hamburg.",
    "v|leben|lebe/lebst/lebt|hat gelebt|to live|Sie lebt seit 2019 in Deutschland.=She has lived in Germany since 2019.",
    "v|verstehen|verstehe/verstehst/versteht|hat verstanden|to understand|Ich verstehe die Frage nicht.=I do not understand the question.",
    "a|verheiratet||married|Ich bin verheiratet.=I am married.",
    "a|ledig||single, unmarried|Er ist ledig.=He is single.",
  ]);
  g('A1','numbers',[
    "n|Nummer|die|die Nummern|number|Welche Nummer hat das Haus?=What number is the house?",
    "n|Zahl|die|die Zahlen|number, figure|Schreiben Sie die Zahl in Worten.=Write the number in words.",
    "n|Preis|der|die Preise|price|Der Preis ist zu hoch.=The price is too high.",
    "n|Euro|der|die Euro|euro|Das kostet zwölf Euro.=That costs twelve euros.",
    "n|Cent|der|die Cent|cent|Das Brot kostet ein Euro fünfzig.=The bread costs one euro fifty.",
    "n|Geld|das|—|money|Ich habe kein Geld dabei.=I have no money on me.",
    "v|kosten|koste/kostest/kostet|hat gekostet|to cost|Wie viel kostet die Fahrkarte?=How much does the ticket cost?",
    "v|zahlen|zahle/zahlst/zahlt|hat gezahlt|to pay|Ich zahle mit Karte.=I pay by card.",
    "v|bezahlen|bezahle/bezahlst/bezahlt|hat bezahlt|to pay for|Ich habe die Rechnung bezahlt.=I paid the bill.",
    "a|teuer|teurer/am teuersten|expensive|Die Wohnung ist zu teuer.=The flat is too expensive.",
    "a|billig|billiger/am billigsten|cheap|Das Gemüse ist hier billig.=The vegetables are cheap here.",
    "a|günstig|günstiger/am günstigsten|reasonably priced|Ich suche ein günstiges Zimmer.=I am looking for a reasonably priced room.",
  ]);
  g('A1','time',[
    "n|Uhrzeit|die|die Uhrzeiten|time of day|Wie ist die Uhrzeit?=What time is it?",
    "n|Zeit|die|die Zeiten|time|Ich habe heute keine Zeit.=I have no time today.",
    "n|Minute|die|die Minuten|minute|Der Bus kommt in fünf Minuten.=The bus comes in five minutes.",
    "n|Stunde|die|die Stunden|hour|Der Kurs dauert zwei Stunden.=The course lasts two hours.",
    "n|Monat|der|die Monate|month|Nächsten Monat ziehe ich um.=Next month I am moving.",
    "n|Morgen|der|die Morgen|morning|Am Morgen trinke ich Tee.=In the morning I drink tea.",
    "n|Vormittag|der|die Vormittage|late morning|Am Vormittag habe ich Unterricht.=In the late morning I have class.",
    "n|Mittag|der|die Mittage|midday|Zu Mittag esse ich warm.=At midday I eat a hot meal.",
    "n|Nachmittag|der|die Nachmittage|afternoon|Am Nachmittag arbeite ich.=In the afternoon I work.",
    "n|Abend|der|die Abende|evening|Am Abend sehe ich fern.=In the evening I watch TV.",
    "n|Nacht|die|die Nächte|night|In der Nacht ist es ruhig.=At night it is quiet.",
    "w|heute|adv|today|Heute habe ich frei.=Today I have a day off.",
    "w|morgen|adv|tomorrow|Morgen fahre ich nach Köln.=Tomorrow I am going to Cologne.|+id:v_morgen_adv",
    "w|gestern|adv|yesterday|Gestern war ich krank.=Yesterday I was ill.",
    "w|jetzt|adv|now|Ich muss jetzt gehen.=I have to go now.",
    "w|später|adv|later|Wir telefonieren später.=We will talk later.",
    "w|früh|adv|early|Ich stehe früh auf.=I get up early.",
    "w|spät|adv|late|Es ist schon spät.=It is already late.",
    "n|Januar|der|—|January|Im Januar ist es kalt.=In January it is cold.",
    "n|Juli|der|—|July|Im Juli fahren wir ans Meer.=In July we go to the seaside.",
    "n|Dezember|der|—|December|Im Dezember schneit es oft.=In December it often snows.",
  ]);
  g('A1','family',[
    "n|Eltern|die|die Eltern|parents|Meine Eltern wohnen in Kabul.=My parents live in Kabul.",
    "n|Geschwister|die|die Geschwister|siblings|Ich habe drei Geschwister.=I have three siblings.",
    "n|Großvater|der|die Großväter|grandfather|Mein Großvater ist achtzig.=My grandfather is eighty.",
    "n|Großmutter|die|die Großmütter|grandmother|Meine Großmutter kocht sehr gut.=My grandmother cooks very well.",
    "n|Onkel|der|die Onkel|uncle|Mein Onkel lebt in Wien.=My uncle lives in Vienna.",
    "n|Tante|die|die Tanten|aunt|Meine Tante besucht uns oft.=My aunt visits us often.",
    "n|Freund|der|die Freunde|friend (m.), boyfriend|Mein Freund hilft mir beim Lernen.=My friend helps me study.",
    "n|Freundin|die|die Freundinnen|friend (f.), girlfriend|Meine Freundin arbeitet im Krankenhaus.=My friend works in the hospital.",
    "n|Baby|das|die Babys|baby|Das Baby schläft schon.=The baby is already asleep.",
    "n|Kind|das|die Kinder|child|Das Kind spielt im Garten.=The child is playing in the garden.",
    "a|jung|jünger/am jüngsten|young|Meine Schwester ist noch jung.=My sister is still young.",
    "v|besuchen|besuche/besuchst/besucht|hat besucht|to visit|Ich besuche meine Familie.=I visit my family.",
    "v|heiraten|heirate/heiratest/heiratet|hat geheiratet|to marry|Sie heiraten im Sommer.=They are getting married in the summer.",
  ]);
  g('A1','home',[
    "n|Wohnung|die|die Wohnungen|flat, apartment|Die Wohnung hat drei Zimmer.=The flat has three rooms.",
    "n|Haus|das|die Häuser|house|Das Haus ist alt, aber schön.=The house is old but beautiful.",
    "n|Zimmer|das|die Zimmer|room|Mein Zimmer ist klein.=My room is small.",
    "n|Küche|die|die Küchen|kitchen|Die Küche ist neu.=The kitchen is new.",
    "n|Bad|das|die Bäder|bathroom|Das Bad ist gleich rechts.=The bathroom is right there on the right.",
    "n|Schlafzimmer|das|die Schlafzimmer|bedroom|Das Schlafzimmer liegt hinten.=The bedroom is at the back.",
    "n|Balkon|der|die Balkone|balcony|Die Wohnung hat einen Balkon.=The flat has a balcony.",
    "n|Tisch|der|die Tische|table|Das Buch liegt auf dem Tisch.=The book is on the table.",
    "n|Stuhl|der|die Stühle|chair|Der Stuhl ist bequem.=The chair is comfortable.",
    "n|Bett|das|die Betten|bed|Das Bett steht am Fenster.=The bed stands by the window.",
    "n|Schrank|der|die Schränke|cupboard, wardrobe|Die Kleidung ist im Schrank.=The clothes are in the wardrobe.",
    "n|Fenster|das|die Fenster|window|Bitte mach das Fenster zu.=Please close the window.",
    "n|Tür|die|die Türen|door|Die Tür ist offen.=The door is open.",
    "n|Miete|die|die Mieten|rent|Die Miete ist hoch.=The rent is high.",
    "v|*umziehen|ziehe um/ziehst um/zieht um|ist umgezogen|to move house|Wir ziehen nächsten Monat um.=We are moving next month.",
    "v|mieten|miete/mietest/mietet|hat gemietet|to rent|Wir mieten eine Wohnung.=We are renting a flat.",
    "a|gemütlich|gemütlicher/am gemütlichsten|cosy|Das Zimmer ist gemütlich.=The room is cosy.",
    "a|hell|heller/am hellsten|bright|Die Küche ist sehr hell.=The kitchen is very bright.",
    "a|dunkel|dunkler/am dunkelsten|dark|Das Bad ist ein bisschen dunkel.=The bathroom is a bit dark.",
  ]);
  g('A1','food',[
    "n|Frühstück|das|die Frühstücke|breakfast|Zum Frühstück esse ich Brot.=For breakfast I eat bread.",
    "n|Brot|das|die Brote|bread|Ich kaufe ein frisches Brot.=I am buying a fresh loaf of bread.",
    "n|Mittagessen|das|die Mittagessen|lunch|Das Mittagessen ist um zwölf.=Lunch is at twelve.",
    "n|Abendessen|das|die Abendessen|dinner|Wir kochen das Abendessen zusammen.=We cook dinner together.",
    "n|Milch|die|—|milk|Ich trinke Kaffee mit Milch.=I drink coffee with milk.",
    "n|Tee|der|die Tees|tea|Möchtest du einen Tee?=Would you like a tea?",
    "n|Reis|der|—|rice|Wir essen oft Reis.=We often eat rice.",
    "n|Fleisch|das|—|meat|Ich esse kein Fleisch.=I do not eat meat.",
    "n|Gemüse|das|—|vegetables|Gemüse ist gesund.=Vegetables are healthy.",
    "n|Obst|das|—|fruit|Im Sommer kaufe ich viel Obst.=In summer I buy a lot of fruit.",
    "n|Suppe|die|die Suppen|soup|Die Suppe ist heiß.=The soup is hot.",
    "n|Salz|das|—|salt|Kannst du mir das Salz geben?=Can you pass me the salt?",
    "n|Zucker|der|—|sugar|Nimmst du Zucker?=Do you take sugar?",
    "v|kochen|koche/kochst/kocht|hat gekocht|to cook|Meine Mutter kocht gern.=My mother likes cooking.",
    "v|bestellen|bestelle/bestellst/bestellt|hat bestellt|to order|Ich bestelle eine Suppe.=I am ordering a soup.",
    "v|probieren|probiere/probierst/probiert|hat probiert|to try, to taste|Probier mal den Kuchen!=Try the cake!",
    "a|lecker|leckerer/am leckersten|tasty|Das Essen war sehr lecker.=The food was very tasty.",
    "a|hungrig|hungriger/am hungrigsten|hungry|Ich bin hungrig.=I am hungry.",
    "a|satt||full (not hungry)|Danke, ich bin satt.=Thank you, I am full.",
  ]);
  g('A1','shopping',[
    "n|Geschäft|das|die Geschäfte|shop|Das Geschäft öffnet um neun.=The shop opens at nine.",
    "n|Supermarkt|der|die Supermärkte|supermarket|Ich kaufe im Supermarkt ein.=I shop at the supermarket.",
    "v|kaufen|kaufe/kaufst/kauft|hat gekauft|to buy|Ich kaufe einen Apfel.=I am buying an apple.",
    "n|Bäckerei|die|die Bäckereien|bakery|Die Bäckerei ist gleich um die Ecke.=The bakery is just around the corner.",
    "n|Markt|der|die Märkte|market|Am Samstag gehe ich auf den Markt.=On Saturday I go to the market.",
    "n|Kasse|die|die Kassen|checkout, till|Bitte zahlen Sie an der Kasse.=Please pay at the checkout.",
    "n|Quittung|die|die Quittungen|receipt|Brauchen Sie eine Quittung?=Do you need a receipt?",
    "n|Tasche|die|die Taschen|bag|Haben Sie eine Tasche?=Do you have a bag?",
    "v|*einkaufen|kaufe ein/kaufst ein/kauft ein|hat eingekauft|to shop|Ich kaufe im Supermarkt ein.=I shop at the supermarket.",
    "v|brauchen|brauche/brauchst/braucht|hat gebraucht|to need|Ich brauche noch Milch.=I still need milk.",
    "v|suchen|suche/suchst/sucht|hat gesucht|to look for|Ich suche eine Jacke.=I am looking for a jacket.",
    "v|finden|finde/findest/findet|hat gefunden|to find|Ich finde den Preis gut.=I think the price is good.",
    "p|Was kostet das?|How much is that?|Entschuldigung, was kostet das?=Excuse me, how much is that?",
    "p|Ich hätte gern …|I would like …|Ich hätte gern ein Kilo Äpfel.=I would like a kilo of apples.",
  ]);
  g('A1','clothing',[
    "n|Kleidung|die|—|clothing|Die Kleidung ist im Schrank.=The clothes are in the wardrobe.",
    "n|Hose|die|die Hosen|trousers|Die Hose ist zu lang.=The trousers are too long.",
    "n|Hemd|das|die Hemden|shirt|Das Hemd passt gut.=The shirt fits well.",
    "n|Jacke|die|die Jacken|jacket|Nimm eine Jacke mit, es ist kalt.=Take a jacket, it is cold.",
    "n|Schuh|der|die Schuhe|shoe|Die Schuhe sind zu klein.=The shoes are too small.",
    "n|Größe|die|die Größen|size|Welche Größe haben Sie?=What size are you?",
    "v|*anziehen|ziehe an/ziehst an/zieht an|hat angezogen|to put on (clothes)|Zieh eine warme Jacke an!=Put on a warm jacket!",
    "v|passen|passe/passt/passt|hat gepasst|to fit, to suit|Der Termin passt mir gut.=The appointment suits me well.",
    "v|tragen|trage/trägst/trägt|hat getragen|to wear, to carry|Sie trägt ein blaues Kleid.=She is wearing a blue dress.",
  ]);
  g('A1','city',[
    "n|Bahnhof|der|die Bahnhöfe|train station|Der Bahnhof ist in der Nähe.=The station is nearby.",
    "n|Haltestelle|die|die Haltestellen|stop (bus/tram)|Die Haltestelle ist dort drüben.=The stop is over there.",
    "n|Bus|der|die Busse|bus|Der Bus fährt alle zehn Minuten.=The bus runs every ten minutes.",
    "n|Zug|der|die Züge|train|Der Zug hat Verspätung.=The train is delayed.",
    "n|Fahrkarte|die|die Fahrkarten|ticket|Eine Fahrkarte nach Köln, bitte.=One ticket to Cologne, please.",
    "n|Apotheke|die|die Apotheken|pharmacy|Die Apotheke hat bis achtzehn Uhr offen.=The pharmacy is open until six.",
    "n|Post|die|—|post office|Ich gehe zur Post.=I am going to the post office.",
    "n|Bank|die|die Banken|bank|Die Bank ist neben dem Rathaus.=The bank is next to the town hall.",
    "n|Rathaus|das|die Rathäuser|town hall|Das Rathaus ist am Marktplatz.=The town hall is on the market square.",
    "n|Krankenhaus|das|die Krankenhäuser|hospital|Sie arbeitet im Krankenhaus.=She works in the hospital.",
    "n|Park|der|die Parks|park|Im Park kann man gut laufen.=You can run well in the park.",
    "v|!fahren|fahre/fährst/fährt|ist gefahren|to travel, to drive|Ich fahre mit dem Bus.=I travel by bus.",
    "v|!gehen|gehe/gehst/geht|ist gegangen|to go, to walk|Ich gehe zu Fuß.=I go on foot.",
    "v|!laufen|laufe/läufst/läuft|ist gelaufen|to run, to walk|Wir laufen jeden Morgen.=We run every morning.",
    "w|links|adv|left|Gehen Sie links.=Go left.",
    "w|rechts|adv|right|Die Apotheke ist rechts.=The pharmacy is on the right.",
    "w|geradeaus|adv|straight ahead|Gehen Sie geradeaus bis zur Kreuzung.=Go straight ahead to the crossroads.",
    "p|Wie komme ich zum Bahnhof?|How do I get to the station?|Entschuldigung, wie komme ich zum Bahnhof?=Excuse me, how do I get to the station?",
  ]);
  g('A1','appointments',[
    "n|Termin|der|die Termine|appointment|Ich habe morgen einen Termin.=I have an appointment tomorrow.",
    "n|Kalender|der|die Kalender|calendar|Ich schreibe es in den Kalender.=I will write it in the calendar.",
    "n|Praxis|die|die Praxen|doctor's practice|Die Praxis ist heute geschlossen.=The practice is closed today.",
    "v|*absagen|sage ab/sagst ab/sagt ab|hat abgesagt|to cancel|Ich muss den Termin absagen.=I have to cancel the appointment.",
    "v|*anrufen|rufe an/rufst an/ruft an|hat angerufen|to call (phone)|Ich rufe dich morgen an.=I will call you tomorrow.",
    "v|*verschieben|verschiebe/verschiebst/verschiebt|hat verschoben|to postpone|Können wir den Termin verschieben?=Can we postpone the appointment?",
    "v|warten|warte/wartest/wartet|hat gewartet|to wait|Ich warte seit zwanzig Minuten.=I have been waiting for twenty minutes.",
    "p|Passt Ihnen Donnerstag?|Does Thursday suit you?|Passt Ihnen Donnerstag um zehn?=Does Thursday at ten suit you?",
  ]);
  g('A1','work-school',[
    "n|Arbeit|die|die Arbeiten|work|Die Arbeit macht mir Spaß.=I enjoy the work.",
    "n|Firma|die|die Firmen|company|Die Firma hat dreißig Mitarbeiter.=The company has thirty employees.",
    "n|Kollege|der|die Kollegen|colleague (m.)|Mein Kollege hilft mir oft.=My colleague often helps me.",
    "n|Chef|der|die Chefs|boss|Der Chef ist heute nicht da.=The boss is not here today.",
    "n|Schule|die|die Schulen|school|Die Kinder gehen zur Schule.=The children go to school.",
    "n|Kurs|der|die Kurse|course|Der Kurs beginnt im September.=The course starts in September.",
    "n|Lehrer|der|die Lehrer|teacher (m.)|Der Lehrer erklärt die Grammatik.=The teacher explains the grammar.",
    "n|Hausaufgabe|die|die Hausaufgaben|homework|Ich mache jeden Tag Hausaufgaben.=I do homework every day.",
    "v|arbeiten|arbeite/arbeitest/arbeitet|hat gearbeitet|to work|Ich arbeite von neun bis fünf.=I work from nine to five.",
    "v|lernen|lerne/lernst/lernt|hat gelernt|to learn, to study|Ich lerne jeden Abend Deutsch.=I study German every evening.",
    "v|studieren|studiere/studierst/studiert|hat studiert|to study (at university)|Sie studiert Medizin.=She studies medicine.",
    "v|*anfangen|fange an/fängst an/fängt an|hat angefangen|to begin|Der Unterricht fängt um acht an.=The lesson begins at eight.",
  ]);
  g('A1','health',[
    "n|Arzt|der|die Ärzte|doctor (m.)|Ich gehe morgen zum Arzt.=I am going to the doctor tomorrow.",
    "n|Ärztin|die|die Ärztinnen|doctor (f.)|Die Ärztin hat mir ein Rezept gegeben.=The doctor gave me a prescription.",
    "n|Schmerz|der|die Schmerzen|pain|Ich habe Schmerzen im Rücken.=I have pain in my back.",
    "n|Kopf|der|die Köpfe|head|Mein Kopf tut weh.=My head hurts.",
    "n|Bauch|der|die Bäuche|stomach, belly|Mir tut der Bauch weh.=My stomach hurts.",
    "n|Medikament|das|die Medikamente|medication|Nehmen Sie das Medikament dreimal täglich.=Take the medication three times a day.",
    "a|krank|kränker/am kränksten|ill|Ich bin seit gestern krank.=I have been ill since yesterday.",
    "a|gesund|gesünder/am gesündesten|healthy|Obst ist gesund.=Fruit is healthy.",
    "a|müde|müder/am müdesten|tired|Ich bin sehr müde.=I am very tired.",
    "p|Mir geht es nicht gut.|I am not feeling well.|Ich bleibe zu Hause, mir geht es nicht gut.=I am staying home, I am not feeling well.",
  ]);
  g('A1','weather',[
    "n|Wetter|das|—|weather|Wie ist das Wetter heute?=What is the weather like today?",
    "n|Regen|der|—|rain|Bei Regen bleibe ich zu Hause.=When it rains I stay at home.",
    "n|Schnee|der|—|snow|Im Winter liegt viel Schnee.=In winter there is a lot of snow.",
    "n|Sonne|die|die Sonnen|sun|Die Sonne scheint.=The sun is shining.",
    "a|warm|wärmer/am wärmsten|warm|Heute ist es warm.=Today it is warm.",
    "a|kalt|kälter/am kältesten|cold|Im Januar ist es sehr kalt.=In January it is very cold.",
    "v|regnen|—/—/regnet|hat geregnet|to rain|Es regnet seit heute Morgen.=It has been raining since this morning.",
    "v|scheinen|scheine/scheinst/scheint|hat geschienen|to shine|Die Sonne scheint heute.=The sun is shining today.",
  ]);
  g('A1','freetime',[
    "n|Freizeit|die|—|free time|In meiner Freizeit lese ich.=In my free time I read.",
    "n|Sport|der|—|sport|Ich mache dreimal pro Woche Sport.=I do sport three times a week.",
    "n|Musik|die|—|music|Ich höre gern Musik.=I like listening to music.",
    "n|Film|der|die Filme|film|Der Film war sehr gut.=The film was very good.",
    "n|Buch|das|die Bücher|book|Ich lese gerade ein Buch.=I am reading a book right now.",
    "v|spielen|spiele/spielst/spielt|hat gespielt|to play|Die Kinder spielen im Park.=The children are playing in the park.",
    "v|hören|höre/hörst/hört|hat gehört|to hear, to listen|Ich höre Musik.=I listen to music.",
    "v|!schwimmen|schwimme/schwimmst/schwimmt|ist geschwommen|to swim|Wir schwimmen im Sommer oft.=We often swim in the summer.",
    "v|*fernsehen|sehe fern/siehst fern/sieht fern|hat ferngesehen|to watch TV|Abends sehe ich fern.=In the evening I watch TV.",
    "v|*aufstehen|stehe auf/stehst auf/steht auf|ist aufgestanden|to get up|Ich stehe um sechs Uhr auf.=I get up at six o'clock.",
    "w|immer|adv|always|Ich trinke immer Kaffee.=I always drink coffee.",
    "w|oft|adv|often|Ich fahre oft mit dem Bus.=I often travel by bus.",
    "w|manchmal|adv|sometimes|Manchmal koche ich selbst.=Sometimes I cook myself.",
    "w|nie|adv|never|Ich trinke nie Alkohol.=I never drink alcohol.",
    "v|*mitkommen|komme mit/kommst mit/kommt mit|ist mitgekommen|to come along|Kommst du mit?=Are you coming along?",
    "w|gern|adv|gladly, with pleasure|Ich koche gern.=I like cooking.",
    "w|lieber|adv|preferably, rather|Ich trinke lieber Tee.=I prefer drinking tea.",
  ]);
  g('A1','basics',[
    "v|geben|gebe/gibst/gibt|hat gegeben|to give|Gib mir bitte das Buch.=Please give me the book.",
    "v|nehmen|nehme/nimmst/nimmt|hat genommen|to take|Ich nehme den Bus.=I take the bus.",
    "v|sehen|sehe/siehst/sieht|hat gesehen|to see|Ich sehe dich morgen.=I will see you tomorrow.",
    "v|sagen|sage/sagst/sagt|hat gesagt|to say|Was hast du gesagt?=What did you say?",
    "v|fragen|frage/fragst/fragt|hat gefragt|to ask|Darf ich etwas fragen?=May I ask something?",
    "v|antworten|antworte/antwortest/antwortet|hat geantwortet|to answer|Er antwortet mir nicht.=He does not answer me.",
    "v|helfen|helfe/hilfst/hilft|hat geholfen|to help|Kannst du mir helfen?=Can you help me?",
    "v|*mitbringen|bringe mit/bringst mit/bringt mit|hat mitgebracht|to bring along|Bring bitte Brot mit.=Please bring bread along.",
    "v|!bleiben|bleibe/bleibst/bleibt|ist geblieben|to stay|Ich bleibe heute zu Hause.=I am staying home today.",
    "v|mögen|mag/magst/mag|hat gemocht|to like|Ich mag deutschen Kaffee nicht.=I do not like German coffee.",
    "a|gut|besser/am besten|good|Das Essen ist gut.=The food is good.",
    "a|schlecht|schlechter/am schlechtesten|bad|Das Wetter ist schlecht.=The weather is bad.",
    "a|groß|größer/am größten|big, tall|Die Wohnung ist groß.=The flat is big.",
    "a|klein|kleiner/am kleinsten|small|Mein Zimmer ist klein.=My room is small.",
    "a|neu|neuer/am neuesten|new|Ich habe ein neues Handy.=I have a new mobile phone.",
    "a|schön|schöner/am schönsten|beautiful, nice|Das ist eine schöne Stadt.=That is a beautiful city.",
    "a|schwierig|schwieriger/am schwierigsten|difficult|Deutsch ist nicht so schwierig.=German is not that difficult.",
    "a|einfach|einfacher/am einfachsten|easy, simple|Die Übung war einfach.=The exercise was easy.",
    "a|alt|älter/am ältesten|old|Der Mann ist sehr alt.=The man is very old.",
    "a|freundlich|freundlicher/am freundlichsten|friendly|Die Kollegin ist sehr freundlich.=The colleague is very friendly.",
    "w|sehr|adv|very|Das ist sehr wichtig.=That is very important.",
    "w|auch|adv|also|Ich komme auch mit.=I am coming along too.",
    "w|noch|adv|still, yet|Ich habe noch Zeit.=I still have time.",
    "w|schon|adv|already|Er ist schon da.=He is already here.",
    "w|hier|adv|here|Hier ist mein Ausweis.=Here is my ID.",
    "w|dort|adv|there|Dort ist die Haltestelle.=The stop is over there.",
    "w|vielleicht|adv|maybe|Vielleicht komme ich später.=Maybe I will come later.",
    "w|leider|adv|unfortunately|Leider habe ich keine Zeit.=Unfortunately I have no time.",
  ]);

  /* ================= A2 ================= */
  g('A2','travel',[
    "n|Reise|die|die Reisen|journey, trip|Die Reise hat acht Stunden gedauert.=The journey took eight hours.",
    "n|Flughafen|der|die Flughäfen|airport|Der Flughafen liegt außerhalb der Stadt.=The airport is outside the city.",
    "n|Gepäck|das|—|luggage|Mein Gepäck ist nicht angekommen.=My luggage has not arrived.",
    "n|Koffer|der|die Koffer|suitcase|Der Koffer ist zu schwer.=The suitcase is too heavy.",
    "n|Verspätung|die|die Verspätungen|delay|Der Zug hat zwanzig Minuten Verspätung.=The train is twenty minutes late.",
    "n|Unterkunft|die|die Unterkünfte|accommodation|Wir suchen eine günstige Unterkunft.=We are looking for affordable accommodation.",
    "n|Ausweis|der|die Ausweise|ID card|Zeigen Sie bitte Ihren Ausweis.=Please show your ID card.",
    "v|!reisen|reise/reist/reist|ist gereist|to travel|Ich reise gern mit dem Zug.=I like travelling by train.",
    "v|buchen|buche/buchst/bucht|hat gebucht|to book|Ich habe ein Zimmer gebucht.=I have booked a room.",
    "v|*umsteigen|steige um/steigst um/steigt um|ist umgestiegen|to change (trains)|In Frankfurt müssen Sie umsteigen.=You have to change in Frankfurt.",
    "v|!ankommen|komme an/kommst an/kommt an|ist angekommen|to arrive|Wir sind pünktlich angekommen.=We arrived on time.",
    "v|!abfahren|fahre ab/fährst ab/fährt ab|ist abgefahren|to depart|Der Zug fährt um 9:12 Uhr ab.=The train departs at 9:12.",
    "a|pünktlich|pünktlicher/am pünktlichsten|punctual|Der Bus war pünktlich.=The bus was on time.",
  ]);
  g('A2','housing',[
    "n|Vermieter|der|die Vermieter|landlord|Ich habe dem Vermieter geschrieben.=I wrote to the landlord.",
    "n|Nachbar|der|die Nachbarn|neighbour|Mein Nachbar ist sehr laut.=My neighbour is very loud.",
    "n|Heizung|die|die Heizungen|heating|Die Heizung funktioniert nicht.=The heating does not work.",
    "n|Nebenkosten|die|die Nebenkosten|additional costs|Die Nebenkosten sind nicht enthalten.=The additional costs are not included.",
    "n|Vertrag|der|die Verträge|contract|Ich habe den Vertrag unterschrieben.=I signed the contract.",
    "n|Kaution|die|die Kautionen|deposit|Die Kaution beträgt zwei Monatsmieten.=The deposit is two months' rent.",
    "v|funktionieren|funktioniere/funktionierst/funktioniert|hat funktioniert|to work, to function|Der Aufzug funktioniert nicht.=The lift is not working.",
    "v|reparieren|repariere/reparierst/repariert|hat repariert|to repair|Der Vermieter lässt die Heizung reparieren.=The landlord is having the heating repaired.",
    "v|*aufräumen|räume auf/räumst auf/räumt auf|hat aufgeräumt|to tidy up|Ich räume die Küche auf.=I am tidying up the kitchen.",
    "v|sich beschweren|beschwere mich/beschwerst dich/beschwert sich|hat sich beschwert|to complain|Ich habe mich beim Vermieter beschwert.=I complained to the landlord.",
  ]);
  g('A2','work',[
    "n|Stelle|die|die Stellen|position, job|Ich habe eine neue Stelle gefunden.=I have found a new job.",
    "n|Bewerbung|die|die Bewerbungen|application|Ich schicke morgen die Bewerbung ab.=I will send the application tomorrow.",
    "n|Lebenslauf|der|die Lebensläufe|CV|Der Lebenslauf muss aktuell sein.=The CV must be up to date.",
    "n|Vorstellungsgespräch|das|die Vorstellungsgespräche|job interview|Das Vorstellungsgespräch war am Montag.=The job interview was on Monday.",
    "n|Gehalt|das|die Gehälter|salary|Das Gehalt ist in Ordnung.=The salary is fine.",
    "n|Ausbildung|die|die Ausbildungen|vocational training|Er macht eine Ausbildung als Elektriker.=He is doing an apprenticeship as an electrician.",
    "n|Praktikum|das|die Praktika|internship|Ich mache ein Praktikum im Krankenhaus.=I am doing an internship at the hospital.",
    "n|Schicht|die|die Schichten|shift|Diese Woche habe ich Spätschicht.=This week I am on late shift.",
    "n|Urlaub|der|die Urlaube|holiday, leave|Ich nehme im August Urlaub.=I am taking leave in August.",
    "v|sich bewerben|bewerbe mich/bewirbst dich/bewirbt sich|hat sich beworben|to apply|Ich bewerbe mich um die Stelle.=I am applying for the position.",
    "v|verdienen|verdiene/verdienst/verdient|hat verdient|to earn|Sie verdient gut.=She earns well.",
    "v|kündigen|kündige/kündigst/kündigt|hat gekündigt|to resign, to terminate|Er hat zum Monatsende gekündigt.=He resigned effective the end of the month.",
    "v|*teilnehmen|nehme teil/nimmst teil/nimmt teil|hat teilgenommen|to take part|Ich nehme an einer Fortbildung teil.=I am taking part in a training course.",
  ]);
  g('A2','health2',[
    "n|Krankenkasse|die|die Krankenkassen|health insurance fund|Die Krankenkasse zahlt die Behandlung.=The health insurance covers the treatment.",
    "n|Rezept|das|die Rezepte|prescription, recipe|Der Arzt hat mir ein Rezept gegeben.=The doctor gave me a prescription.",
    "n|Untersuchung|die|die Untersuchungen|examination|Die Untersuchung dauert zehn Minuten.=The examination takes ten minutes.",
    "n|Beschwerde|die|die Beschwerden|complaint, symptom|Ich habe seit einer Woche Beschwerden.=I have had symptoms for a week.",
    "n|Erkältung|die|die Erkältungen|cold (illness)|Ich habe eine Erkältung.=I have a cold.",
    "n|Fieber|das|—|fever|Mein Sohn hat Fieber.=My son has a fever.",
    "v|sich fühlen|fühle mich/fühlst dich/fühlt sich|hat sich gefühlt|to feel|Ich fühle mich heute besser.=I feel better today.",
    "v|sich erholen|erhole mich/erholst dich/erholt sich|hat sich erholt|to recover|Er hat sich schnell erholt.=He recovered quickly.",
    "v|wehtun|tue weh/tust weh/tut weh|hat wehgetan|to hurt|Der Rücken tut mir weh.=My back hurts.",
    "v|*einnehmen|nehme ein/nimmst ein/nimmt ein|hat eingenommen|to take (medicine)|Nehmen Sie die Tabletten nach dem Essen ein.=Take the tablets after meals.",
  ]);
  g('A2','feelings',[
    "a|glücklich|glücklicher/am glücklichsten|happy|Ich bin sehr glücklich hier.=I am very happy here.",
    "a|traurig|trauriger/am traurigsten|sad|Die Nachricht war traurig.=The news was sad.",
    "a|nervös|nervöser/am nervösesten|nervous|Vor der Prüfung war ich nervös.=Before the exam I was nervous.",
    "a|zufrieden|zufriedener/am zufriedensten|satisfied|Mein Chef ist zufrieden.=My boss is satisfied.",
    "a|wütend|wütender/am wütendsten|angry|Er war wirklich wütend.=He was really angry.",
    "a|aufgeregt|aufgeregter/am aufgeregtesten|excited|Die Kinder sind aufgeregt.=The children are excited.",
    "v|sich freuen|freue mich/freust dich/freut sich|hat sich gefreut|to be glad|Ich freue mich auf das Wochenende.=I am looking forward to the weekend.",
    "v|sich ärgern|ärgere mich/ärgerst dich/ärgert sich|hat sich geärgert|to be annoyed|Ich ärgere mich über den Lärm.=I am annoyed about the noise.",
    "v|hoffen|hoffe/hoffst/hofft|hat gehofft|to hope|Ich hoffe, dass alles klappt.=I hope everything works out.",
    "v|sich interessieren|interessiere mich/interessierst dich/interessiert sich|hat sich interessiert|to be interested|Ich interessiere mich für Technik.=I am interested in technology.",
  ]);
  g('A2','services',[
    "n|Amt|das|die Ämter|public authority, office|Ich muss zum Amt gehen.=I have to go to the public office.",
    "n|Formular|das|die Formulare|form|Füllen Sie bitte das Formular aus.=Please fill in the form.",
    "n|Anmeldung|die|die Anmeldungen|registration|Die Anmeldung dauert zehn Minuten.=The registration takes ten minutes.",
    "n|Bescheinigung|die|die Bescheinigungen|certificate|Ich brauche eine Bescheinigung vom Arzt.=I need a certificate from the doctor.",
    "n|Unterschrift|die|die Unterschriften|signature|Hier fehlt Ihre Unterschrift.=Your signature is missing here.",
    "n|Rechnung|die|die Rechnungen|bill, invoice|Die Rechnung kommt per Post.=The bill will come by post.",
    "v|*ausfüllen|fülle aus/füllst aus/füllt aus|hat ausgefüllt|to fill in|Ich habe das Formular ausgefüllt.=I have filled in the form.",
    "v|erklären|erkläre/erklärst/erklärt|hat erklärt|to explain|Können Sie mir das erklären?=Can you explain that to me?",
  ]);
  g('A2','opinions',[
    "n|Meinung|die|die Meinungen|opinion|Meiner Meinung nach ist das falsch.=In my opinion that is wrong.",
    "n|Grund|der|die Gründe|reason|Es gibt einen guten Grund dafür.=There is a good reason for it.",
    "n|Problem|das|die Probleme|problem|Wir haben ein kleines Problem.=We have a small problem.",
    "n|Lösung|die|die Lösungen|solution|Ich sehe keine einfache Lösung.=I see no easy solution.",
    "n|Vorschlag|der|die Vorschläge|suggestion|Ich habe einen Vorschlag.=I have a suggestion.",
    "n|Wunsch|der|die Wünsche|wish|Ich habe nur einen Wunsch.=I have only one wish.",
    "v|denken|denke/denkst/denkt|hat gedacht|to think|Ich denke, das ist eine gute Idee.=I think that is a good idea.",
    "v|glauben|glaube/glaubst/glaubt|hat geglaubt|to believe|Ich glaube, er hat recht.=I believe he is right.",
    "v|vorschlagen|schlage vor/schlägst vor/schlägt vor|hat vorgeschlagen|to suggest|Ich schlage Donnerstag vor.=I suggest Thursday.",
    "v|sich entscheiden|entscheide mich/entscheidest dich/entscheidet sich|hat sich entschieden|to decide|Wir haben uns für die Wohnung entschieden.=We decided on the flat.",
    "v|diskutieren|diskutiere/diskutierst/diskutiert|hat diskutiert|to discuss|Wir haben lange diskutiert.=We discussed for a long time.",
    "w|deshalb|adv|therefore|Es war spät, deshalb bin ich gegangen.=It was late, so I left.",
    "w|trotzdem|adv|nevertheless|Es regnete. Trotzdem sind wir gelaufen.=It was raining. We walked anyway.",
    "w|außerdem|adv|besides, moreover|Außerdem ist es zu teuer.=Besides, it is too expensive.",
  ]);
  g('A2','media',[
    "n|Nachricht|die|die Nachrichten|message; (pl.) news|Ich habe dir eine Nachricht geschickt.=I sent you a message.",
    "n|Zeitung|die|die Zeitungen|newspaper|Ich lese morgens die Zeitung.=I read the newspaper in the morning.",
    "n|Werbung|die|die Werbungen|advertising|Im Radio kommt zu viel Werbung.=There is too much advertising on the radio.",
    "n|Internet|das|—|internet|Ich suche im Internet eine Wohnung.=I am looking for a flat on the internet.",
    "n|Anzeige|die|die Anzeigen|advertisement, notice|Ich habe die Anzeige online gefunden.=I found the advertisement online.",
    "v|*herunterladen|lade herunter/lädst herunter/lädt herunter|hat heruntergeladen|to download|Ich habe die App heruntergeladen.=I downloaded the app.",
    "v|schicken|schicke/schickst/schickt|hat geschickt|to send|Ich schicke dir die Adresse.=I will send you the address.",
    "v|speichern|speichere/speicherst/speichert|hat gespeichert|to save|Hast du die Datei gespeichert?=Did you save the file?",
  ]);
  g('A2','time2',[
    "w|damals|adv|back then|Damals war alles anders.=Back then everything was different.",
    "w|neulich|adv|recently|Neulich habe ich ihn getroffen.=I met him recently.",
    "w|früher|adv|formerly, in the past|Früher habe ich in Kabul gewohnt.=I used to live in Kabul.",
    "w|plötzlich|adv|suddenly|Plötzlich hat es geregnet.=Suddenly it started raining.",
    "w|zuerst|adv|first (of all)|Zuerst gehe ich einkaufen.=First I go shopping.",
    "w|danach|adv|afterwards|Danach fahre ich nach Hause.=Afterwards I drive home.",
    "w|schließlich|adv|finally|Schließlich haben wir eine Lösung gefunden.=Finally we found a solution.",
    "w|seit|prep|since, for|Ich lerne seit einem Jahr Deutsch.=I have been learning German for a year.",
    "w|bis|prep|until|Ich arbeite bis sechs Uhr.=I work until six.",
    "w|während|prep|during|Während der Pause trinke ich Kaffee.=During the break I drink coffee.",
    "n|Vergangenheit|die|—|past|In der Vergangenheit war das anders.=In the past that was different.",
    "n|Zukunft|die|—|future|In Zukunft mache ich das anders.=In future I will do that differently.",
  ]);

  return out;
})();

if(typeof module !== 'undefined' && module.exports){ module.exports = { VOCAB_CORE }; }
