/* ============================================================
   WRITING (spec §25-27)
   Every prompt states purpose, audience, register, a structural
   skeleton and real assessment criteria — not just "write about X".
   ============================================================ */
const WRITING_PROMPTS_RICH = (() => {
  const S = (typeof Schema !== 'undefined') ? Schema : require('../core/schema.js');
  const mk = (id, level, title, task, opts) => ({
    id: S.ID_PREFIX.writing + id, level, title, task,
    textType: opts.textType, audience: opts.audience, register: opts.register,
    minWords: opts.minWords, maxWords: opts.maxWords,
    skeleton: opts.skeleton || [], criteria: opts.criteria || [],
    modelAnswer: opts.modelAnswer || null, meta: S.meta(),
  });

  return [
  mk('a1_steckbrief','A1','Steckbrief: Über mich',
    'Schreib einen kurzen Steckbrief über dich: Name, Alter, Herkunft, Wohnort, Beruf oder Studium, Sprachen, ein Hobby.',
    { textType:'personal profile', audience:'classmates', register:'informal', minWords:30, maxWords:60,
      skeleton:['Name und Alter','Herkunft und Wohnort','Beruf/Studium','Sprachen','Ein Hobby'],
      criteria:['Alle sechs Punkte sind enthalten','Verben sind richtig konjugiert (ich-Form)','Sätze beginnen mit Großbuchstaben, Nomen sind großgeschrieben'],
      modelAnswer:'Ich heiße Fatima und bin 24 Jahre alt. Ich komme aus Kabul und wohne jetzt in Leipzig. Ich studiere Wirtschaft. Ich spreche Dari, Englisch und ein bisschen Deutsch. In meiner Freizeit lese ich gern.' }),
  mk('a1_einkaufszettel','A1','Eine kurze Nachricht: Einkaufsliste und Bitte',
    'Dein Mitbewohner geht einkaufen. Schreib eine kurze Nachricht: was er kaufen soll und warum.',
    { textType:'short message', audience:'flatmate', register:'informal', minWords:20, maxWords:40,
      skeleton:['Anrede','Bitte formulieren','Liste nennen','Grund (optional)','Danke'],
      criteria:['Die Bitte ist klar','Mindestens drei Einkaufsartikel werden genannt','Ein kurzer, freundlicher Ton'],
      modelAnswer:'Hallo Tom! Kannst du bitte einkaufen gehen? Wir brauchen Milch, Brot und Äpfel. Ich habe heute keine Zeit, weil ich arbeiten muss. Danke! Amina' }),
  mk('a2_email_einladung','A2','E-Mail: Eine Einladung schreiben',
    'Lade eine Freundin/einen Freund zu deinem Geburtstag ein. Nenne Datum, Uhrzeit, Ort und frage, ob sie/er kommen kann.',
    { textType:'email', audience:'friend', register:'informal', minWords:50, maxWords:90,
      skeleton:['Anrede','Anlass nennen','Datum, Uhrzeit, Ort','Persönliche Note','Frage/Bitte um Antwort','Grußformel'],
      criteria:['Alle Informationen (Datum, Zeit, Ort) sind enthalten','Mindestens ein Satz mit weil oder denn','Passende informelle Anrede und Grußformel'],
      modelAnswer:'Liebe Lena,\n\nich feiere am 14. Juni meinen Geburtstag und würde mich freuen, wenn du kommst! Die Feier beginnt um 19 Uhr bei mir in der Wohnung (Musterstraße 12). Es gibt Essen und Musik, und ich lade auch ein paar andere Freunde ein.\n\nHast du an dem Tag Zeit? Lass es mich bitte bis Freitag wissen.\n\nLiebe Grüße\nOmar' }),
  mk('a2_beschwerde_kurz','A2','Kurze Beschwerde: Kaputtes Gerät',
    'Du hast online eine Lampe bestellt. Sie ist beschädigt angekommen. Schreib eine kurze, höfliche Beschwerde und sag, was du möchtest.',
    { textType:'complaint email', audience:'online shop', register:'formal', minWords:50, maxWords:90,
      skeleton:['Anrede','Bestellung nennen','Problem beschreiben','Was du möchtest (Ersatz/Rückzahlung)','Grußformel'],
      criteria:['Die Anrede und der Gruß sind formal','Das Problem ist klar beschrieben','Eine konkrete Forderung wird genannt'],
      modelAnswer:'Sehr geehrte Damen und Herren,\n\nam 5. April habe ich bei Ihnen eine Lampe bestellt (Bestellnummer 88213). Leider ist der Lampenschirm beim Transport zerbrochen.\n\nIch bitte Sie, mir eine neue Lampe zu schicken oder den Kaufpreis zu erstatten.\n\nMit freundlichen Grüßen\nJonas Weber' }),
  mk('b1_meinung_homeoffice','B1','Meinungstext: Homeoffice – Vor- und Nachteile',
    'Schreib einen kurzen Text (ca. 120-150 Wörter): Was sind die Vor- und Nachteile von Homeoffice? Nenne deine eigene Meinung.',
    { textType:'opinion text', audience:'course/forum', register:'neutral-formal', minWords:120, maxWords:170,
      skeleton:['Einleitung: Thema nennen','Ein Vorteil mit Beispiel','Ein Nachteil mit Beispiel','Eigene Meinung mit Begründung','Schluss'],
      criteria:['Mindestens ein Vorteil und ein Nachteil, jeweils begründet','Mindestens ein Konnektor (weil/deshalb/obwohl/trotzdem)','Eine klare eigene Meinung am Ende'],
      modelAnswer:'Immer mehr Menschen arbeiten von zu Hause. Ein großer Vorteil ist die Zeitersparnis, weil man nicht pendeln muss. Ein Nachteil ist jedoch, dass der Kontakt zu Kollegen fehlt, was manche Menschen isoliert.\n\nMeiner Meinung nach ist eine Mischung aus Homeoffice und Büro am besten. So kann man flexibel arbeiten, ohne den Kontakt zu Kollegen ganz zu verlieren.' }),
  mk('b1_bericht_erlebnis','B1','Bericht: Ein besonderes Erlebnis',
    'Beschreibe ein besonderes Erlebnis aus deinem Leben (eine Reise, ein wichtiger Tag, ein Problem, das du gelöst hast). Nutze das Perfekt und/oder Präteritum.',
    { textType:'narrative report', audience:'course', register:'neutral', minWords:120, maxWords:180,
      skeleton:['Wann und wo?','Was ist passiert (chronologisch)?','Wie hast du dich gefühlt?','Wie ist es ausgegangen?'],
      criteria:['Klare zeitliche Reihenfolge (zuerst, dann, danach, schließlich)','Korrekte Vergangenheitsformen','Mindestens ein Gefühl oder eine Bewertung wird genannt'],
      modelAnswer:null }),
  mk('b2_kommentar_stadtverkehr','B2','Leserbrief: Stellung nehmen zum Stadtverkehr',
    'Schreib einen Leserbrief (180-220 Wörter) zu der Frage: Sollten Innenstädte autofrei werden? Nenne Argumente für und gegen die Maßnahme und formuliere eine begründete eigene Position.',
    { textType:'letter to the editor', audience:'newspaper readers', register:'formal', minWords:180, maxWords:230,
      skeleton:['Einleitung: Kontext des Themas','Position der Befürworter mit Argumenten','Position der Gegner mit Argumenten','Eigene, begründete Position','Schlussgedanke oder Kompromissvorschlag'],
      criteria:['Beide Seiten werden fair dargestellt, bevor die eigene Position kommt','Mindestens zwei unterschiedliche Konnektoren (z. B. einerseits/andererseits, dennoch, allerdings)','Ein klar begründeter eigener Standpunkt'],
      modelAnswer:null }),
  mk('b2_bewerbungsschreiben','B2','Anschreiben für eine Bewerbung',
    'Schreib ein kurzes Anschreiben (150-200 Wörter) für eine Stelle, die dich interessiert. Nenne deine Motivation, relevante Erfahrung und warum du zur Stelle passt.',
    { textType:'cover letter', audience:'employer', register:'formal', minWords:150, maxWords:220,
      skeleton:['Betreff/Bezug auf die Anzeige','Motivation','Relevante Erfahrung/Qualifikation','Warum du passt','Abschluss mit Gesprächswunsch'],
      criteria:['Formale, konsistente Anrede und Grußformel','Konkrete, nicht generische Begründung der Motivation','Professioneller, aber nicht steifer Ton'],
      modelAnswer:null }),
  mk('c1_essay_bildung','C1','Essay: Chancengleichheit im Bildungssystem',
    'Schreib einen argumentativen Essay (280-350 Wörter) zur Frage: Wie stark hängt Bildungserfolg in Deutschland von der sozialen Herkunft ab? Strukturiere deine Argumentation klar und belege deine Aussagen.',
    { textType:'academic essay', audience:'academic/general educated reader', register:'formal, academic', minWords:280, maxWords:360,
      skeleton:['Einleitung mit Fragestellung','Hauptargument 1 mit Beleg','Hauptargument 2 mit Beleg','Gegenargument/Einschränkung','Fazit mit eigener Position'],
      criteria:['Klare These in der Einleitung','Mindestens zwei belegte Argumente, nicht nur behauptet','Ein Gegenargument wird ernsthaft berücksichtigt, nicht nur erwähnt','Konsistentes formales Register durchgehend'],
      modelAnswer:null }),
  mk('c2_synthese','C2','Synthese: Zwei widersprüchliche Positionen zusammenführen',
    'Dir liegen zwei Kommentare zum Thema künstliche Intelligenz und Arbeitsmarkt vor, die sich widersprechen (Kommentar A: KI schafft mehr Arbeitsplätze als sie vernichtet; Kommentar B: KI führt zu massivem Stellenabbau). Schreib eine Synthese (350-450 Wörter), die beide Positionen fair darstellt, ihre Widersprüche benennt und zu einer eigenen, differenzierten Einschätzung kommt.',
    { textType:'synthesis essay', audience:'informed general reader', register:'formal, precise', minWords:350, maxWords:460,
      skeleton:['Einleitung: beide Positionen benennen','Position A mit ihrer Begründung fair darstellen','Position B mit ihrer Begründung fair darstellen','Gemeinsamkeiten und Widersprüche benennen','Eigene differenzierte Einschätzung'],
      criteria:['Beide Positionen werden in einer Form dargestellt, die ihre Vertreter selbst wiedererkennen würden','Die Widersprüche zwischen den Positionen werden explizit benannt, nicht nur nebeneinandergestellt','Die eigene Einschätzung ist differenziert, nicht einfach "beide haben ein bisschen recht"','Ein einheitliches, kontrolliertes Register über den gesamten Text'],
      modelAnswer:null }),
  ];
})();

if(typeof module !== 'undefined' && module.exports){ module.exports = { WRITING_PROMPTS_RICH }; }
