/* ============================================================
   DEUTSCHBEGLEITER — CONTENT DATA
   All learning content lives here, separate from app logic,
   so new vocabulary / lessons can be added without touching
   the UI or engine code (see spec section 47).
   ============================================================ */

/* ---------------- VOCABULARY ---------------- */
/* type: noun | verb | adj | adv | pron | num | qword | phrase
   article: 'der' | 'die' | 'das' | '' (non-nouns)
   forms (verbs only): { praesens:{ich,du,er}, perfekt, praeteritum, sep:boolean } */
const VOCAB = [
// --- Pronouns & question words (A1) ---
{id:'v001',de:'ich',article:'',plural:'',en:'I',type:'pron',level:'A1',topic:'basics',ex_de:'Ich heiße Sara.',ex_en:'My name is Sara.'},
{id:'v002',de:'du',article:'',plural:'',en:'you (informal)',type:'pron',level:'A1',topic:'basics',ex_de:'Wie heißt du?',ex_en:'What is your name?'},
{id:'v003',de:'er / sie / es',article:'',plural:'',en:'he / she / it',type:'pron',level:'A1',topic:'basics',ex_de:'Er wohnt in Berlin.',ex_en:'He lives in Berlin.'},
{id:'v004',de:'wir',article:'',plural:'',en:'we',type:'pron',level:'A1',topic:'basics',ex_de:'Wir lernen Deutsch.',ex_en:'We are learning German.'},
{id:'v005',de:'ihr',article:'',plural:'',en:'you (plural informal)',type:'pron',level:'A1',topic:'basics',ex_de:'Woher kommt ihr?',ex_en:'Where are you (pl.) from?'},
{id:'v006',de:'Sie',article:'',plural:'',en:'you (formal)',type:'pron',level:'A1',topic:'basics',ex_de:'Wie heißen Sie?',ex_en:'What is your name? (formal)'},
{id:'v007',de:'wer',article:'',plural:'',en:'who',type:'qword',level:'A1',topic:'basics',ex_de:'Wer ist das?',ex_en:'Who is that?'},
{id:'v008',de:'was',article:'',plural:'',en:'what',type:'qword',level:'A1',topic:'basics',ex_de:'Was machst du?',ex_en:'What are you doing?'},
{id:'v009',de:'wo',article:'',plural:'',en:'where',type:'qword',level:'A1',topic:'basics',ex_de:'Wo wohnst du?',ex_en:'Where do you live?'},
{id:'v010',de:'wann',article:'',plural:'',en:'when',type:'qword',level:'A1',topic:'basics',ex_de:'Wann kommst du?',ex_en:'When are you coming?'},
{id:'v011',de:'warum',article:'',plural:'',en:'why',type:'qword',level:'A1',topic:'basics',ex_de:'Warum lernst du Deutsch?',ex_en:'Why are you learning German?'},
{id:'v012',de:'wie',article:'',plural:'',en:'how',type:'qword',level:'A1',topic:'basics',ex_de:'Wie geht es dir?',ex_en:'How are you?'},
{id:'v013',de:'woher',article:'',plural:'',en:'from where',type:'qword',level:'A1',topic:'basics',ex_de:'Woher kommst du?',ex_en:'Where are you from?'},

// --- Greetings / basics ---
{id:'v014',de:'heißen',article:'',plural:'',en:'to be called',type:'verb',level:'A1',topic:'greetings',
  forms:{praesens:{ich:'heiße',du:'heißt',er:'heißt'},perfekt:'hat geheißen',praeteritum:'hieß'},
  ex_de:'Ich heiße Ahmed.',ex_en:'My name is Ahmed.'},
{id:'v015',de:'sein',article:'',plural:'',en:'to be',type:'verb',level:'A1',topic:'greetings',
  forms:{praesens:{ich:'bin',du:'bist',er:'ist'},perfekt:'ist gewesen',praeteritum:'war'},
  ex_de:'Ich bin müde.',ex_en:'I am tired.'},
{id:'v016',de:'kommen',article:'',plural:'',en:'to come',type:'verb',level:'A1',topic:'greetings',
  forms:{praesens:{ich:'komme',du:'kommst',er:'kommt'},perfekt:'ist gekommen',praeteritum:'kam'},
  ex_de:'Ich komme aus Pakistan.',ex_en:'I come from Pakistan.'},
{id:'v017',de:'wohnen',article:'',plural:'',en:'to live (reside)',type:'verb',level:'A1',topic:'greetings',
  forms:{praesens:{ich:'wohne',du:'wohnst',er:'wohnt'},perfekt:'hat gewohnt',praeteritum:'wohnte'},
  ex_de:'Wir wohnen in München.',ex_en:'We live in Munich.'},
{id:'v018',de:'der Name',article:'der',plural:'die Namen',en:'name',type:'noun',level:'A1',topic:'greetings',ex_de:'Mein Name ist Klaus.',ex_en:'My name is Klaus.'},
{id:'v019',de:'guten Morgen',article:'',plural:'',en:'good morning',type:'phrase',level:'A1',topic:'greetings',ex_de:'Guten Morgen!',ex_en:'Good morning!'},
{id:'v020',de:'guten Tag',article:'',plural:'',en:'good day / hello',type:'phrase',level:'A1',topic:'greetings',ex_de:'Guten Tag, Frau Schmidt.',ex_en:'Hello, Mrs. Schmidt.'},
{id:'v021',de:'auf Wiedersehen',article:'',plural:'',en:'goodbye (formal)',type:'phrase',level:'A1',topic:'greetings',ex_de:'Auf Wiedersehen!',ex_en:'Goodbye!'},
{id:'v022',de:'danke',article:'',plural:'',en:'thank you',type:'phrase',level:'A1',topic:'greetings',ex_de:'Danke schön!',ex_en:'Thank you very much!'},
{id:'v023',de:'bitte',article:'',plural:'',en:'please / you\u2019re welcome',type:'phrase',level:'A1',topic:'greetings',ex_de:'Bitte schön.',ex_en:'You\u2019re welcome.'},

// --- Numbers ---
{id:'v024',de:'eins',article:'',plural:'',en:'one',type:'num',level:'A1',topic:'numbers'},
{id:'v025',de:'zwei',article:'',plural:'',en:'two',type:'num',level:'A1',topic:'numbers'},
{id:'v026',de:'drei',article:'',plural:'',en:'three',type:'num',level:'A1',topic:'numbers'},
{id:'v027',de:'vier',article:'',plural:'',en:'four',type:'num',level:'A1',topic:'numbers'},
{id:'v028',de:'fünf',article:'',plural:'',en:'five',type:'num',level:'A1',topic:'numbers'},
{id:'v029',de:'sechs',article:'',plural:'',en:'six',type:'num',level:'A1',topic:'numbers'},
{id:'v030',de:'sieben',article:'',plural:'',en:'seven',type:'num',level:'A1',topic:'numbers'},
{id:'v031',de:'acht',article:'',plural:'',en:'eight',type:'num',level:'A1',topic:'numbers'},
{id:'v032',de:'neun',article:'',plural:'',en:'nine',type:'num',level:'A1',topic:'numbers'},
{id:'v033',de:'zehn',article:'',plural:'',en:'ten',type:'num',level:'A1',topic:'numbers'},
{id:'v034',de:'zwanzig',article:'',plural:'',en:'twenty',type:'num',level:'A1',topic:'numbers'},
{id:'v035',de:'dreißig',article:'',plural:'',en:'thirty',type:'num',level:'A1',topic:'numbers'},
{id:'v036',de:'hundert',article:'',plural:'',en:'one hundred',type:'num',level:'A1',topic:'numbers'},
{id:'v037',de:'das Jahr',article:'das',plural:'die Jahre',en:'year',type:'noun',level:'A1',topic:'numbers',ex_de:'Ich bin zwanzig Jahre alt.',ex_en:'I am twenty years old.'},
{id:'v038',de:'alt',article:'',plural:'',en:'old',type:'adj',level:'A1',topic:'numbers',ex_de:'Wie alt bist du?',ex_en:'How old are you?'},

// --- Family ---
{id:'v039',de:'die Familie',article:'die',plural:'die Familien',en:'family',type:'noun',level:'A1',topic:'family',ex_de:'Meine Familie ist groß.',ex_en:'My family is big.'},
{id:'v040',de:'der Vater',article:'der',plural:'die Väter',en:'father',type:'noun',level:'A1',topic:'family',ex_de:'Mein Vater arbeitet viel.',ex_en:'My father works a lot.'},
{id:'v041',de:'die Mutter',article:'die',plural:'die Mütter',en:'mother',type:'noun',level:'A1',topic:'family',ex_de:'Meine Mutter kocht gern.',ex_en:'My mother likes to cook.'},
{id:'v042',de:'der Bruder',article:'der',plural:'die Brüder',en:'brother',type:'noun',level:'A1',topic:'family',ex_de:'Ich habe einen Bruder.',ex_en:'I have a brother.'},
{id:'v043',de:'die Schwester',article:'die',plural:'die Schwestern',en:'sister',type:'noun',level:'A1',topic:'family',ex_de:'Meine Schwester ist Ärztin.',ex_en:'My sister is a doctor.'},
{id:'v044',de:'der Sohn',article:'der',plural:'die Söhne',en:'son',type:'noun',level:'A1',topic:'family',ex_de:'Der Sohn spielt Fußball.',ex_en:'The son plays soccer.'},
{id:'v045',de:'die Tochter',article:'die',plural:'die Töchter',en:'daughter',type:'noun',level:'A1',topic:'family',ex_de:'Die Tochter lernt Deutsch.',ex_en:'The daughter is learning German.'},
{id:'v046',de:'das Kind',article:'das',plural:'die Kinder',en:'child',type:'noun',level:'A1',topic:'family',ex_de:'Das Kind ist glücklich.',ex_en:'The child is happy.'},
{id:'v047',de:'der Mann',article:'der',plural:'die Männer',en:'man / husband',type:'noun',level:'A1',topic:'family',ex_de:'Der Mann heißt Peter.',ex_en:'The man is called Peter.'},
{id:'v048',de:'die Frau',article:'die',plural:'die Frauen',en:'woman / wife',type:'noun',level:'A1',topic:'family',ex_de:'Die Frau kommt aus Kabul.',ex_en:'The woman comes from Kabul.'},
{id:'v049',de:'haben',article:'',plural:'',en:'to have',type:'verb',level:'A1',topic:'family',
  forms:{praesens:{ich:'habe',du:'hast',er:'hat'},perfekt:'hat gehabt',praeteritum:'hatte'},
  ex_de:'Ich habe zwei Kinder.',ex_en:'I have two children.'},

// --- Daily routine / verbs ---
{id:'v050',de:'machen',article:'',plural:'',en:'to do / make',type:'verb',level:'A1',topic:'routine',
  forms:{praesens:{ich:'mache',du:'machst',er:'macht'},perfekt:'hat gemacht',praeteritum:'machte'},
  ex_de:'Was machst du heute?',ex_en:'What are you doing today?'},
{id:'v051',de:'arbeiten',article:'',plural:'',en:'to work',type:'verb',level:'A1',topic:'routine',
  forms:{praesens:{ich:'arbeite',du:'arbeitest',er:'arbeitet'},perfekt:'hat gearbeitet',praeteritum:'arbeitete'},
  ex_de:'Ich arbeite von neun bis fünf.',ex_en:'I work from nine to five.'},
{id:'v052',de:'lernen',article:'',plural:'',en:'to learn',type:'verb',level:'A1',topic:'routine',
  forms:{praesens:{ich:'lerne',du:'lernst',er:'lernt'},perfekt:'hat gelernt',praeteritum:'lernte'},
  ex_de:'Sie lernt jeden Tag Deutsch.',ex_en:'She learns German every day.'},
{id:'v053',de:'schlafen',article:'',plural:'',en:'to sleep',type:'verb',level:'A1',topic:'routine',
  forms:{praesens:{ich:'schlafe',du:'schläfst',er:'schläft'},perfekt:'hat geschlafen',praeteritum:'schlief'},
  ex_de:'Das Kind schläft schon.',ex_en:'The child is already sleeping.'},
{id:'v054',de:'aufstehen',article:'',plural:'',en:'to get up',type:'verb',level:'A1',topic:'routine',
  forms:{praesens:{ich:'stehe...auf',du:'stehst...auf',er:'steht...auf'},perfekt:'ist aufgestanden',praeteritum:'stand auf',sep:true},
  ex_de:'Ich stehe um sieben Uhr auf.',ex_en:'I get up at seven o\u2019clock.'},
{id:'v055',de:'essen',article:'',plural:'',en:'to eat',type:'verb',level:'A1',topic:'routine',
  forms:{praesens:{ich:'esse',du:'isst',er:'isst'},perfekt:'hat gegessen',praeteritum:'aß'},
  ex_de:'Wir essen um zwölf Uhr.',ex_en:'We eat at twelve o\u2019clock.'},
{id:'v056',de:'trinken',article:'',plural:'',en:'to drink',type:'verb',level:'A1',topic:'routine',
  forms:{praesens:{ich:'trinke',du:'trinkst',er:'trinkt'},perfekt:'hat getrunken',praeteritum:'trank'},
  ex_de:'Er trinkt gern Tee.',ex_en:'He likes to drink tea.'},
{id:'v057',de:'die Uhr',article:'die',plural:'die Uhren',en:'clock / o\u2019clock',type:'noun',level:'A1',topic:'routine',ex_de:'Es ist acht Uhr.',ex_en:'It is eight o\u2019clock.'},
{id:'v058',de:'der Tag',article:'der',plural:'die Tage',en:'day',type:'noun',level:'A1',topic:'routine',ex_de:'Guten Tag!',ex_en:'Good day!'},
{id:'v059',de:'die Woche',article:'die',plural:'die Wochen',en:'week',type:'noun',level:'A1',topic:'routine',ex_de:'Diese Woche arbeite ich viel.',ex_en:'This week I work a lot.'},
{id:'v060',de:'immer',article:'',plural:'',en:'always',type:'adv',level:'A1',topic:'routine',ex_de:'Ich trinke immer Kaffee.',ex_en:'I always drink coffee.'},
{id:'v061',de:'oft',article:'',plural:'',en:'often',type:'adv',level:'A1',topic:'routine',ex_de:'Wir gehen oft spazieren.',ex_en:'We often go for a walk.'},
{id:'v062',de:'manchmal',article:'',plural:'',en:'sometimes',type:'adv',level:'A1',topic:'routine',ex_de:'Manchmal koche ich zu Hause.',ex_en:'Sometimes I cook at home.'},
{id:'v063',de:'nie',article:'',plural:'',en:'never',type:'adv',level:'A1',topic:'routine',ex_de:'Er trinkt nie Alkohol.',ex_en:'He never drinks alcohol.'},

// --- Food & shopping ---
{id:'v064',de:'das Brot',article:'das',plural:'die Brote',en:'bread',type:'noun',level:'A1',topic:'food',ex_de:'Ich kaufe ein Brot.',ex_en:'I am buying a bread.'},
{id:'v065',de:'der Apfel',article:'der',plural:'die Äpfel',en:'apple',type:'noun',level:'A1',topic:'food',ex_de:'Der Apfel ist rot.',ex_en:'The apple is red.'},
{id:'v066',de:'die Banane',article:'die',plural:'die Bananen',en:'banana',type:'noun',level:'A1',topic:'food',ex_de:'Ich esse eine Banane.',ex_en:'I am eating a banana.'},
{id:'v067',de:'das Ei',article:'das',plural:'die Eier',en:'egg',type:'noun',level:'A1',topic:'food',ex_de:'Er isst ein Ei zum Frühstück.',ex_en:'He eats an egg for breakfast.'},
{id:'v068',de:'der Käse',article:'der',plural:'—',en:'cheese',type:'noun',level:'A1',topic:'food',ex_de:'Ich mag Käse.',ex_en:'I like cheese.'},
{id:'v069',de:'das Wasser',article:'das',plural:'—',en:'water',type:'noun',level:'A1',topic:'food',ex_de:'Ein Glas Wasser, bitte.',ex_en:'A glass of water, please.'},
{id:'v070',de:'der Kaffee',article:'der',plural:'—',en:'coffee',type:'noun',level:'A1',topic:'food',ex_de:'Ich trinke einen Kaffee.',ex_en:'I am drinking a coffee.'},
{id:'v071',de:'der Supermarkt',article:'der',plural:'die Supermärkte',en:'supermarket',type:'noun',level:'A1',topic:'food',ex_de:'Der Supermarkt ist um die Ecke.',ex_en:'The supermarket is around the corner.'},
{id:'v072',de:'kaufen',article:'',plural:'',en:'to buy',type:'verb',level:'A1',topic:'food',
  forms:{praesens:{ich:'kaufe',du:'kaufst',er:'kauft'},perfekt:'hat gekauft',praeteritum:'kaufte'},
  ex_de:'Ich kaufe einen Apfel.',ex_en:'I am buying an apple.'},
{id:'v073',de:'brauchen',article:'',plural:'',en:'to need',type:'verb',level:'A1',topic:'food',
  forms:{praesens:{ich:'brauche',du:'brauchst',er:'braucht'},perfekt:'hat gebraucht',praeteritum:'brauchte'},
  ex_de:'Ich brauche Milch.',ex_en:'I need milk.'},
{id:'v074',de:'das Geld',article:'das',plural:'—',en:'money',type:'noun',level:'A1',topic:'food',ex_de:'Ich habe kein Geld.',ex_en:'I have no money.'},
{id:'v075',de:'billig',article:'',plural:'',en:'cheap',type:'adj',level:'A1',topic:'food',ex_de:'Das Brot ist billig.',ex_en:'The bread is cheap.'},
{id:'v076',de:'teuer',article:'',plural:'',en:'expensive',type:'adj',level:'A1',topic:'food',ex_de:'Der Kaffee ist teuer.',ex_en:'The coffee is expensive.'},

// --- Time / appointments (also used for modal verb lesson) ---
{id:'v077',de:'der Termin',article:'der',plural:'die Termine',en:'appointment',type:'noun',level:'A1',topic:'time',ex_de:'Ich habe einen Termin um drei Uhr.',ex_en:'I have an appointment at three o\u2019clock.'},
{id:'v078',de:'können',article:'',plural:'',en:'can / to be able to',type:'verb',level:'A1',topic:'time',
  forms:{praesens:{ich:'kann',du:'kannst',er:'kann'},perfekt:'hat gekonnt',praeteritum:'konnte'},
  ex_de:'Kannst du morgen kommen?',ex_en:'Can you come tomorrow?'},
{id:'v079',de:'müssen',article:'',plural:'',en:'must / to have to',type:'verb',level:'A1',topic:'time',
  forms:{praesens:{ich:'muss',du:'musst',er:'muss'},perfekt:'hat gemusst',praeteritum:'musste'},
  ex_de:'Ich muss um acht Uhr arbeiten.',ex_en:'I have to work at eight o\u2019clock.'},
{id:'v080',de:'heute',article:'',plural:'',en:'today',type:'adv',level:'A1',topic:'time',ex_de:'Was machst du heute?',ex_en:'What are you doing today?'},
{id:'v081',de:'morgen',article:'',plural:'',en:'tomorrow',type:'adv',level:'A1',topic:'time',ex_de:'Bis morgen!',ex_en:'See you tomorrow!'},

// --- A2: modal verbs continued ---
{id:'v082',de:'wollen',article:'',plural:'',en:'to want',type:'verb',level:'A2',topic:'modal',
  forms:{praesens:{ich:'will',du:'willst',er:'will'},perfekt:'hat gewollt',praeteritum:'wollte'},
  ex_de:'Ich will nach Deutschland reisen.',ex_en:'I want to travel to Germany.'},
{id:'v083',de:'möchten',article:'',plural:'',en:'would like to',type:'verb',level:'A2',topic:'modal',
  forms:{praesens:{ich:'möchte',du:'möchtest',er:'möchte'},perfekt:'—',praeteritum:'—'},
  ex_de:'Ich möchte einen Kaffee, bitte.',ex_en:'I would like a coffee, please.'},
{id:'v084',de:'dürfen',article:'',plural:'',en:'to be allowed to',type:'verb',level:'A2',topic:'modal',
  forms:{praesens:{ich:'darf',du:'darfst',er:'darf'},perfekt:'hat gedurft',praeteritum:'durfte'},
  ex_de:'Hier darf man nicht rauchen.',ex_en:'One is not allowed to smoke here.'},
{id:'v085',de:'sollen',article:'',plural:'',en:'to be supposed to',type:'verb',level:'A2',topic:'modal',
  forms:{praesens:{ich:'soll',du:'sollst',er:'soll'},perfekt:'hat gesollt',praeteritum:'sollte'},
  ex_de:'Du sollst pünktlich sein.',ex_en:'You are supposed to be on time.'},

// --- A2: Perfekt-focused verbs ---
{id:'v086',de:'gehen',article:'',plural:'',en:'to go',type:'verb',level:'A1',topic:'movement',
  forms:{praesens:{ich:'gehe',du:'gehst',er:'geht'},perfekt:'ist gegangen',praeteritum:'ging'},
  ex_de:'Ich gehe ins Kino.',ex_en:'I am going to the cinema.'},
{id:'v087',de:'fahren',article:'',plural:'',en:'to drive / travel',type:'verb',level:'A1',topic:'movement',
  forms:{praesens:{ich:'fahre',du:'fährst',er:'fährt'},perfekt:'ist gefahren',praeteritum:'fuhr'},
  ex_de:'Wir fahren nach Berlin.',ex_en:'We are traveling to Berlin.'},
{id:'v088',de:'sehen',article:'',plural:'',en:'to see',type:'verb',level:'A2',topic:'perception',
  forms:{praesens:{ich:'sehe',du:'siehst',er:'sieht'},perfekt:'hat gesehen',praeteritum:'sah'},
  ex_de:'Ich sehe einen Film.',ex_en:'I am watching a film.'},
{id:'v089',de:'sprechen',article:'',plural:'',en:'to speak',type:'verb',level:'A2',topic:'perception',
  forms:{praesens:{ich:'spreche',du:'sprichst',er:'spricht'},perfekt:'hat gesprochen',praeteritum:'sprach'},
  ex_de:'Sie spricht drei Sprachen.',ex_en:'She speaks three languages.'},
{id:'v090',de:'lesen',article:'',plural:'',en:'to read',type:'verb',level:'A2',topic:'perception',
  forms:{praesens:{ich:'lese',du:'liest',er:'liest'},perfekt:'hat gelesen',praeteritum:'las'},
  ex_de:'Er liest ein Buch.',ex_en:'He is reading a book.'},
{id:'v091',de:'schreiben',article:'',plural:'',en:'to write',type:'verb',level:'A2',topic:'perception',
  forms:{praesens:{ich:'schreibe',du:'schreibst',er:'schreibt'},perfekt:'hat geschrieben',praeteritum:'schrieb'},
  ex_de:'Ich schreibe eine E-Mail.',ex_en:'I am writing an email.'},
{id:'v092',de:'helfen',article:'',plural:'',en:'to help',type:'verb',level:'A2',topic:'perception',
  forms:{praesens:{ich:'helfe',du:'hilfst',er:'hilft'},perfekt:'hat geholfen',praeteritum:'half'},
  ex_de:'Kannst du mir helfen?',ex_en:'Can you help me?'},

// --- Dativ-related nouns / prepositions ---
{id:'v093',de:'geben',article:'',plural:'',en:'to give',type:'verb',level:'A2',topic:'dativ',
  forms:{praesens:{ich:'gebe',du:'gibst',er:'gibt'},perfekt:'hat gegeben',praeteritum:'gab'},
  ex_de:'Ich gebe dir das Buch.',ex_en:'I am giving you the book.'},
{id:'v094',de:'das Buch',article:'das',plural:'die Bücher',en:'book',type:'noun',level:'A1',topic:'dativ',ex_de:'Das Buch ist interessant.',ex_en:'The book is interesting.'},
{id:'v095',de:'der Freund',article:'der',plural:'die Freunde',en:'friend (m)',type:'noun',level:'A1',topic:'dativ',ex_de:'Ich helfe meinem Freund.',ex_en:'I am helping my friend.'},
{id:'v096',de:'die Freundin',article:'die',plural:'die Freundinnen',en:'friend (f)',type:'noun',level:'A1',topic:'dativ',ex_de:'Ich schreibe meiner Freundin.',ex_en:'I am writing to my friend (f).'},
{id:'v097',de:'mit',article:'',plural:'',en:'with',type:'phrase',level:'A2',topic:'dativ',ex_de:'Ich fahre mit dem Bus.',ex_en:'I travel by bus.'},
{id:'v098',de:'nach',article:'',plural:'',en:'to / after',type:'phrase',level:'A2',topic:'dativ',ex_de:'Wir fahren nach Hause.',ex_en:'We are driving home.'},
{id:'v099',de:'zu',article:'',plural:'',en:'to',type:'phrase',level:'A2',topic:'dativ',ex_de:'Ich gehe zu meiner Mutter.',ex_en:'I am going to my mother\u2019s.'},

// --- adjectives (general) ---
{id:'v100',de:'groß',article:'',plural:'',en:'big / tall',type:'adj',level:'A1',topic:'adjectives',ex_de:'Das Haus ist groß.',ex_en:'The house is big.'},
{id:'v101',de:'klein',article:'',plural:'',en:'small',type:'adj',level:'A1',topic:'adjectives',ex_de:'Die Wohnung ist klein.',ex_en:'The apartment is small.'},
{id:'v102',de:'gut',article:'',plural:'',en:'good',type:'adj',level:'A1',topic:'adjectives',ex_de:'Das Essen ist gut.',ex_en:'The food is good.'},
{id:'v103',de:'schlecht',article:'',plural:'',en:'bad',type:'adj',level:'A1',topic:'adjectives',ex_de:'Das Wetter ist schlecht.',ex_en:'The weather is bad.'},
{id:'v104',de:'schön',article:'',plural:'',en:'beautiful',type:'adj',level:'A1',topic:'adjectives',ex_de:'Die Stadt ist schön.',ex_en:'The city is beautiful.'},
{id:'v105',de:'müde',article:'',plural:'',en:'tired',type:'adj',level:'A1',topic:'adjectives',ex_de:'Ich bin müde.',ex_en:'I am tired.'},
{id:'v106',de:'hungrig',article:'',plural:'',en:'hungry',type:'adj',level:'A1',topic:'adjectives',ex_de:'Das Kind ist hungrig.',ex_en:'The child is hungry.'},
{id:'v107',de:'wichtig',article:'',plural:'',en:'important',type:'adj',level:'A2',topic:'adjectives',ex_de:'Das ist sehr wichtig.',ex_en:'That is very important.'},

// --- house / transport (used in reading & Akkusativ lesson) ---
{id:'v108',de:'das Haus',article:'das',plural:'die Häuser',en:'house',type:'noun',level:'A1',topic:'house',ex_de:'Wir kaufen ein Haus.',ex_en:'We are buying a house.'},
{id:'v109',de:'die Wohnung',article:'die',plural:'die Wohnungen',en:'apartment',type:'noun',level:'A1',topic:'house',ex_de:'Ich suche eine Wohnung.',ex_en:'I am looking for an apartment.'},
{id:'v110',de:'das Zimmer',article:'das',plural:'die Zimmer',en:'room',type:'noun',level:'A1',topic:'house',ex_de:'Das Zimmer hat ein Fenster.',ex_en:'The room has a window.'},
{id:'v111',de:'der Bus',article:'der',plural:'die Busse',en:'bus',type:'noun',level:'A1',topic:'transport',ex_de:'Ich nehme den Bus.',ex_en:'I am taking the bus.'},
{id:'v112',de:'der Zug',article:'der',plural:'die Züge',en:'train',type:'noun',level:'A1',topic:'transport',ex_de:'Der Zug kommt um neun.',ex_en:'The train arrives at nine.'},
{id:'v113',de:'das Auto',article:'das',plural:'die Autos',en:'car',type:'noun',level:'A1',topic:'transport',ex_de:'Ich habe kein Auto.',ex_en:'I do not have a car.'},

// --- Added: words referenced as grammar examples elsewhere but missing from the searchable dictionary ---
{id:'v114',de:'der Tisch',article:'der',plural:'die Tische',en:'table',type:'noun',level:'A1',topic:'house',ex_de:'Der Tisch ist groß.',ex_en:'The table is big.'},
{id:'v115',de:'der Stuhl',article:'der',plural:'die Stühle',en:'chair',type:'noun',level:'A1',topic:'house',ex_de:'Der Stuhl ist neu.',ex_en:'The chair is new.'},
{id:'v116',de:'das Mädchen',article:'das',plural:'die Mädchen',en:'girl',type:'noun',level:'A1',topic:'family',ex_de:'Das Mädchen lernt Deutsch.',ex_en:'The girl is learning German. (neuter due to the -chen ending, not natural gender)'},
{id:'v117',de:'die Tasche',article:'die',plural:'die Taschen',en:'bag',type:'noun',level:'A1',topic:'food',ex_de:'Ich brauche eine Tasche.',ex_en:'I need a bag.'},
];

/* ---------------- GRAMMAR TOPICS ---------------- */
const GRAMMAR = [
{
  id:'g_gender', level:'A1', category:'articles', title:'Nouns & Gender (der / die / das)',
  explanation:'Every German noun has a grammatical gender — masculine (der), feminine (die), or neuter (das). Gender is mostly not predictable from meaning, so it is learned together with each new word, not applied afterward.',
  rules:[
    'Always learn a noun together with its article: not "Tisch" but "der Tisch".',
    'Plural forms replace the article with die, regardless of the original gender: der Tisch → die Tische.',
    'Some endings are strong hints: words ending in -ung, -heit, -keit, -schaft are almost always die. Words ending in -chen or -lein are always das (diminutives).',
  ],
  examples:[
    {de:'der Tisch, die Tische', en:'the table, the tables'},
    {de:'die Wohnung, die Wohnungen', en:'the apartment, the apartments'},
    {de:'das Kind, die Kinder', en:'the child, the children'},
  ],
  mistakes:['Guessing gender from the English meaning (e.g. assuming "das Mädchen" should be feminine because it means "girl" — it is das, because -chen nouns are always neuter).'],
},
{
  id:'g_praesens', level:'A1', category:'verb-conjugation', title:'Present Tense (Präsens) Conjugation',
  explanation:'German verbs change their ending depending on who is doing the action. Regular verbs follow a predictable pattern; some common verbs are irregular and change their stem vowel for du/er/sie/es.',
  rules:[
    'Regular pattern: ich -e, du -st, er/sie/es -t, wir -en, ihr -t, sie/Sie -en.',
    'Verbs with a stem ending in -t or -d add an extra e: du arbeitest, er arbeitet.',
    'Some strong verbs change their vowel only in the du and er/sie/es forms: fahren → du fährst, er fährt; sprechen → du sprichst, er spricht.',
    'The conjugated verb is always the second element of a normal statement, even if something else starts the sentence.',
  ],
  examples:[
    {de:'Ich lerne Deutsch. Du lernst Deutsch. Er lernt Deutsch.', en:'I learn German. You learn German. He learns German.'},
    {de:'Heute arbeite ich lange.', en:'Today I work long. (verb stays in 2nd position)'},
  ],
  mistakes:['Forgetting the vowel change in du/er forms of strong verbs: "du fahrst" instead of the correct "du fährst".'],
},
{
  id:'g_akkusativ', level:'A1', category:'akkusativ', title:'The Accusative Case (Akkusativ)',
  explanation:'The accusative case marks the direct object of a sentence — the thing that directly receives the action. In German, only the masculine article actually changes in the accusative: der → den. die, das and die (plural) stay the same.',
  rules:[
    'Masculine: der → den (ein → einen). Feminine: die stays die (eine stays eine). Neuter: das stays das (ein stays ein). Plural: die stays die.',
    'Ask "wen oder was?" (whom or what?) to find the accusative object: "Ich kaufe den Apfel" — Was kaufe ich? Den Apfel.',
    'Many common verbs take a direct object in the accusative: kaufen, haben, brauchen, sehen, essen, trinken, lesen.',
  ],
  examples:[
    {de:'Ich kaufe den Apfel.', en:'I am buying the apple. (der Apfel → den Apfel)'},
    {de:'Ich brauche eine Tasche.', en:'I need a bag. (die Tasche stays die/eine)'},
    {de:'Ich habe ein Auto.', en:'I have a car. (das Auto stays das/ein)'},
  ],
  mistakes:['Using "der" instead of "den" for masculine direct objects — this is the single most common German case mistake for beginners.'],
},
{
  id:'g_dativ', level:'A2', category:'dativ', title:'The Dative Case (Dativ)',
  explanation:'The dative case marks the indirect object — usually the person who receives something. It also follows a fixed set of prepositions such as mit, nach, zu, von, bei, aus.',
  rules:[
    'Masculine: der → dem (ein → einem). Feminine: die → der (eine → einer). Neuter: das → dem (ein → einem). Plural: die → den (and add -n to the noun if possible: den Kindern).',
    'Ask "wem?" (to/for whom?) to find the dative object: "Ich gebe dem Kind das Buch" — Wem gebe ich das Buch? Dem Kind.',
    'Verbs that typically take a dative object: geben, helfen, danken, gehören, gefallen.',
    'Prepositions that always take the dative: mit, nach, zu, von, bei, aus, seit.',
  ],
  examples:[
    {de:'Ich helfe meinem Freund.', en:'I am helping my friend. (der Freund → meinem Freund)'},
    {de:'Ich fahre mit dem Bus.', en:'I am traveling by bus. (mit + dative)'},
    {de:'Ich gebe der Frau das Geld.', en:'I am giving the woman the money. (die Frau → der Frau)'},
  ],
  mistakes:['Mixing up der/den (accusative masculine) with dem (dative masculine) — check which case the verb or preposition requires first.'],
},
{
  id:'g_wordorder', level:'A2', category:'word-order', title:'Word Order: Main and Subordinate Clauses',
  explanation:'In a main clause, the conjugated verb is always the second element. In a subordinate clause introduced by words like weil (because) or dass (that), the conjugated verb moves to the very end.',
  rules:[
    'Main clause: Subject/Time/Other — VERB — rest of sentence.',
    'Subordinate clause with weil/dass/wenn: the conjugated verb is pushed to the end of the clause.',
    'A subordinate clause can come first in the sentence; if it does, the main clause verb comes immediately after the comma (still "second position" overall).',
  ],
  examples:[
    {de:'Ich lerne Deutsch, weil ich in Deutschland arbeiten will.', en:'I am learning German because I want to work in Germany.'},
    {de:'Weil es regnet, bleibe ich zu Hause.', en:'Because it is raining, I am staying home.'},
  ],
  mistakes:['Keeping normal word order after weil: "weil ich lerne Deutsch" is wrong — the verb must move to the end: "weil ich Deutsch lerne".'],
},
{
  id:'g_modal', level:'A2', category:'modal-verbs', title:'Modal Verbs',
  explanation:'Modal verbs (können, müssen, wollen, dürfen, sollen, möchten) express ability, necessity, desire, permission or obligation. They are almost always used together with a second verb in the infinitive, which goes to the very end of the sentence.',
  rules:[
    'The modal verb is conjugated and takes position two; the main verb stays in the infinitive at the end.',
    'können = can/ability, müssen = must/necessity, wollen = want, dürfen = may/permission, sollen = supposed to, möchten = would like (polite form of wollen).',
    'Modal verbs in the ich and er/sie/es forms have no ending: ich kann, er kann (not "kannt").',
  ],
  examples:[
    {de:'Ich muss heute arbeiten.', en:'I have to work today.'},
    {de:'Kannst du mir helfen?', en:'Can you help me?'},
    {de:'Wir möchten einen Kaffee bestellen.', en:'We would like to order a coffee.'},
  ],
  mistakes:['Forgetting to send the main verb to the end: "Ich kann sprechen Deutsch" instead of the correct "Ich kann Deutsch sprechen".'],
},
{
  id:'g_perfekt', level:'A2', category:'perfekt', title:'Talking About the Past: Perfekt',
  explanation:'In spoken German, the Perfekt tense is the normal way to talk about the past. It is built with a helper verb (haben or sein) conjugated in position two, plus a past participle (Partizip II) at the end of the sentence.',
  rules:[
    'Most verbs use haben as the helper. Verbs of motion or change of state (gehen, kommen, fahren, sein) use sein.',
    'Regular (weak) verbs form the participle as ge- + stem + -t: machen → gemacht, kaufen → gekauft.',
    'Irregular (strong) verbs form the participle as ge- + stem (often changed) + -en, and must be learned individually: sehen → gesehen, sprechen → gesprochen, gehen → gegangen.',
    'Separable verbs place ge- between the prefix and the stem: aufstehen → aufgestanden.',
  ],
  examples:[
    {de:'Ich habe Deutsch gelernt.', en:'I learned German. (learn → haben + gelernt)'},
    {de:'Wir sind nach Berlin gefahren.', en:'We traveled to Berlin. (motion → sein + gefahren)'},
    {de:'Er ist um sieben aufgestanden.', en:'He got up at seven. (separable verb → sein + aufgestanden)'},
  ],
  mistakes:['Using haben with a motion verb: "Ich habe gegangen" is wrong — gehen takes sein: "Ich bin gegangen".'],
},
];

/* ---------------- LESSONS ---------------- */
/* Each lesson: intro text + vocabIds (for the vocab strip) + optional grammarId
   + an ordered array of exercises. Exercise types: mcq | fill | build
   category tags feed the weakness engine. */
const LESSONS = [
{
  id:'l01', level:'A1', order:1, title:'Alphabet & Pronunciation', topic:'pronunciation',
  prereq:[],
  goal:'Recognize and pronounce the German sounds that differ most from English.',
  why:'Getting pronunciation patterns right from the start makes every word you learn afterward easier to say and understand.',
  intro:'German spelling is very regular once you know the sound rules. This lesson covers the letters and sound combinations that differ most from English.',
  vocabIds:[], grammarId:null,
  teach:[
    {h:'The umlauts', p:'ä, ö and ü change the sound of a, o and u. ä sounds like the "e" in "bed"; ö has no English equivalent (round your lips while saying "e"); ü is like French "u" — round your lips while saying "ee".'},
    {h:'ch', p:'After a, o, u it is a rough back-of-throat sound (Bach, Buch). After e, i, ä, ö, ü and consonants it is a soft "hy"-like sound (ich, München).'},
    {h:'sch, sp, st', p:'sch = English "sh" (Schule). At the start of a word, sp and st are pronounced "shp" and "sht" (sprechen → "shprechen", Stadt → "shtat").'},
    {h:'ei vs ie', p:'ei sounds like English "eye" (mein, Wein). ie sounds like English "ee" (Sie, Bier). These are commonly reversed by learners.'},
  ],
  commonMistake:'Reading "ei" as "ee" and "ie" as "eye" — it is the opposite of what English spelling suggests, so this reverses for almost every learner at first.',
  sentenceProgression:{
    title:'From sound to real exchange: "heißen"',
    steps:[
      {de:'heißen', en:'to be called', note:'Notice the ß (scharfes S, pronounced like "ss") and the "ei" sound (like English "eye").'},
      {de:'Wie heißt du?', en:'What is your name?', note:'A whole question built from one verb. "ei" appears twice — practice saying it like "eye", not "ee".'},
      {de:'Ich heiße Sara.', en:'My name is Sara.', note:'The answer pattern. Say it slowly: ICH-HY-suh SAH-rah.'},
      {de:'Ich heiße Sara. Und wie heißt du?', en:'My name is Sara. And what is your name?', note:'"Und" (and) links your answer to a question back — this is how a real exchange starts.'},
    ],
  },
  exercises:[
    {id:'l01e1', type:'mcq', category:'pronunciation', prompt:'Which word contains the "eye" sound (as in English "my")?',
      options:['Bier','mein','Sie','wie'], correct:'mein',
      explain:'"ei" is pronounced like English "eye". "ie" (as in Bier, Sie, wie) is pronounced like English "ee".'},
    {id:'l01e2', type:'mcq', category:'pronunciation', prompt:'Which letter combination makes the "sh" sound at the start of "Schule"?',
      options:['sp','ch','sch','st'], correct:'sch',
      explain:'"sch" is always pronounced like English "sh", as in "Schule" (school).'},
    {id:'l01e3', type:'mcq', category:'pronunciation', prompt:'How is "Stadt" (city) pronounced at the start?',
      options:['"stat"','"shtat"','"sdatt"','"ztat"'], correct:'"shtat"',
      explain:'At the start of a word or syllable, "st" is pronounced "sht" — so "Stadt" sounds like "Shtat".'},
  ],
},
{
  id:'l02', level:'A1', order:2, title:'Greetings & Introductions', topic:'greetings',
  prereq:['l01'],
  goal:'Introduce yourself and greet people appropriately in formal and informal situations.',
  why:'Greetings and self-introduction are usually the very first real conversation you will have in German.',
  intro:'Learn to greet people and introduce yourself using sein, heißen and kommen.',
  vocabIds:['v001','v002','v006','v014','v015','v016','v017','v018','v019','v020','v021','v022','v023'],
  grammarId:'g_praesens',
  teach:[
    {h:'Introducing yourself', p:'Use "Ich heiße..." (my name is...) or "Ich bin..." (I am...) to give your name. Use "Ich komme aus..." to say where you are from, and "Ich wohne in..." to say where you live.'},
    {h:'Formal vs informal', p:'Use "du" with friends, family, and children. Use "Sie" with strangers, in shops, and at work until invited to use "du". "Wie heißt du?" (informal) vs "Wie heißen Sie?" (formal).'},
  ],
  commonMistake:'Using "du" with strangers or in professional settings — when in doubt, start with "Sie" and switch only if invited to.',
  sentenceProgression:{
    title:'From word to real sentence: "kommen"',
    steps:[
      {de:'kommen', en:'to come', note:'The infinitive — the dictionary form, not yet usable in a sentence on its own.'},
      {de:'Ich komme.', en:'I come. / I’m coming.', note:'Conjugated for "ich" (drop -en, add -e). This alone is already a complete sentence.'},
      {de:'Ich komme aus Pakistan.', en:'I come from Pakistan.', note:'Add "aus" (from) plus a country to say where you’re from.'},
      {de:'Ich komme aus Pakistan und wohne in Berlin.', en:'I come from Pakistan and live in Berlin.', note:'Join two facts about yourself with "und" (and) — "wohne" doesn’t need its own "ich", since it shares the same subject.'},
    ],
  },
  exercises:[
    {id:'l02e1', type:'mcq', category:'verb-conjugation', prompt:'Complete: "Ich ___ Sara." (My name is Sara.)',
      options:['heißt','heiße','heißen','heißest'], correct:'heiße',
      explain:'With "ich", regular verbs take the ending -e: ich heiße.'},
    {id:'l02e2', type:'mcq', category:'verb-conjugation', prompt:'Complete: "Woher ___ du?" (Where are you from?)',
      options:['kommst','komme','kommt','kommen'], correct:'kommst',
      explain:'With "du", regular verbs take the ending -st: du kommst.'},
    {id:'l02e3', type:'fill', category:'greetings', prompt:'Translate: "Good morning!"',
      accept:['guten morgen'], explain:'"Guten Morgen!" is used until around 10-11am.'},
    {id:'l02e4', type:'mcq', category:'greetings', prompt:'You are speaking formally to a stranger. How do you ask their name?',
      options:['Wie heißt du?','Wie heißen Sie?','Wie heißen wir?','Wie heißt ihr?'], correct:'Wie heißen Sie?',
      explain:'"Sie" is the formal form and is used with people you do not know well.'},
    {id:'l02e5', type:'build', category:'word-order', prompt:'Put the words in order: "I come from Pakistan."',
      words:['Pakistan.','komme','Ich','aus'], correctOrder:['Ich','komme','aus','Pakistan.'],
      explain:'German main-clause order: subject, then the conjugated verb in position two, then the rest.'},
  ],
},
{
  id:'l03', level:'A1', order:3, title:'Numbers & Age', topic:'numbers',
  prereq:['l02'],
  goal:'Count, state your age, and understand numbers in everyday contexts.',
  why:'Numbers come up constantly — prices, ages, phone numbers, addresses, times.',
  commonMistake:'Using "haben" for age (as some other languages do): "Ich habe zwanzig Jahre" is wrong — German uses "sein": "Ich bin zwanzig Jahre alt."',
  intro:'Count from 0-100 and learn to talk about age using "sein" + years.',
  vocabIds:['v024','v025','v026','v027','v028','v029','v030','v031','v032','v033','v034','v035','v036','v037','v038'],
  grammarId:null,
  teach:[
    {h:'Saying your age', p:'German uses "sein" (to be), not "haben", for age: "Ich bin zwanzig Jahre alt" (I am twenty years old) — literally "I am twenty years old", matching English structure with sein, not the "haben" pattern some other languages use.'},
    {h:'Numbers 21-99', p:'Numbers between 21 and 99 are built backwards compared to English: einundzwanzig = "one-and-twenty" = 21. zweiunddreißig = "two-and-thirty" = 32.'},
  ],
  sentenceProgression:{
    title:'From word to real exchange: talking about age',
    steps:[
      {de:'alt', en:'old', note:'A simple adjective on its own.'},
      {de:'zwanzig Jahre alt', en:'twenty years old', note:'Add a number and "Jahre" (years) in front of "alt" — this whole phrase behaves as one unit.'},
      {de:'Ich bin zwanzig Jahre alt.', en:'I am twenty years old.', note:'"sein" (bin) + the phrase above = a full sentence about your age.'},
      {de:'Wie alt bist du? — Ich bin zwanzig Jahre alt.', en:'How old are you? — I am twenty years old.', note:'The natural question-and-answer pair you’ll actually use.'},
    ],
  },
  exercises:[
    {id:'l03e1', type:'mcq', category:'vocab', prompt:'What is "fünfzehn"?', options:['5','15','50','55'], correct:'15',
      explain:'"fünf" = five, "-zehn" = -teen, so fünfzehn = fifteen.'},
    {id:'l03e2', type:'fill', category:'vocab', prompt:'Write the German word for the number 7.',
      accept:['sieben'], explain:'7 = sieben.'},
    {id:'l03e3', type:'mcq', category:'grammar', prompt:'Complete: "Ich ___ dreißig Jahre alt." (I am thirty years old.)',
      options:['habe','bin','mache','werde'], correct:'bin',
      explain:'German expresses age with "sein" (to be): Ich bin ... Jahre alt.'},
  ],
},
{
  id:'l04', level:'A1', order:4, title:'Family', topic:'family',
  prereq:['l02'],
  goal:'Talk about your family members using correct articles and haben.',
  why:'Family is one of the most common early conversation topics, and it gives you a natural way to practice noun genders.',
  intro:'Talk about your family members using "haben" and learn key family vocabulary.',
  vocabIds:['v039','v040','v041','v042','v043','v044','v045','v046','v047','v048','v049'],
  grammarId:'g_gender',
  teach:[
    {h:'Gender check', p:'Notice: der Bruder, der Sohn, der Vater, der Mann are all "der" (masculine). die Schwester, die Tochter, die Mutter, die Frau are all "die" (feminine). das Kind is neuter.'},
    {h:'"haben" for family', p:'"Ich habe einen Bruder" (I have a brother) — notice "einen", not "ein": this is the accusative case, covered in the next lesson.'},
  ],
  sentenceProgression:{
    title:'From word to real sentence: "der Bruder"',
    steps:[
      {de:'der Bruder', en:'the brother', note:'Masculine noun — remember it as "der Bruder", not just "Bruder".'},
      {de:'einen Bruder', en:'a brother', note:'As the object of "haben", "der" becomes "einen" — you’ll learn the full rule for this in the Akkusativ lesson soon.'},
      {de:'Ich habe einen Bruder.', en:'I have a brother.', note:'A complete sentence about your family.'},
      {de:'Ich habe einen Bruder und eine Schwester.', en:'I have a brother and a sister.', note:'"die Schwester" stays "eine Schwester" here — only masculine nouns change in this position.'},
    ],
  },
  exercises:[
    {id:'l04e1', type:'mcq', category:'articles', prompt:'What is the article for "Schwester" (sister)?',
      options:['der','die','das'], correct:'die', explain:'die Schwester — feminine family words are usually die (Mutter, Schwester, Tochter, Frau).'},
    {id:'l04e2', type:'mcq', category:'articles', prompt:'What is the article for "Kind" (child)?',
      options:['der','die','das'], correct:'das', explain:'das Kind is neuter — it does not follow the natural gender of the child.'},
    {id:'l04e3', type:'fill', category:'vocab', prompt:'Translate: "grandmother" is "die Großmutter". What is "grandfather"?',
      accept:['der grossvater','der großvater'], explain:'der Großvater (grandfather) — groß (big) + Vater (father).'},
    {id:'l04e4', type:'mcq', category:'verb-conjugation', prompt:'Complete: "Er ___ eine Schwester." (He has a sister.)',
      options:['habe','hast','hat','haben'], correct:'hat', explain:'"haben" is irregular: er/sie/es hat (not "habt").'},
    {id:'l04e5', type:'correct', category:'articles', prompt:'This sentence has a gender mistake. Type the corrected version.',
      wrong:'Der Schwester ist nett.', accept:['die schwester ist nett'],
      explain:'"Schwester" is feminine (die Schwester), so the article must be "die", not "der": Die Schwester ist nett.'},
  ],
},
{
  id:'l05', level:'A1', order:5, title:'Daily Routine', topic:'routine',
  prereq:['l02','l04'],
  goal:'Describe your daily routine using present-tense verbs and frequency words.',
  why:'Talking about routines is one of the most common real conversation topics, and it reinforces verb conjugation through repetition.',
  intro:'Describe your day using common verbs and time expressions like immer, oft, manchmal, nie.',
  vocabIds:['v050','v051','v052','v053','v054','v055','v056','v057','v058','v059','v060','v061','v062','v063'],
  grammarId:'g_praesens',
  teach:[
    {h:'Separable verbs', p:'"aufstehen" (to get up) splits in a main clause: the prefix "auf" moves to the very end. "Ich stehe um sieben Uhr auf" (I get up at seven o\u2019clock).'},
    {h:'Frequency words', p:'immer (always) > oft (often) > manchmal (sometimes) > selten (rarely) > nie (never). They usually appear right after the conjugated verb.'},
  ],
  sentenceProgression:{
    title:'From word to real sentence: "gehen"',
    steps:[
      {de:'gehen', en:'to go', note:'Start with the bare infinitive \u2014 this is what you\u2019ll find in a dictionary.'},
      {de:'Ich gehe.', en:'I go. / I\u2019m going.', note:'Conjugate it for "ich" and you already have a complete, correct sentence.'},
      {de:'Ich gehe nach Hause.', en:'I\u2019m going home.', note:'Add a destination with "nach Hause" (a fixed phrase meaning "home[ward]").'},
      {de:'Ich gehe heute nach Hause.', en:'I\u2019m going home today.', note:'Adding "heute" (today) doesn\u2019t change word order here \u2014 it slots in after the verb.'},
      {de:'Heute gehe ich um sieben Uhr nach Hause.', en:'Today I\u2019m going home at seven o\u2019clock.', note:'Front the time word "Heute" for emphasis, and the verb "gehe" automatically jumps back to position two \u2014 "ich" moves after it. This is the verb-second rule in action.'},
    ],
  },
  exercises:[
    {id:'l05e1', type:'build', category:'word-order', prompt:'Order the words: "I get up at seven o\u2019clock."',
      words:['auf.','Uhr','sieben','Ich','um','stehe'], correctOrder:['Ich','stehe','um','sieben','Uhr','auf.'],
      explain:'"aufstehen" is separable: "stehe" stays in position two, "auf" goes to the end.'},
    {id:'l05e2', type:'mcq', category:'verb-conjugation', prompt:'Complete: "Das Kind ___ schon." (The child is already sleeping.)',
      options:['schlafe','schläfst','schläft','schlafen'], correct:'schläft',
      explain:'"schlafen" changes its vowel in the er/sie/es form: schläft.'},
    {id:'l05e3', type:'mcq', category:'vocab', prompt:'Which word means "never"?', options:['immer','oft','nie','manchmal'], correct:'nie',
      explain:'nie = never. immer = always, oft = often, manchmal = sometimes.'},
    {id:'l05e4', type:'fill', category:'vocab', prompt:'Translate: "I always drink coffee." (use "immer")',
      accept:['ich trinke immer kaffee','immer trinke ich kaffee'], explain:'Frequency words like "immer" typically come right after the conjugated verb, though fronting it ("Immer trinke ich Kaffee") is also correct German for emphasis.'},
  ],
},
{
  id:'l06', level:'A1', order:6, title:'Food & Shopping', topic:'food',
  prereq:['l05'],
  goal:'Buy groceries and talk about food, meeting the accusative case for the first time.',
  why:'Shopping is an everyday real-life task, and kaufen/brauchen give you a natural, low-stakes way to meet the accusative case before studying it formally in the next lesson.',
  intro:'Buy groceries and talk about food, using the accusative case for the first time.',
  vocabIds:['v064','v065','v066','v067','v068','v069','v070','v071','v072','v073','v074','v075','v076'],
  grammarId:'g_akkusativ',
  teach:[
    {h:'"Ich kaufe den Apfel"', p:'"kaufen" takes a direct object in the accusative case. Watch what happens to masculine "der": "der Apfel" → "den Apfel". Feminine and neuter nouns do not change.'},
  ],
  commonMistake:'Forgetting to change "der" to "den" for masculine direct objects while correctly leaving "die" and "das" unchanged — the most common beginner Akkusativ slip.',
  sentenceProgression:{
    title:'From word to real sentence: "der Apfel"',
    steps:[
      {de:'der Apfel', en:'the apple', note:'Masculine noun, plural "die Äpfel".'},
      {de:'einen Apfel', en:'an apple', note:'As a direct object (what you’re buying), masculine "ein" becomes "einen".'},
      {de:'Ich kaufe einen Apfel.', en:'I am buying an apple.', note:'Subject + verb + accusative object — the basic shopping sentence.'},
      {de:'Ich kaufe einen Apfel und eine Banane.', en:'I am buying an apple and a banana.', note:'"die Banane" stays "eine Banane" — only the masculine word changed.'},
    ],
  },
  exercises:[
    {id:'l06e1', type:'mcq', category:'akkusativ', prompt:'Complete: "Ich kaufe ___ Apfel." (der Apfel)',
      options:['der','den','dem','die'], correct:'den',
      explain:'"der Apfel" is masculine, and in the accusative (direct object) masculine "der" becomes "den".'},
    {id:'l06e2', type:'mcq', category:'akkusativ', prompt:'Complete: "Ich brauche ___ Banane." (die Banane)',
      options:['die','den','der','das'], correct:'die',
      explain:'Feminine "die" does not change in the accusative: die Banane → die Banane.'},
    {id:'l06e3', type:'mcq', category:'akkusativ', prompt:'Complete: "Wir haben ___ Wasser." (das Wasser)',
      options:['das','den','dem','der'], correct:'das',
      explain:'Neuter "das" does not change in the accusative.'},
    {id:'l06e4', type:'fill', category:'vocab', prompt:'Translate: "The bread is cheap."',
      accept:['das brot ist billig'], explain:'billig = cheap, teuer = expensive.'},
    {id:'l06e5', type:'match', category:'vocab', prompt:'Match each German food word to its English meaning.',
      pairs:[{de:'das Brot',en:'bread'},{de:'der Apfel',en:'apple'},{de:'das Wasser',en:'water'},{de:'der Kaffee',en:'coffee'}],
      explain:'These are the core food words from this lesson \u2014 worth over-learning since they come up constantly.'},
  ],
},
{
  id:'l07', level:'A1', order:7, title:'The Cases: Nominativ & Akkusativ', topic:'grammar',
  prereq:['l06'],
  goal:'Understand systematically why German sentences use der vs. den, and identify the subject vs. the object in a sentence.',
  why:'Once this single masculine-article rule clicks, most beginner case mistakes disappear — it is the single highest-leverage grammar rule at this level.',
  intro:'A closer, more systematic look at the two cases you have used so far.',
  vocabIds:['v094','v108','v109','v113'],
  grammarId:'g_akkusativ',
  teach:[
    {h:'Nominativ vs Akkusativ', p:'The nominative marks the subject (who/what performs the action): "Der Mann kauft ein Auto." Here "der Mann" is nominative (subject), "ein Auto" is accusative (direct object) — but "ein" is neuter here so it does not visibly change.'},
    {h:'The key change to memorize', p:'Only the masculine article changes between nominative and accusative: der/ein → den/einen. Everything else (die, das, plural die) stays identical in both cases. This single rule covers most of what you need at this level.'},
  ],
  sentenceProgression:{
    title:'The same word, two roles: "der Zug"',
    steps:[
      {de:'der Zug', en:'the train', note:'Masculine noun, its dictionary (nominative) form.'},
      {de:'den Zug', en:'the train (as an object)', note:'The identical word, but now as what’s being seen — masculine "der" must become "den".'},
      {de:'Ich sehe den Zug.', en:'I see the train.', note:'"Ich" is the subject (nominative); "den Zug" is the object (accusative).'},
      {de:'Der Mann sieht den Zug.', en:'The man sees the train.', note:'Now compare two "der"-words in one sentence: "der Mann" stays "der" (it’s the subject), while "der Zug" becomes "den Zug" (it’s the object). Same original article, different job, different form.'},
    ],
  },
  exercises:[
    {id:'l07e1', type:'mcq', category:'akkusativ', prompt:'"Der Mann sieht ___ Zug." (der Zug) — which is correct?',
      options:['der Zug','den Zug','dem Zug','des Zug'], correct:'den Zug',
      explain:'"der Zug" is the direct object here (what does the man see?), so masculine der → den.'},
    {id:'l07e2', type:'mcq', category:'akkusativ', prompt:'Which sentence element is in the nominative case in "Die Frau kauft das Haus"?',
      options:['die Frau','das Haus','kauft'], correct:'die Frau',
      explain:'"die Frau" is the subject performing the action, so it is in the nominative case.'},
    {id:'l07e3', type:'fill', category:'akkusativ', prompt:'Translate using the accusative: "I have a car." (das Auto → ein Auto)',
      accept:['ich habe ein auto'], explain:'"das Auto" is neuter, so "ein" does not change in the accusative: ich habe ein Auto.'},
    {id:'l07e4', type:'correct', category:'akkusativ', prompt:'This sentence has an Akkusativ mistake. Type the corrected version.',
      wrong:'Ich sehe der Zug.', accept:['ich sehe den zug'],
      explain:'"der Zug" is the direct object here (what do I see?), so masculine "der" must become "den": Ich sehe den Zug.'},
  ],
},
{
  id:'l08', level:'A1', order:8, title:'Time & Appointments', topic:'time',
  prereq:['l07'],
  goal:'Make and discuss appointments using können and müssen.',
  why:'Scheduling — “can you come”, “I have to work” — is essential for both work and daily life in German.',
  intro:'Talk about appointments and obligations using können and müssen.',
  vocabIds:['v077','v078','v079','v080','v081'],
  grammarId:'g_modal',
  teach:[
    {h:'Modal + infinitive at the end', p:'"Ich muss um acht Uhr arbeiten" — the modal verb "muss" takes position two, and the main verb "arbeiten" goes all the way to the end of the sentence.'},
  ],
  sentenceProgression:{
    title:'From word to real exchange: "der Termin"',
    steps:[
      {de:'der Termin', en:'the appointment', note:'Masculine noun, plural "die Termine".'},
      {de:'einen Termin', en:'an appointment', note:'As an object of "haben", "der" becomes "einen" — the same Akkusativ pattern from earlier lessons.'},
      {de:'Ich habe morgen einen Termin.', en:'I have an appointment tomorrow.', note:'"morgen" (tomorrow) slots in right after the verb.'},
      {de:'Ich habe morgen einen Termin. Kannst du morgen kommen?', en:'I have an appointment tomorrow. Can you come tomorrow?', note:'The modal "Kannst" leads the question, and "kommen" — the actual verb — waits until the very end.'},
    ],
  },
  exercises:[
    {id:'l08e1', type:'build', category:'modal-verbs', prompt:'Order the words: "Can you come tomorrow?"',
      words:['morgen','du','kommen?','Kannst'], correctOrder:['Kannst','du','morgen','kommen?'],
      explain:'The modal "Kannst" takes position two (here, first, since it is a question); the main verb "kommen" goes to the end.'},
    {id:'l08e2', type:'mcq', category:'modal-verbs', prompt:'Complete: "Ich ___ um acht Uhr arbeiten." (I have to work at eight.)',
      options:['muss','müsse','musst','müssen'], correct:'muss',
      explain:'Modal verbs have no ending in the ich and er/sie/es forms: ich muss, er muss.'},
    {id:'l08e3', type:'fill', category:'vocab', prompt:'Translate: "I have an appointment."',
      accept:['ich habe einen termin'], explain:'"der Termin" is masculine, so the accusative object is "einen Termin".'},
  ],
},
{
  id:'l09', level:'A2', order:9, title:'Talking About the Past: Perfekt', topic:'perfekt',
  prereq:['l07','l08'],
  goal:'Describe things that already happened using the Perfekt tense.',
  why:'Perfekt is how spoken German normally talks about the past — you need it as soon as you want to tell anyone what you did yesterday.',
  intro:'Learn to describe things that already happened using haben/sein + past participle.',
  vocabIds:['v086','v087','v088','v089','v090','v091'],
  grammarId:'g_perfekt',
  teach:[
    {h:'Choosing haben or sein', p:'Ask: does the verb describe motion from A to B, or a change of state? If yes, usually sein (gehen, fahren, kommen, aufstehen). Otherwise, haben (machen, kaufen, lernen, essen, sehen, sprechen).'},
  ],
  sentenceProgression:{
    title:'From word to real sentence: "lernen" in the past',
    steps:[
      {de:'lernen', en:'to learn', note:'The infinitive.'},
      {de:'gelernt', en:'learned', note:'The Partizip II (past participle): regular verbs take ge- + stem + -t.'},
      {de:'Ich habe gelernt.', en:'I learned. / I have learned.', note:'Add the helper verb "habe" (conjugated haben) in position two \u2014 the participle goes to the very end.'},
      {de:'Ich habe Deutsch gelernt.', en:'I learned German.', note:'Insert the object "Deutsch" in the middle \u2014 the participle stays at the end no matter what you add.'},
      {de:'Gestern habe ich drei Stunden Deutsch gelernt.', en:'Yesterday I studied German for three hours.', note:'Front "Gestern" (yesterday) for emphasis: "habe" jumps to position two, "ich" follows it, and "gelernt" is still the very last word.'},
    ],
  },
  exercises:[
    {id:'l09e1', type:'mcq', category:'perfekt', prompt:'Complete: "Wir ___ nach Berlin gefahren." (We traveled to Berlin.)',
      options:['haben','sind','hat','ist'], correct:'sind',
      explain:'"fahren" is a motion verb, so it takes "sein" as its helper: wir sind gefahren.'},
    {id:'l09e2', type:'mcq', category:'perfekt', prompt:'Complete: "Ich ___ Deutsch gelernt." (I learned German.)',
      options:['bin','habe','ist','sind'], correct:'habe',
      explain:'"lernen" is not a motion verb, so it takes "haben": ich habe gelernt.'},
    {id:'l09e3', type:'fill', category:'perfekt', prompt:'Give the Partizip II (past participle) of "sprechen".',
      accept:['gesprochen'], explain:'"sprechen" is a strong verb: gesprochen (not "gesprecht").'},
    {id:'l09e4', type:'build', category:'perfekt', prompt:'Order the words: "He got up at seven." (aufstehen → ist aufgestanden)',
      words:['sieben','aufgestanden.','ist','Er','um'], correctOrder:['Er','ist','um','sieben','aufgestanden.'],
      explain:'The helper verb "ist" takes position two; the participle "aufgestanden" goes to the end.'},
  ],
},
{
  id:'l10', level:'A2', order:10, title:'Modal Verbs in Context', topic:'modal',
  prereq:['l08'],
  goal:'Use the full set of modal verbs naturally, including the polite möchten.',
  why:'Modal verbs let you express permission, obligation, and polite requests — without them German can sound blunt or robotic.',
  intro:'Use the full set of modal verbs — wollen, möchten, dürfen, sollen — in everyday situations.',
  vocabIds:['v082','v083','v084','v085'],
  grammarId:'g_modal',
  teach:[
    {h:'möchten vs wollen', p:'"möchten" is the polite, softer way to say what you want, ideal for ordering food or making requests: "Ich möchte einen Kaffee" sounds more polite than "Ich will einen Kaffee", which can sound blunt or demanding.'},
  ],
  sentenceProgression:{
    title:'From word to real exchange: "möchten"',
    steps:[
      {de:'möchten', en:'would like to', note:'A modal verb — it almost always pairs with another verb or, as here, directly with a noun you want.'},
      {de:'Ich möchte...', en:'I would like...', note:'Conjugated for "ich". Notice: no -e ending like regular verbs — modal verbs are irregular in this way.'},
      {de:'Ich möchte einen Kaffee.', en:'I would like a coffee.', note:'"Kaffee" is the thing wanted — in the accusative, so "der Kaffee" becomes "einen Kaffee".'},
      {de:'Ich möchte einen Kaffee, bitte. Möchtest du auch einen?', en:'I would like a coffee, please. Would you like one too?', note:'"Möchtest du...?" is how you politely ask someone else the same question.'},
    ],
  },
  exercises:[
    {id:'l10e1', type:'mcq', category:'modal-verbs', prompt:'You are ordering coffee politely at a café. What do you say?',
      options:['Ich will einen Kaffee.','Ich möchte einen Kaffee.','Ich muss einen Kaffee.','Ich darf einen Kaffee.'], correct:'Ich möchte einen Kaffee.',
      explain:'"möchte" is the polite form used for requests and orders.'},
    {id:'l10e2', type:'mcq', category:'modal-verbs', prompt:'Complete: "Hier ___ man nicht rauchen." (One is not allowed to smoke here.)',
      options:['kann','muss','darf','soll'], correct:'darf',
      explain:'"dürfen" expresses permission; in the negative it expresses prohibition.'},
    {id:'l10e3', type:'fill', category:'vocab', prompt:'Translate: "You are supposed to be on time." (use "sollen")',
      accept:['du sollst pünktlich sein'], explain:'sollen = to be supposed to / should.'},
  ],
},
{
  id:'l11', level:'A2', order:11, title:'The Dativ Case', topic:'dativ',
  prereq:['l07'],
  goal:'Say who receives something using the dative case and common dative prepositions.',
  why:'Dativ is the other case you will use constantly — for giving things to people, helping someone, and prepositions like mit and nach.',
  intro:'Learn to say who receives something, and use the common dative prepositions mit, nach, zu.',
  vocabIds:['v093','v094','v095','v096','v097','v098','v099'],
  grammarId:'g_dativ',
  teach:[
    {h:'"Wem?" — who receives it?', p:'"Ich gebe dem Kind das Buch" — Wem gebe ich das Buch? Dem Kind. The person receiving the thing is in the dative case.'},
  ],
  commonMistake:'Mixing up "den" (accusative masculine) with "dem" (dative masculine) — always check whether the verb/preposition specifically requires the dative (helfen, mit, nach...) before choosing the form.',
  sentenceProgression:{
    title:'The same word, two people: dative contrast',
    steps:[
      {de:'der Freund / die Freundin', en:'the friend (m) / the friend (f)', note:'Two related nouns with different genders — useful for seeing how each changes differently in the dative.'},
      {de:'meinem Freund / meiner Freundin', en:'to my friend (m) / to my friend (f)', note:'Masculine "der/mein" → "dem/meinem". Feminine "die/meine" → "der/meiner". Different endings for different genders.'},
      {de:'Ich helfe meinem Freund.', en:'I am helping my (male) friend.', note:'"helfen" always takes the dative — there is no accusative option here.'},
      {de:'Ich helfe meinem Freund und meiner Freundin.', en:'I am helping my (male) friend and my (female) friend.', note:'Both dative forms appear side by side, showing the masculine/feminine contrast directly.'},
    ],
  },
  exercises:[
    {id:'l11e1', type:'mcq', category:'dativ', prompt:'Complete: "Ich helfe ___ Freund." (der Freund)',
      options:['der','den','dem','des'], correct:'dem',
      explain:'"helfen" takes the dative: der Freund → dem Freund.'},
    {id:'l11e2', type:'mcq', category:'dativ', prompt:'Complete: "Ich fahre mit ___ Bus." (der Bus)',
      options:['der','den','dem','die'], correct:'dem',
      explain:'"mit" always takes the dative: der Bus → dem Bus.'},
    {id:'l11e3', type:'mcq', category:'dativ', prompt:'Complete: "Ich gebe ___ Frau das Geld." (die Frau)',
      options:['die','der','dem','den'], correct:'der',
      explain:'Feminine "die" becomes "der" in the dative: die Frau → der Frau.'},
    {id:'l11e4', type:'fill', category:'dativ', prompt:'Translate: "I am writing to my friend (f)." (schreiben + Dativ)',
      accept:['ich schreibe meiner freundin'], explain:'"meine Freundin" becomes "meiner Freundin" in the dative.'},
    {id:'l11e5', type:'match', category:'dativ', prompt:'Match each German dative preposition to its meaning.',
      pairs:[{de:'mit',en:'with'},{de:'nach',en:'to / after'},{de:'zu',en:'to'},{de:'seit',en:'since'}],
      explain:'mit, nach, zu, von, bei, aus, seit always take the dative case \u2014 worth memorizing as a fixed set.'},
  ],
},
];

/* ---------------- PLACEMENT TEST ---------------- */
const PLACEMENT_TEST = [
  {id:'p1', level:'A1', category:'vocab', prompt:'"Guten Tag" means:', options:['Good night','Hello / good day','Goodbye','Thank you'], correct:'Hello / good day'},
  {id:'p2', level:'A1', category:'articles', prompt:'What is the article for "Buch" (book)?', options:['der','die','das'], correct:'das'},
  {id:'p3', level:'A1', category:'verb-conjugation', prompt:'Complete: "Er ___ aus Syrien." (kommen)', options:['komme','kommst','kommt','kommen'], correct:'kommt'},
  {id:'p4', level:'A1', category:'akkusativ', prompt:'Complete: "Ich kaufe ___ Apfel."', options:['der','den','dem'], correct:'den'},
  {id:'p5', level:'A2', category:'perfekt', prompt:'Complete: "Ich ___ Deutsch gelernt."', options:['bin','habe','ist'], correct:'habe'},
  {id:'p6', level:'A2', category:'perfekt', prompt:'Complete: "Wir ___ nach Hause gegangen."', options:['haben','sind','ist'], correct:'sind'},
  {id:'p7', level:'A2', category:'modal-verbs', prompt:'Complete: "Kannst du mir ___?" (helfen)', options:['helfen','hilfst','half'], correct:'helfen'},
  {id:'p8', level:'A2', category:'dativ', prompt:'Complete: "Ich fahre mit ___ Bus."', options:['der','den','dem'], correct:'dem'},
  {id:'p9', level:'B1', category:'word-order', prompt:'Which sentence has correct word order?', options:['Ich bleibe zu Hause, weil es regnet.','Ich bleibe zu Hause, weil regnet es.','Ich bleibe zu Hause, weil es regnet heute.'], correct:'Ich bleibe zu Hause, weil es regnet.'},
  {id:'p10', level:'B1', category:'grammar', prompt:'Which sentence correctly uses a subordinate clause?', options:['Ich denke, dass er kommt.','Ich denke, dass kommt er.','Ich denke dass er kommt morgen.'], correct:'Ich denke, dass er kommt.'},
  {id:'p11', level:'B1', category:'vocab', prompt:'"Die Bewerbung" means:', options:['The interview','The application','The appointment','The contract'], correct:'The application'},
  {id:'p12', level:'B1', category:'grammar', prompt:'Which is the correct Konjunktiv II form of "Ich habe Zeit" (hypothetical)?', options:['Ich hätte Zeit.','Ich habte Zeit.','Ich haben Zeit.'], correct:'Ich hätte Zeit.'},
  {id:'p13', level:'B2', category:'vocab', prompt:'"Die Voraussetzung" most nearly means:', options:['The prerequisite','The result','The exception','The opinion'], correct:'The prerequisite'},
  {id:'p14', level:'B2', category:'grammar', prompt:'Which is a correctly formed passive sentence?', options:['Das Haus wird gebaut.','Das Haus baut wird.','Das Haus ist bauen.'], correct:'Das Haus wird gebaut.'},
  {id:'p15', level:'C1', category:'vocab', prompt:'"Nichtsdestotrotz" means:', options:['Nevertheless','Consequently','Meanwhile','Presumably'], correct:'Nevertheless'},
  {id:'p16', level:'C1', category:'grammar', prompt:'Which sentence uses Konjunktiv I correctly for reported speech?', options:['Er sagte, er sei müde.','Er sagte, er ist müde gewesen sein.','Er sagte, er wäre müde gehabt.'], correct:'Er sagte, er sei müde.'},
];

/* Ordered CEFR levels, used for progress calc and Learn-view grouping */
const CEFR_LEVELS = ['A1','A2','B1','B2','C1','C2'];
